// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/texture/projective_texturer.hpp"

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>

#include "volumetric_kit/recon/core/allocator.hpp"
#include "volumetric_kit/recon/core/compute_kernel.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "texture_score_comp.spv.hpp"

namespace volumetric_kit::recon::texture {
namespace {

using volume::DepthCameraParams;

// Local group size, matching `layout(local_size_x = 256)` in the kernel.
constexpr std::uint32_t kLocalSize = 256;

// The push-constant block (mirrors `PushConstants` in texture_common.glsl): the
// triangle count, the occlusion distance threshold, and the vertex count that
// bounds the shader's index -> vertex addressing. All scalars, so under scalar
// block layout each lands at its host offset. A drift is a compile error, not
// silent misprojection -- the discipline the volume/tsdf/mesh PODs follow.
struct PushConstants {
  std::uint32_t num_triangles;
  float occlusion_threshold;
  std::uint32_t num_vertices;
};
static_assert(sizeof(PushConstants) == 12, "PushConstants must be 12 bytes");
static_assert(offsetof(PushConstants, num_triangles) == 0,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, occlusion_threshold) == 4,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, num_vertices) == 8,
              "PushConstants layout drift");

// group_count / storage_buffer / upload_storage_buffer are shared across the
// compute tiers -- see core/compute_util.hpp.

}  // namespace

Result<ProjectiveTexturer> ProjectiveTexturer::create(Device& device,
                                                      Allocator& allocator) {
  const VkDevice dev = device.handle();

  ProjectiveTexturer tex;
  tex.device_ = &device;
  tex.allocator_ = &allocator;

  // The view-selection kernel: 4 storage-buffer bindings (vertices, indices,
  // depth, camera) + the PushConstants range. KernelSetBuilder builds its
  // layout
  // + pipeline and allocates its set from a shared pool (sized to the exact
  // descriptor total).
  VkPushConstantRange push_range{};
  push_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push_range.offset = 0;
  push_range.size = sizeof(PushConstants);
  KernelSetBuilder kb(dev);
  VR_TRY(kb.add(tex.kernel_, vr_texture_score_comp_spv,
                vr_texture_score_comp_spv_size, 4, &push_range));
  VR_ASSIGN(tex.pool_, kb.build());

  // A 1-D dispatch's groupCountX is capped by maxComputeWorkGroupCount[0];
  // cache it so texture() can reject an over-large triangle count as a clean
  // error rather than risk a device-lost on a min-spec GPU (the guard
  // dispatch() enforces).
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  tex.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  // The ceiling on a single storage-buffer binding's range; texture() rejects a
  // vertex / index / depth buffer larger than this with a clean error rather
  // than an opaque allocation failure or device-lost (mirrors the mesh tier).
  tex.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;

  // The camera params are fixed-size, so persist the SSBO (bound once at
  // binding 3) and rewrite its contents each texture() -- not a per-call
  // allocation, mirroring the tsdf tier's camera SSBO.
  VR_ASSIGN(tex.cam_buf_, storage_buffer(allocator, sizeof(DepthCameraParams),
                                         HostAccess::SequentialWrite));
  tex.kernel_.set.write_storage_buffer(3, tex.cam_buf_.handle(), 0,
                                       VK_WHOLE_SIZE);

  return tex;
}

Status ProjectiveTexturer::texture(mesh::Mesh& mesh, const float* depth,
                                   const DepthCameraParams& cam,
                                   float occlusion_threshold) {
  if (!valid()) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: moved-from texturer");
  }
  if (depth == nullptr) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: depth is null");
  }
  if (cam.width == 0 || cam.height == 0) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: camera image is empty");
  }
  if (mesh.indices.size() % 3 != 0) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: index count is not a multiple of three");
  }
  // An empty mesh is a no-op success (nothing to texture), matching the tsdf
  // tier's empty-active-set early return.
  if (mesh.empty()) {
    return {};
  }
  const std::size_t triangle_count = mesh.triangle_count();
  if (triangle_count > std::numeric_limits<std::uint32_t>::max()) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: triangle count exceeds 2^32");
  }

  // A storage-buffer binding may not exceed maxStorageBufferRange; reject an
  // over-large mesh or depth image with a clean error rather than an opaque
  // allocation failure / device-lost (mirrors the mesh tier's arena guard).
  // This also bounds vertices.size() / indices.size() well under UINT32_MAX, so
  // the casts below -- and the shader's `tri * 3` addressing -- cannot
  // overflow.
  const auto pixels = static_cast<std::size_t>(cam.width) *
                      static_cast<std::size_t>(cam.height);
  const VkDeviceSize vertex_bytes =
      VkDeviceSize(mesh.vertices.size()) * sizeof(mesh::Vertex);
  const VkDeviceSize index_bytes =
      VkDeviceSize(mesh.indices.size()) * sizeof(std::uint32_t);
  const VkDeviceSize depth_bytes = VkDeviceSize(pixels) * sizeof(float);
  if (vertex_bytes > max_storage_buffer_range_ ||
      index_bytes > max_storage_buffer_range_ ||
      depth_bytes > max_storage_buffer_range_) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: a vertex / index / depth buffer exceeds "
        "the device maxStorageBufferRange");
  }

  // Upload the interleaved vertices (Random: the kernel writes uv0 and the host
  // reads it back), the index buffer, and the depth frame (metres). The camera
  // rides the persistent SSBO written at create().
  VR_ASSIGN(Buffer vertex_buf,
            upload_storage_buffer(*allocator_, mesh.vertices.data(),
                                  vertex_bytes, HostAccess::Random));
  VR_ASSIGN(
      Buffer index_buf,
      upload_storage_buffer(*allocator_, mesh.indices.data(), index_bytes));
  VR_ASSIGN(Buffer depth_buf,
            upload_storage_buffer(*allocator_, depth, depth_bytes));
  std::memcpy(cam_buf_.mapped(), &cam, sizeof(DepthCameraParams));

  kernel_.set.write_storage_buffer(0, vertex_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(1, index_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(2, depth_buf.handle(), 0, VK_WHOLE_SIZE);

  const PushConstants push{static_cast<std::uint32_t>(triangle_count),
                           occlusion_threshold,
                           static_cast<std::uint32_t>(mesh.vertices.size())};

  // One thread per triangle. dispatch() caps groupCountX at the device limit
  // and emits the COMPUTE->HOST barrier that makes the written uv0 visible to
  // the read-back below.
  VR_TRY(dispatch(
      *device_, kernel_, &push, sizeof(push),
      group_count(static_cast<std::uint32_t>(triangle_count), kLocalSize),
      max_workgroup_count_x_));

  // Read back only the uv0 the kernel wrote: positions / normals / colors are
  // the bytes just uploaded and unchanged, so the host already holds them --
  // copying just uv0 avoids rewriting 5/6 of each vertex with identical data.
  const auto* gpu_vertices =
      static_cast<const mesh::Vertex*>(vertex_buf.mapped());
  for (std::size_t i = 0; i < mesh.vertices.size(); ++i) {
    mesh.vertices[i].uv0 = gpu_vertices[i].uv0;
  }
  return {};
}

}  // namespace volumetric_kit::recon::texture
