// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/texture/projective_texturer.hpp"

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>

#include "volumetric_kit/recon/core/allocator.hpp"
#include "volumetric_kit/recon/core/compute_kernel.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/gpu_timer.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "texture_score_comp.spv.hpp"

namespace volumetric_kit::recon::texture {
namespace {

// Local group size, matching `layout(local_size_x = 256)` in the kernel.
constexpr std::uint32_t kLocalSize = 256;

// The push-constant block (mirrors `PushConstants` in texture_common.glsl): the
// vertex count this dispatch is bounded by, and the occlusion distance
// threshold. All scalars, so under scalar block layout each lands at its host
// offset. A drift is a compile error, not silent misprojection -- the
// discipline the volume/tsdf/mesh PODs follow.
//
// The triangle count left with the per-triangle dispatch, and so did the
// separate vertex bound it used to need: the kernel formed a vertex index from
// the index buffer and had to be told where vertices[] ended, whereas now the
// only index it forms is its own invocation id, bounded by the same count that
// sizes the dispatch.
struct PushConstants {
  std::uint32_t num_vertices;
  float occlusion_threshold;
};
static_assert(sizeof(PushConstants) == 8, "PushConstants must be 8 bytes");
static_assert(offsetof(PushConstants, num_vertices) == 0,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, occlusion_threshold) == 4,
              "PushConstants layout drift");

// group_count / storage_buffer / upload_storage_buffer are shared across the
// compute tiers -- see core/compute_util.hpp.

}  // namespace

Result<ProjectiveTexturer> ProjectiveTexturer::create(Device& device,
                                                      Allocator& allocator) {
  const VkDevice dev = device.handle();

  ProjectiveTexturer tex;
  tex.device_ = &device;
  tex.allocator_ = &allocator;

  // The view-selection kernel: 3 storage-buffer bindings (vertices, depth,
  // camera) + the PushConstants range. KernelSetBuilder builds its layout
  // + pipeline and allocates its set from a shared pool (sized to the exact
  // descriptor total).
  //
  // Three, not four: the per-vertex dispatch never addresses a vertex through
  // an index, so the index buffer is not bound at all. The remaining three are
  // renumbered to close the gap rather than leaving binding 1 unused, since the
  // set layout comes from SPIR-V reflection and a hole in it would be a
  // standing invitation to write the wrong slot.
  VkPushConstantRange push_range{};
  push_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push_range.offset = 0;
  push_range.size = sizeof(PushConstants);
  KernelSetBuilder kb(dev);
  VR_TRY(kb.add(tex.kernel_, vr_texture_score_comp_spv,
                vr_texture_score_comp_spv_size, 3, &push_range));
  VR_ASSIGN(tex.pool_, kb.build());

  // A 1-D dispatch's groupCountX is capped by maxComputeWorkGroupCount[0];
  // cache it so texture() can reject an over-large triangle count as a clean
  // error rather than risk a device-lost on a min-spec GPU (the guard
  // dispatch() enforces).
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  tex.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  // The device-span collector; see the member's declaration, and GpuTimer for
  // why a pool that will not allocate cannot fail this create().
  VR_ASSIGN(tex.gpu_timer_, GpuTimer::create(device));
  // The ceiling on a single storage-buffer binding's range; texture() rejects a
  // vertex / index / depth buffer larger than this with a clean error rather
  // than an opaque allocation failure or device-lost (mirrors the mesh tier).
  tex.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;

  // The camera params are fixed-size, so persist the SSBO (bound once at
  // binding 2) and rewrite its contents each texture() -- not a per-call
  // allocation, mirroring the tsdf tier's camera SSBO.
  VR_ASSIGN(tex.cam_buf_, storage_buffer(allocator, sizeof(DepthCameraParams),
                                         HostAccess::SequentialWrite));
  tex.kernel_.set.write_storage_buffer(2, tex.cam_buf_.handle(), 0,
                                       VK_WHOLE_SIZE);

  return tex;
}

Status ProjectiveTexturer::texture(const mesh::DeviceMesh& mesh,
                                   const float* depth,
                                   const DepthCameraParams& cam,
                                   float occlusion_threshold,
                                   StageMetrics* metrics) {
  // Before the validity check, so a refused call still costs its row: a stage
  // silent on failure reads as a stage that did not run. Inert when null, and
  // it publishes both halves on every return below -- this overload has five
  // between here and the dispatch.
  GpuStageScope stage(metrics, gpu_timer_, "texture");
  if (!valid()) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: moved-from texturer");
  }
  if (depth == nullptr) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: depth is null");
  }
  if (cam.width == 0 || cam.height == 0) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: camera image is empty");
  }
  // An empty mesh is a no-op success, as in the host overload -- and it is the
  // one case where a DeviceMesh legitimately names no buffers.
  if (mesh.empty()) {
    return {};
  }
  if (!mesh.valid()) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: the DeviceMesh names no buffers");
  }
  // valid() is a handle-non-null check and says nothing about whether these
  // handles are still the producer's. It has to be asked here, not only in
  // MarchingCubes::download: this pass *binds and writes* the buffers, so a
  // superseded view is worse than a stale read. If the later extract grew the
  // arena, the old VkBuffer was destroyed synchronously (no fence, no deferred
  // retire) and binding it is a use-after-free -- undefined with validation
  // layers off, the shipping configuration. If it did not grow, the pass
  // silently rewrites the *current* extract's uv0 under this view's stale
  // triangle count. The reading path was guarded and the writing path was not.
  if (!mesh.is_current()) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: the DeviceMesh has been superseded by a "
        "later extract on its producer (texture it before extracting again)");
  }
  // No shared-vertex refusal any more, and its absence is the point of this
  // pass's shape. It used to refuse a `DeviceMesh::shares_vertices` mesh
  // outright, because deciding visibility per TRIANGLE and writing uv0 per
  // VERTEX is well-defined only while a vertex belongs to one triangle -- a
  // shared vertex whose triangles disagreed was written by whichever thread
  // ran last. The dispatch is per vertex now, so there is no second writer and
  // nothing to disagree; see the kernel's header for what that costs at a
  // silhouette and how the uv-carrying encoding bounds it.
  //
  // A packed multi-camera atlas will still need a per-PRIMITIVE camera id, and
  // that is a genuinely different problem: a triangle whose vertices index
  // different sub-rects of a pack cannot be expressed per vertex however it is
  // encoded. Vertex sharing was never that problem, which is why it no longer
  // travels with the mesh as an incompatibility.

  // Only the depth frame needs a binding check here: the mesh buffers were
  // already sized (and range-checked) by the pass that created them, and are
  // bound as they are rather than re-allocated.
  const auto pixels = static_cast<std::size_t>(cam.width) *
                      static_cast<std::size_t>(cam.height);
  const VkDeviceSize depth_bytes = VkDeviceSize(pixels) * sizeof(float);
  if (depth_bytes > max_storage_buffer_range_) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: the depth buffer exceeds the device "
        "maxStorageBufferRange");
  }

  // The one transfer left in this path.
  VR_ASSIGN(Buffer depth_buf,
            upload_storage_buffer(*allocator_, depth, depth_bytes));
  std::memcpy(cam_buf_.mapped(), &cam, sizeof(DepthCameraParams));

  // Bind the producing pass's buffers directly -- no upload, and nothing to
  // read back afterwards: the kernel rewrites uv0 where the geometry already
  // lives, for the next device consumer to use.
  kernel_.set.write_storage_buffer(0, mesh.vertices, 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(1, depth_buf.handle(), 0, VK_WHOLE_SIZE);

  const PushConstants push{mesh.vertex_count, occlusion_threshold};
  return dispatch(*device_, kernel_, &push, sizeof(push),
                  group_count(mesh.vertex_count, kLocalSize),
                  max_workgroup_count_x_, &stage);
}

Status ProjectiveTexturer::texture(mesh::Mesh& mesh, const float* depth,
                                   const DepthCameraParams& cam,
                                   float occlusion_threshold,
                                   StageMetrics* metrics) {
  // The host overload's row covers the upload and read-back this path adds on
  // top of the same dispatch -- which is the whole difference between it and
  // the device overload, and the reason both are timed under one name.
  GpuStageScope stage(metrics, gpu_timer_, "texture");
  if (!valid()) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: moved-from texturer");
  }
  if (depth == nullptr) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: depth is null");
  }
  if (cam.width == 0 || cam.height == 0) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: camera image is empty");
  }
  if (mesh.indices.size() % 3 != 0) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: index count is not a multiple of three");
  }
  // An empty mesh is a no-op success (nothing to texture), matching the tsdf
  // tier's empty-active-set early return.
  if (mesh.empty()) {
    return {};
  }
  // The dispatch is sized by the vertex count now, so that is what has to fit a
  // uint32 -- the triangle count no longer reaches the GPU at all.
  if (mesh.vertices.size() > std::numeric_limits<std::uint32_t>::max()) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: vertex count exceeds 2^32");
  }

  // A storage-buffer binding may not exceed maxStorageBufferRange; reject an
  // over-large mesh or depth image with a clean error rather than an opaque
  // allocation failure / device-lost (mirrors the mesh tier's arena guard).
  // This also bounds vertices.size() well under UINT32_MAX, so the casts below
  // cannot overflow.
  //
  // The index buffer is not checked because it is not bound: the per-vertex
  // dispatch reads no indices. Leaving it in the check would reject a mesh this
  // pass can texture perfectly well -- and would do so on the one axis vertex
  // sharing makes *larger* relative to the vertices, which is the shape this
  // pass is now meant to support.
  const auto pixels = static_cast<std::size_t>(cam.width) *
                      static_cast<std::size_t>(cam.height);
  const VkDeviceSize vertex_bytes =
      VkDeviceSize(mesh.vertices.size()) * sizeof(mesh::Vertex);
  const VkDeviceSize depth_bytes = VkDeviceSize(pixels) * sizeof(float);
  if (vertex_bytes > max_storage_buffer_range_ ||
      depth_bytes > max_storage_buffer_range_) {
    return Status::invalid_argument(
        "ProjectiveTexturer::texture: a vertex / depth buffer exceeds "
        "the device maxStorageBufferRange");
  }

  // Upload the interleaved vertices (Random: the kernel writes uv0 and the host
  // reads it back) and the depth frame (metres). The camera rides the
  // persistent SSBO written at create().
  //
  // The index buffer is no longer uploaded: the per-vertex dispatch does not
  // read it. That is the larger half of this path's transfer on a mesh the
  // caller did not share (three 4-byte indices per triangle against one 64-byte
  // vertex), so the host overload got cheaper along with the device one.
  VR_ASSIGN(Buffer vertex_buf,
            upload_storage_buffer(*allocator_, mesh.vertices.data(),
                                  vertex_bytes, HostAccess::Random));
  VR_ASSIGN(Buffer depth_buf,
            upload_storage_buffer(*allocator_, depth, depth_bytes));
  std::memcpy(cam_buf_.mapped(), &cam, sizeof(DepthCameraParams));

  kernel_.set.write_storage_buffer(0, vertex_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(1, depth_buf.handle(), 0, VK_WHOLE_SIZE);

  const PushConstants push{static_cast<std::uint32_t>(mesh.vertices.size()),
                           occlusion_threshold};

  // One thread per vertex. dispatch() caps groupCountX at the device limit
  // and emits the COMPUTE->HOST barrier that makes the written uv0 visible to
  // the read-back below.
  VR_TRY(dispatch(
      *device_, kernel_, &push, sizeof(push),
      group_count(static_cast<std::uint32_t>(mesh.vertices.size()), kLocalSize),
      max_workgroup_count_x_, &stage));

  // Read back only the uv0 the kernel wrote: positions / normals / colors are
  // the bytes just uploaded and unchanged, so the host already holds them --
  // copying just uv0 avoids rewriting 5/6 of each vertex with identical data.
  const auto* gpu_vertices =
      static_cast<const mesh::Vertex*>(vertex_buf.mapped());
  for (std::size_t i = 0; i < mesh.vertices.size(); ++i) {
    mesh.vertices[i].uv0 = gpu_vertices[i].uv0;
  }
  return {};
}

}  // namespace volumetric_kit::recon::texture
