// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/tsdf/mesh_integrator.hpp"

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <string>
#include <vector>

#include "volumetric_kit/recon/core/allocator.hpp"
#include "volumetric_kit/recon/core/command_batch.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"
#include "volumetric_kit/recon/volume/triangle_candidates.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "mesh_bin_comp.spv.hpp"
#include "mesh_bin_ranges_comp.spv.hpp"
#include "mesh_compact_bins_comp.spv.hpp"
#include "mesh_integrate_comp.spv.hpp"
#include "mesh_scan_add_comp.spv.hpp"
#include "mesh_scan_counts_comp.spv.hpp"
#include "mesh_scan_sums_comp.spv.hpp"

namespace volumetric_kit::recon::tsdf {
namespace {

using volume::AttributeView;
using volume::VoxelBlockGrid;
using volume::VoxelGridParams;

constexpr const char* kWho = "MeshIntegrator::integrate";

// Local group size, matching `layout(local_size_x = 256)` in both kernels.
constexpr std::uint32_t kLocalSize = 256;
// Bins whose starts share a window have at most window-1 entries between
// their first and last starts, plus at most kMaxBinTriangles for the last bin.
constexpr std::uint32_t kBinWindow = MeshIntegrator::kMaxDispatchBinEntries -
                                     MeshIntegrator::kMaxBinTriangles + 1;

// mesh_bin.comp's pc.pass.
constexpr std::uint32_t kPassCount = 0;
constexpr std::uint32_t kPassFill = 1;

// The distance from a point to the nearest node of a cubic lattice can reach
// half the cell's diagonal, so a shell thinner than this can fall between
// voxels and extract with holes.
constexpr float kMinShellVoxels = 0.8660254f;  // sqrt(3) / 2

// Mirrors the push-constant blocks of mesh_bin.comp and mesh_integrate.comp,
// and their MeshBin struct, under scalar block layout.
struct BinPush {
  VoxelGridParams grid;
  std::uint32_t tri_count;
  std::uint32_t pass;
};
struct IntegratePush {
  VoxelGridParams grid;
  std::uint32_t first_bin;
  std::uint32_t num_bins;
  std::uint32_t mode;
  float shell;
  std::uint32_t tick;  // the map's tick, which each block written takes
};
struct MeshBin {
  std::int32_t ptr;
  std::uint32_t begin;
  std::uint32_t count;
};
struct ScanPush {
  std::uint32_t size;
  std::uint32_t first_group;
};
struct CompactPush {
  std::uint32_t size;
  std::uint32_t voxels_per_block;
  std::uint32_t capacity;
  std::uint32_t max_bin;
  std::uint32_t first_group;
};
struct RangesPush {
  std::uint32_t size;
  std::uint32_t capacity;
  std::uint32_t window;
  std::uint32_t max_bin;
};
struct ScanSummary {
  std::uint32_t entries;
  std::uint32_t blocks;
  std::uint32_t largest_bin;
  std::uint32_t overflow;
};
struct BinRange {
  std::uint32_t first;
  std::uint32_t count;
};
static_assert(sizeof(ScanPush) == 8, "ScanPush layout drift");
static_assert(sizeof(CompactPush) == 20, "CompactPush layout drift");
static_assert(sizeof(RangesPush) == 16, "RangesPush layout drift");
static_assert(sizeof(ScanSummary) == 16, "ScanSummary layout drift");
static_assert(sizeof(BinRange) == 8, "BinRange layout drift");

static_assert(sizeof(BinPush) == 40, "BinPush must be 40 bytes");
static_assert(offsetof(BinPush, tri_count) == 32, "BinPush layout drift");
static_assert(offsetof(BinPush, pass) == 36, "BinPush layout drift");
static_assert(sizeof(IntegratePush) == 52, "IntegratePush must be 52 bytes");
static_assert(offsetof(IntegratePush, first_bin) == 32,
              "IntegratePush layout drift");
static_assert(offsetof(IntegratePush, num_bins) == 36,
              "IntegratePush layout drift");
static_assert(offsetof(IntegratePush, mode) == 40,
              "IntegratePush layout drift");
static_assert(offsetof(IntegratePush, shell) == 44,
              "IntegratePush layout drift");
static_assert(offsetof(IntegratePush, tick) == 48,
              "IntegratePush layout drift");
static_assert(sizeof(MeshBin) == 12, "MeshBin must be 12 bytes");
static_assert(offsetof(MeshBin, begin) == 4, "MeshBin layout drift");
static_assert(offsetof(MeshBin, count) == 8, "MeshBin layout drift");

std::uint32_t group_count(std::uint32_t items) {
  return volumetric_kit::recon::group_count(items, kLocalSize);
}

}  // namespace

Result<MeshIntegrator> MeshIntegrator::create(Device& device,
                                              Allocator& allocator) {
  MeshIntegrator integ;
  integ.device_ = &device;
  integ.allocator_ = &allocator;

  // mesh_bin takes 9 storage buffers: 0 hash entries, 1 vertices, 2 indices,
  // 3 candidate offsets, 4 per-slot counts then cursors, 5 per-item slots,
  // 6 per-slot coordinates, 7 missing-block counter, 8 bins. mesh_integrate
  // takes 7: 0 tsdf, 1 weight, 2 vertices, 3 indices, 4 block bins, 5 bins,
  // 6 per-slot coordinates. These counts and the shaders move together.
  VkPushConstantRange bin_range{};
  bin_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  bin_range.size = sizeof(BinPush);
  VkPushConstantRange integrate_range{};
  integrate_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  integrate_range.size = sizeof(IntegratePush);
  KernelSetBuilder kb(device);
  VR_TRY(kb.add(integ.bin_, "tsdf_mesh_bin", vr_mesh_bin_comp_spv,
                vr_mesh_bin_comp_spv_size, 9, &bin_range));
  VR_TRY(kb.add(integ.integrate_, "tsdf_mesh_integrate",
                vr_mesh_integrate_comp_spv, vr_mesh_integrate_comp_spv_size, 8,
                &integrate_range));
  VkPushConstantRange scan_range{VK_SHADER_STAGE_COMPUTE_BIT, 0,
                                 sizeof(ScanPush)};
  VR_TRY(kb.add(integ.scan_counts_, "tsdf_mesh_scan_counts",
                vr_mesh_scan_counts_comp_spv, vr_mesh_scan_counts_comp_spv_size,
                2, &scan_range));
  for (ComputeKernel& kernel : integ.scan_sums_) {
    VR_TRY(kb.add(kernel, "tsdf_mesh_scan_sums", vr_mesh_scan_sums_comp_spv,
                  vr_mesh_scan_sums_comp_spv_size, 2, &scan_range));
  }
  for (ComputeKernel& kernel : integ.scan_add_) {
    VR_TRY(kb.add(kernel, "tsdf_mesh_scan_add", vr_mesh_scan_add_comp_spv,
                  vr_mesh_scan_add_comp_spv_size, 2, &scan_range));
  }
  VkPushConstantRange compact_range{VK_SHADER_STAGE_COMPUTE_BIT, 0,
                                    sizeof(CompactPush)};
  VR_TRY(kb.add(integ.compact_bins_, "tsdf_mesh_compact_bins",
                vr_mesh_compact_bins_comp_spv,
                vr_mesh_compact_bins_comp_spv_size, 4, &compact_range));
  VkPushConstantRange ranges_range{VK_SHADER_STAGE_COMPUTE_BIT, 0,
                                   sizeof(RangesPush)};
  VR_TRY(kb.add(integ.bin_ranges_, "tsdf_mesh_bin_ranges",
                vr_mesh_bin_ranges_comp_spv, vr_mesh_bin_ranges_comp_spv_size,
                3, &ranges_range));
  VR_ASSIGN(integ.pool_, kb.build());

  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  integ.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  integ.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;
  VR_ASSIGN(integ.gpu_timer_, GpuTimer::create(device));

  VR_ASSIGN(integ.missing_,
            device_storage_buffer(allocator, sizeof(std::uint32_t)));
  VR_ASSIGN(integ.dummy_,
            device_storage_buffer(allocator, sizeof(std::uint32_t)));
  integ.bin_.set.write_storage_buffer(7, integ.missing_.handle(), 0,
                                      VK_WHOLE_SIZE);

  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(integ.missing_.handle()),
                         "tsdf.mesh_missing");
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(integ.dummy_.handle()),
                         "tsdf.mesh_dummy");
  return integ;
}

Status MeshIntegrator::ensure_scratch(Buffer& buffer, VkDeviceSize bytes,
                                      const char* name) {
  return ensure_device_scratch(*device_, *allocator_, buffer, bytes,
                               max_storage_buffer_range_, name);
}

Result<MeshIntegrateStats> MeshIntegrator::integrate(
    VoxelBlockGrid& grid, const Vec3f* vertices, std::uint32_t vertex_count,
    const std::uint32_t* indices, std::uint32_t triangle_count,
    const MeshSdfParams& params, StageMetrics* metrics) {
  // Opened before the checks so a refused call still costs its row, as
  // TsdfIntegrator::integrate.
  GpuStageScope stage(metrics, gpu_timer_, "mesh integrate");
  if (!valid()) {
    return Status::invalid_argument(std::string(kWho) +
                                    ": moved-from integrator");
  }
  const VoxelGridParams& g = grid.grid();
  const bool is_signed = params.mode == MeshSdfMode::Signed;
  if (!is_signed && params.mode != MeshSdfMode::Shell) {
    return Status::invalid_argument(std::string(kWho) + ": unknown mode");
  }
  const float shell_m = params.shell_voxels * g.voxel_size;
  if (!is_signed &&
      !(params.shell_voxels >= kMinShellVoxels && shell_m < g.trunc_dist)) {
    return Status::invalid_argument(
        std::string(kWho) +
        ": shell_voxels must be at least sqrt(3)/2, or the shell can fall "
        "between voxels, and thinner than trunc_dist, or nothing observed "
        "reads as outside");
  }

  VR_ASSIGN(AttributeView tsdf_view, grid.attribute("tsdf"));
  VR_ASSIGN(AttributeView weight_view, grid.attribute("weight"));
  if (tsdf_view.element_size != sizeof(float) ||
      weight_view.element_size != sizeof(float)) {
    return Status::invalid_argument(std::string(kWho) +
                                    ": tsdf/weight attributes must be float");
  }

  MeshIntegrateStats stats;
  if (triangle_count == 0) {
    return stats;
  }

  // Every input is per-call and bound whole, so each is checked against what
  // one binding may cover -- first, since each size is known from the counts
  // alone, and a mesh too large to bind should not pay the host passes below
  // to find out. The hash entries are the one buffer another tier sized, and
  // are bound with their real range.
  const auto num_blocks = static_cast<std::uint32_t>(g.num_blocks);
  const VkDeviceSize vertex_bytes = VkDeviceSize(vertex_count) * sizeof(Vec3f);
  const VkDeviceSize index_bytes =
      VkDeviceSize(triangle_count) * 3 * sizeof(std::uint32_t);
  const VkDeviceSize offset_bytes =
      (VkDeviceSize(triangle_count) + 1) * sizeof(std::uint32_t);
  const VkDeviceSize count_bytes =
      VkDeviceSize(num_blocks) * sizeof(std::uint32_t);
  const VkDeviceSize coord_bytes = VkDeviceSize(num_blocks) * sizeof(Vec3i);
  const VkDeviceSize entries_bytes = grid.map().entries_buffer_size();
  const struct {
    const char* what;
    VkDeviceSize bytes;
  } ranges[] = {
      {"the vertex buffer", vertex_bytes},
      {"the index buffer", index_bytes},
      {"the candidate offsets", offset_bytes},
      {"the bin counts", count_bytes},
      {"the bin coordinates", coord_bytes},
      {"the hash entries", entries_bytes},
  };
  for (const auto& r : ranges) {
    VR_TRY(
        check_storage_buffer_range((std::string(kWho) + ": " + r.what).c_str(),
                                   r.bytes, max_storage_buffer_range_));
  }

  // The candidate decomposition allocate_from_triangles dispatched over. Also
  // where every index is bounds-checked and a degenerate triangle dropped.
  VR_ASSIGN(std::vector<std::uint32_t> offsets,
            volume::triangle_candidate_offsets(g, vertices, vertex_count,
                                               indices, triangle_count, kWho));
  const std::uint32_t work_items = offsets[triangle_count];
  if (work_items == 0) {
    return stats;  // every triangle degenerate or non-finite
  }
  for (std::uint32_t t = 0; t < triangle_count; ++t) {
    if (offsets[t + 1] > offsets[t]) ++stats.triangles;
  }
  const VkDeviceSize item_bytes =
      VkDeviceSize(work_items) * sizeof(std::uint32_t);
  VR_TRY(check_storage_buffer_range(
      (std::string(kWho) + ": the work-item slots").c_str(), item_bytes,
      max_storage_buffer_range_));

  // All bulk storage is retained. Only inputs and the count/reset state are
  // refreshed, including when a different mesh or grid fits the same capacity.
  VR_TRY(ensure_scratch(vertices_, vertex_bytes, "tsdf.mesh_vertices"));
  VR_TRY(ensure_scratch(indices_, index_bytes, "tsdf.mesh_indices"));
  VR_TRY(ensure_scratch(offsets_, offset_bytes, "tsdf.mesh_offsets"));
  VR_TRY(ensure_scratch(counts_, count_bytes, "tsdf.mesh_bin_counts"));
  VR_TRY(ensure_scratch(coordinates_, coord_bytes, "tsdf.mesh_coordinates"));
  VR_TRY(ensure_scratch(item_slots_, item_bytes, "tsdf.mesh_item_slots"));

  // 256-way hierarchy: even one leaf group is scanned once, leaving its
  // exclusive prefix zero and its aggregate in a separate root. At most
  // three summary passes cover every uint32-sized input.
  std::array<std::uint32_t, 4> level_sizes{};
  level_sizes[0] = group_count(num_blocks);
  std::size_t root = 0;
  do {
    level_sizes[root + 1] = group_count(level_sizes[root]);
    ++root;
  } while (level_sizes[root] > 1);
  for (std::size_t i = 0; i <= root; ++i) {
    VR_TRY(ensure_scratch(scan_levels_[i],
                          VkDeviceSize(level_sizes[i]) * sizeof(ScanSummary),
                          "tsdf.mesh_scan_level"));
  }
  const auto vpb = static_cast<std::uint32_t>(g.voxels_per_block);
  // Candidate work is an upper bound on bin entries. These 8-byte ranges
  // therefore fit in <=34,960 bytes even for UINT32_MAX candidates. Reading
  // the upper bound lets validation and chunk planning share one submission.
  const std::uint32_t range_count = 1u + (work_items - 1u) / kBinWindow;
  const VkDeviceSize range_bytes = VkDeviceSize(range_count) * sizeof(BinRange);
  VR_TRY(ensure_scratch(ranges_, range_bytes, "tsdf.mesh_dispatch_ranges"));
  // A compact list needs no full-capacity reservation. If this guess is short,
  // the GPU leaves local prefixes intact and only compaction/ranges retry.
  VR_TRY(ensure_scratch(
      blocks_, VkDeviceSize(std::min(num_blocks, 4096u)) * sizeof(MeshBin),
      "tsdf.mesh_blocks"));

  const auto bind = [](ComputeKernel& kernel, std::uint32_t binding,
                       const Buffer& buffer) {
    kernel.set.write_storage_buffer(binding, buffer.handle(), 0, VK_WHOLE_SIZE);
  };
  bin_.set.write_storage_buffer(0, grid.map().entries_buffer(), 0,
                                entries_bytes);
  bind(bin_, 1, vertices_);
  bind(bin_, 2, indices_);
  bind(bin_, 3, offsets_);
  bind(bin_, 4, counts_);
  bind(bin_, 5, item_slots_);
  bind(bin_, 6, coordinates_);
  bind(bin_, 8, dummy_);
  bind(scan_counts_, 0, counts_);
  bind(scan_counts_, 1, scan_levels_[0]);
  for (std::size_t i = 0; i < root; ++i) {
    bind(scan_sums_[i], 0, scan_levels_[i]);
    bind(scan_sums_[i], 1, scan_levels_[i + 1]);
    if (i + 1 < root) {
      bind(scan_add_[i], 0, scan_levels_[i]);
      bind(scan_add_[i], 1, scan_levels_[i + 1]);
    }
  }
  bind(compact_bins_, 0, counts_);
  bind(compact_bins_, 1, scan_levels_[0]);
  bind(compact_bins_, 2, scan_levels_[root]);
  bind(compact_bins_, 3, blocks_);
  bind(bin_ranges_, 0, blocks_);
  bind(bin_ranges_, 1, scan_levels_[root]);
  bind(bin_ranges_, 2, ranges_);

  // Scan a large capacity in dispatch slices rather than adding a smaller
  // capacity limit on devices with a low maxComputeWorkGroupCount[0]. Sets
  // stay unchanged within the batch; only push constants change per slice.
  const auto scan = [&](CommandBatch& batch, const ComputeKernel& kernel,
                        std::uint32_t size) -> Status {
    const std::uint32_t groups = group_count(size);
    for (std::uint32_t first = 0; first < groups;) {
      const std::uint32_t n = std::min(groups - first, max_workgroup_count_x_);
      const ScanPush push{size, first};
      VR_TRY(batch.dispatch(kernel, &push, sizeof(push), n,
                            max_workgroup_count_x_, &stage));
      first += n;
    }
    return {};
  };
  std::vector<BinRange> dispatch_ranges(range_count);
  const auto compact = [&](CommandBatch& batch) -> Status {
    const auto capacity =
        static_cast<std::uint32_t>(blocks_.size() / sizeof(MeshBin));
    const std::uint32_t groups = group_count(num_blocks);
    for (std::uint32_t first = 0; first < groups;) {
      const std::uint32_t n = std::min(groups - first, max_workgroup_count_x_);
      const CompactPush push{num_blocks, vpb, capacity, kMaxBinTriangles,
                             first};
      VR_TRY(batch.dispatch(compact_bins_, &push, sizeof(push), n,
                            max_workgroup_count_x_, &stage));
      first += n;
    }
    const RangesPush push{range_count, capacity, kBinWindow, kMaxBinTriangles};
    VR_TRY(batch.dispatch(bin_ranges_, &push, sizeof(push),
                          group_count(range_count), max_workgroup_count_x_,
                          &stage));
    VR_TRY(batch.readback(ranges_, 0, range_bytes, dispatch_ranges.data()));
    return {};
  };

  ScanSummary summary{};
  std::uint32_t missing = 0;
  {
    CommandBatch batch(*device_, *allocator_);
    VR_TRY(batch.upload(vertices_, 0, vertices, vertex_bytes));
    VR_TRY(batch.upload(indices_, 0, indices, index_bytes));
    VR_TRY(batch.upload(offsets_, 0, offsets.data(), offset_bytes));
    VR_TRY(batch.fill(counts_, 0, count_bytes, 0u));
    VR_TRY(batch.fill(missing_, 0, sizeof(missing), 0u));
    const BinPush push{g, triangle_count, kPassCount};
    VR_TRY(batch.dispatch(bin_, &push, sizeof(push), group_count(work_items),
                          max_workgroup_count_x_, &stage));
    VR_TRY(scan(batch, scan_counts_, num_blocks));
    for (std::size_t i = 0; i < root; ++i) {
      VR_TRY(scan(batch, scan_sums_[i], level_sizes[i]));
    }
    for (std::size_t i = root - 1; i > 0; --i) {
      VR_TRY(scan(batch, scan_add_[i - 1], level_sizes[i - 1]));
    }
    VR_TRY(compact(batch));
    VR_TRY(batch.readback(missing_, 0, sizeof(missing), &missing));
    VR_TRY(batch.readback(scan_levels_[root], 0, sizeof(summary), &summary));
    VR_TRY(batch.submit());
  }
  if (missing != 0) {
    return Status::invalid_argument(
        std::string(kWho) +
        ": the band reaches blocks that are not allocated (" +
        std::to_string(missing) +
        " triangle-block pair(s) found none); run "
        "VoxelHashMap::allocate_from_triangles with this mesh first, and "
        "check it reported no failures");
  }
  if (summary.overflow != 0) {
    return Status::invalid_argument(std::string(kWho) +
                                    ": bin entries exceed 2^32");
  }
  if (summary.blocks == 0) return stats;
  if (summary.largest_bin > kMaxBinTriangles) {
    return Status::invalid_argument(
        std::string(kWho) + ": a block's bin holds " +
        std::to_string(summary.largest_bin) +
        " triangles, past kMaxBinTriangles (" +
        std::to_string(kMaxBinTriangles) +
        "); the mesh is far finer than the grid's voxels -- decimate it "
        "toward the voxel size");
  }
  const VkDeviceSize bins_bytes =
      VkDeviceSize(summary.entries) * sizeof(std::uint32_t);
  const VkDeviceSize block_bytes =
      VkDeviceSize(summary.blocks) * sizeof(MeshBin);
  VR_TRY(check_storage_buffer_range((std::string(kWho) + ": the bins").c_str(),
                                    bins_bytes, max_storage_buffer_range_));
  VR_TRY(check_storage_buffer_range(
      (std::string(kWho) + ": the block list").c_str(), block_bytes,
      max_storage_buffer_range_));
  const std::uint64_t max_threads = std::min<std::uint64_t>(
      std::uint64_t{max_workgroup_count_x_} * kLocalSize,
      std::numeric_limits<std::uint32_t>::max());
  const auto max_dispatch_blocks =
      static_cast<std::uint32_t>(max_threads / vpb);
  if (max_dispatch_blocks == 0) {
    return Status::invalid_argument(
        std::string(kWho) +
        ": voxels_per_block exceeds what one dispatch can launch");
  }
  if (blocks_.size() < block_bytes) {
    VR_TRY(ensure_scratch(blocks_, block_bytes, "tsdf.mesh_blocks"));
    bind(compact_bins_, 3, blocks_);
    bind(bin_ranges_, 0, blocks_);
    CommandBatch batch(*device_, *allocator_);
    VR_TRY(compact(batch));
    VR_TRY(batch.submit());
  }
  VR_TRY(ensure_scratch(bins_, bins_bytes, "tsdf.mesh_bins"));

  bind(bin_, 8, bins_);
  bind(integrate_, 0, *tsdf_view.buffer);
  bind(integrate_, 1, *weight_view.buffer);
  bind(integrate_, 2, vertices_);
  bind(integrate_, 3, indices_);
  bind(integrate_, 4, blocks_);
  bind(integrate_, 5, bins_);
  bind(integrate_, 6, coordinates_);
  bind(integrate_, 7, grid.map().stamps_buffer());
  grid.map().advance_tick();
  const std::uint32_t tick = grid.map().tick();

  // Every range satisfies the entry budget. Splitting further for the device
  // thread limit only reduces its work. Keep one submission per write, with
  // the fill in the first: combining them would undo the watchdog contract.
  const BinPush fill_push{g, triangle_count, kPassFill};
  for (const BinRange& range : dispatch_ranges) {
    for (std::uint32_t offset = 0; offset < range.count;) {
      const std::uint32_t n =
          std::min(range.count - offset, max_dispatch_blocks);
      CommandBatch batch(*device_, *allocator_);
      if (stats.dispatches == 0) {
        VR_TRY(batch.dispatch(bin_, &fill_push, sizeof(fill_push),
                              group_count(work_items), max_workgroup_count_x_,
                              &stage));
      }
      const IntegratePush push{g,
                               range.first + offset,
                               n,
                               static_cast<std::uint32_t>(params.mode),
                               is_signed ? 0.0f : shell_m,
                               tick};
      VR_TRY(batch.dispatch(integrate_, &push, sizeof(push),
                            group_count(n * vpb), max_workgroup_count_x_,
                            &stage));
      VR_TRY(batch.submit());
      ++stats.dispatches;
      offset += n;
    }
  }
  stats.blocks = summary.blocks;
  stats.bin_entries = summary.entries;
  return stats;
}

}  // namespace volumetric_kit::recon::tsdf
