// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/tsdf/mesh_integrator.hpp"

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>
#include <string>
#include <vector>

#include "volumetric_kit/recon/core/allocator.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"
#include "volumetric_kit/recon/volume/triangle_candidates.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "mesh_bin_comp.spv.hpp"
#include "mesh_integrate_comp.spv.hpp"

namespace volumetric_kit::recon::tsdf {
namespace {

using volume::AttributeView;
using volume::VoxelBlockGrid;
using volume::VoxelGridParams;

constexpr const char* kWho = "MeshIntegrator::integrate";

// Local group size, matching `layout(local_size_x = 256)` in both kernels.
constexpr std::uint32_t kLocalSize = 256;

// mesh_bin.comp's pc.pass.
constexpr std::uint32_t kPassCount = 0;
constexpr std::uint32_t kPassFill = 1;

// The distance from a point to the nearest node of a cubic lattice can reach
// half the cell's diagonal, so a shell thinner than this can fall between
// voxels and extract with holes.
constexpr float kMinShellVoxels = 0.8660254f;  // sqrt(3) / 2

// Mirrors the push-constant blocks of mesh_bin.comp and mesh_integrate.comp,
// and their MeshBin struct, under scalar block layout.
struct BinPush {
  VoxelGridParams grid;
  std::uint32_t tri_count;
  std::uint32_t pass;
};
struct IntegratePush {
  VoxelGridParams grid;
  std::uint32_t first_bin;
  std::uint32_t num_bins;
  std::uint32_t mode;
  float shell;
};
struct MeshBin {
  Vec3i coord;
  std::int32_t ptr;
  std::uint32_t begin;
  std::uint32_t count;
};

static_assert(sizeof(BinPush) == 40, "BinPush must be 40 bytes");
static_assert(offsetof(BinPush, tri_count) == 32, "BinPush layout drift");
static_assert(offsetof(BinPush, pass) == 36, "BinPush layout drift");
static_assert(sizeof(IntegratePush) == 48, "IntegratePush must be 48 bytes");
static_assert(offsetof(IntegratePush, first_bin) == 32,
              "IntegratePush layout drift");
static_assert(offsetof(IntegratePush, num_bins) == 36,
              "IntegratePush layout drift");
static_assert(offsetof(IntegratePush, mode) == 40,
              "IntegratePush layout drift");
static_assert(offsetof(IntegratePush, shell) == 44,
              "IntegratePush layout drift");
static_assert(sizeof(MeshBin) == 24, "MeshBin must be 24 bytes");
static_assert(offsetof(MeshBin, ptr) == 12, "MeshBin layout drift");
static_assert(offsetof(MeshBin, begin) == 16, "MeshBin layout drift");
static_assert(offsetof(MeshBin, count) == 20, "MeshBin layout drift");

std::uint32_t group_count(std::uint32_t items) {
  return volumetric_kit::recon::group_count(items, kLocalSize);
}

// A storage buffer only the device touches. storage_buffer is host-visible by
// design, which on a discrete GPU puts a buffer the kernels stream across the
// bus.
Result<Buffer> device_storage_buffer(Allocator& allocator, VkDeviceSize bytes) {
  BufferDesc desc;
  desc.size = bytes;
  desc.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
  desc.memory = MemoryUsage::DeviceLocal;
  return allocator.create_buffer(desc);
}

}  // namespace

Result<MeshIntegrator> MeshIntegrator::create(Device& device,
                                              Allocator& allocator) {
  MeshIntegrator integ;
  integ.device_ = &device;
  integ.allocator_ = &allocator;

  // mesh_bin takes 9 storage buffers: 0 hash entries, 1 vertices, 2 indices,
  // 3 candidate offsets, 4 per-slot counts then cursors, 5 per-item slots,
  // 6 per-slot coordinates, 7 missing-block counter, 8 bins. mesh_integrate
  // takes 6: 0 tsdf, 1 weight, 2 vertices, 3 indices, 4 block bins, 5 bins.
  // These counts and the shaders move together.
  VkPushConstantRange bin_range{};
  bin_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  bin_range.size = sizeof(BinPush);
  VkPushConstantRange integrate_range{};
  integrate_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  integrate_range.size = sizeof(IntegratePush);
  KernelSetBuilder kb(device);
  VR_TRY(kb.add(integ.bin_, "tsdf_mesh_bin", vr_mesh_bin_comp_spv,
                vr_mesh_bin_comp_spv_size, 9, &bin_range));
  VR_TRY(kb.add(integ.integrate_, "tsdf_mesh_integrate",
                vr_mesh_integrate_comp_spv, vr_mesh_integrate_comp_spv_size, 6,
                &integrate_range));
  VR_ASSIGN(integ.pool_, kb.build());

  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  integ.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  integ.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;
  VR_ASSIGN(integ.gpu_timer_, GpuTimer::create(device));

  VR_ASSIGN(integ.missing_, storage_buffer(allocator, sizeof(std::uint32_t)));
  VR_ASSIGN(integ.dummy_, storage_buffer(allocator, sizeof(std::uint32_t)));
  integ.bin_.set.write_storage_buffer(7, integ.missing_.handle(), 0,
                                      VK_WHOLE_SIZE);

  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(integ.missing_.handle()),
                         "tsdf.mesh_missing");
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(integ.dummy_.handle()),
                         "tsdf.mesh_dummy");
  return integ;
}

Result<MeshIntegrateStats> MeshIntegrator::integrate(
    VoxelBlockGrid& grid, const Vec3f* vertices, std::uint32_t vertex_count,
    const std::uint32_t* indices, std::uint32_t triangle_count,
    const MeshSdfParams& params, StageMetrics* metrics) {
  // Opened before the checks so a refused call still costs its row, as
  // TsdfIntegrator::integrate.
  GpuStageScope stage(metrics, gpu_timer_, "mesh integrate");
  if (!valid()) {
    return Status::invalid_argument(std::string(kWho) +
                                    ": moved-from integrator");
  }
  const VoxelGridParams& g = grid.grid();
  const bool is_signed = params.mode == MeshSdfMode::Signed;
  if (!is_signed && params.mode != MeshSdfMode::Shell) {
    return Status::invalid_argument(std::string(kWho) + ": unknown mode");
  }
  const float shell_m = params.shell_voxels * g.voxel_size;
  if (!is_signed &&
      !(params.shell_voxels >= kMinShellVoxels && shell_m < g.trunc_dist)) {
    return Status::invalid_argument(
        std::string(kWho) +
        ": shell_voxels must be at least sqrt(3)/2, or the shell can fall "
        "between voxels, and thinner than trunc_dist, or nothing observed "
        "reads as outside");
  }

  VR_ASSIGN(AttributeView tsdf_view, grid.attribute("tsdf"));
  VR_ASSIGN(AttributeView weight_view, grid.attribute("weight"));
  if (tsdf_view.element_size != sizeof(float) ||
      weight_view.element_size != sizeof(float)) {
    return Status::invalid_argument(std::string(kWho) +
                                    ": tsdf/weight attributes must be float");
  }

  MeshIntegrateStats stats;
  if (triangle_count == 0) {
    return stats;
  }

  // Every input is per-call and bound whole, so each is checked against what
  // one binding may cover -- first, since each size is known from the counts
  // alone, and a mesh too large to bind should not pay the host passes below
  // to find out. The hash entries are the one buffer another tier sized, and
  // are bound with their real range.
  const auto num_blocks = static_cast<std::uint32_t>(g.num_blocks);
  const VkDeviceSize vertex_bytes = VkDeviceSize(vertex_count) * sizeof(Vec3f);
  const VkDeviceSize index_bytes =
      VkDeviceSize(triangle_count) * 3 * sizeof(std::uint32_t);
  const VkDeviceSize offset_bytes =
      (VkDeviceSize(triangle_count) + 1) * sizeof(std::uint32_t);
  const VkDeviceSize count_bytes =
      VkDeviceSize(num_blocks) * sizeof(std::uint32_t);
  const VkDeviceSize coord_bytes = VkDeviceSize(num_blocks) * sizeof(Vec3i);
  const VkDeviceSize entries_bytes = grid.map().entries_buffer_size();
  const struct {
    const char* what;
    VkDeviceSize bytes;
  } ranges[] = {
      {"the vertex buffer", vertex_bytes},
      {"the index buffer", index_bytes},
      {"the candidate offsets", offset_bytes},
      {"the bin counts", count_bytes},
      {"the bin coordinates", coord_bytes},
      {"the hash entries", entries_bytes},
  };
  for (const auto& r : ranges) {
    VR_TRY(
        check_storage_buffer_range((std::string(kWho) + ": " + r.what).c_str(),
                                   r.bytes, max_storage_buffer_range_));
  }

  // The candidate decomposition allocate_from_triangles dispatched over. Also
  // where every index is bounds-checked and a degenerate triangle dropped.
  VR_ASSIGN(std::vector<std::uint32_t> offsets,
            volume::triangle_candidate_offsets(g, vertices, vertex_count,
                                               indices, triangle_count, kWho));
  const std::uint32_t work_items = offsets[triangle_count];
  if (work_items == 0) {
    return stats;  // every triangle degenerate or non-finite
  }
  for (std::uint32_t t = 0; t < triangle_count; ++t) {
    if (offsets[t + 1] > offsets[t]) ++stats.triangles;
  }
  const VkDeviceSize item_bytes =
      VkDeviceSize(work_items) * sizeof(std::uint32_t);
  VR_TRY(check_storage_buffer_range(
      (std::string(kWho) + ": the work-item slots").c_str(), item_bytes,
      max_storage_buffer_range_));

  // TODO(tsdf): the inputs are host-visible, as every buffer the grid itself
  // binds is (its attributes carry the same TODO(volume)); staging them
  // device-local waits on a copy path in core. The buffers only the device
  // touches are device-local already.
  VR_ASSIGN(Buffer vertex_buf,
            upload_storage_buffer(*allocator_, vertices, vertex_bytes));
  VR_ASSIGN(Buffer index_buf,
            upload_storage_buffer(*allocator_, indices, index_bytes));
  VR_ASSIGN(Buffer offset_buf,
            upload_storage_buffer(*allocator_, offsets.data(), offset_bytes));
  VR_ASSIGN(Buffer count_buf, storage_buffer(*allocator_, count_bytes));
  VR_ASSIGN(Buffer coord_buf, storage_buffer(*allocator_, coord_bytes));
  VR_ASSIGN(Buffer item_buf, device_storage_buffer(*allocator_, item_bytes));
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(vertex_buf.handle()),
                           "tsdf.mesh_vertices");
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(count_buf.handle()),
                           "tsdf.mesh_bin_counts");
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(item_buf.handle()),
                           "tsdf.mesh_item_slots");
  auto* counts = static_cast<std::uint32_t*>(count_buf.mapped());
  const auto* coords = static_cast<const Vec3i*>(coord_buf.mapped());
  std::memset(counts, 0, static_cast<std::size_t>(count_bytes));
  std::memset(missing_.mapped(), 0, sizeof(std::uint32_t));

  bin_.set.write_storage_buffer(0, grid.map().entries_buffer(), 0,
                                entries_bytes);
  bin_.set.write_storage_buffer(1, vertex_buf.handle(), 0, VK_WHOLE_SIZE);
  bin_.set.write_storage_buffer(2, index_buf.handle(), 0, VK_WHOLE_SIZE);
  bin_.set.write_storage_buffer(3, offset_buf.handle(), 0, VK_WHOLE_SIZE);
  bin_.set.write_storage_buffer(4, count_buf.handle(), 0, VK_WHOLE_SIZE);
  bin_.set.write_storage_buffer(5, item_buf.handle(), 0, VK_WHOLE_SIZE);
  bin_.set.write_storage_buffer(6, coord_buf.handle(), 0, VK_WHOLE_SIZE);
  bin_.set.write_storage_buffer(8, dummy_.handle(), 0, VK_WHOLE_SIZE);

  // Count. The one pass whose result the host must read before it writes
  // anything: a band block the table does not hold would leave that part of
  // the surface unwritten, so it is refused here rather than holed later.
  const BinPush count_push{g, triangle_count, kPassCount};
  VR_TRY(dispatch(*device_, bin_, &count_push, sizeof(count_push),
                  group_count(work_items), max_workgroup_count_x_, &stage));
  std::uint32_t missing = 0;
  std::memcpy(&missing, missing_.mapped(), sizeof(missing));
  if (missing != 0) {
    return Status::invalid_argument(
        std::string(kWho) +
        ": the band reaches blocks that are not allocated (" +
        std::to_string(missing) +
        " triangle-block pair(s) found none); run "
        "VoxelHashMap::allocate_from_triangles with this mesh first, and "
        "check it reported no failures");
  }

  // Each slot's bin as a range of one concatenated array, in one pass: the
  // counts are rewritten in place as each bin's first entry, which the fill
  // pass then advances as its cursor, and every binned slot becomes a block to
  // write, at the coordinate the count pass found it at.
  const auto vpb = static_cast<std::uint32_t>(g.voxels_per_block);
  std::vector<MeshBin> blocks;
  std::uint64_t bin_entries = 0;
  std::uint32_t largest_bin = 0;
  for (std::uint32_t s = 0; s < num_blocks; ++s) {
    const std::uint32_t count = counts[s];
    counts[s] = static_cast<std::uint32_t>(bin_entries);
    if (count == 0) continue;
    blocks.push_back(MeshBin{coords[s], static_cast<std::int32_t>(s * vpb),
                             static_cast<std::uint32_t>(bin_entries), count});
    largest_bin = std::max(largest_bin, count);
    bin_entries += count;
    if (bin_entries > std::numeric_limits<std::uint32_t>::max()) {
      return Status::invalid_argument(std::string(kWho) +
                                      ": bin entries exceed 2^32");
    }
  }
  if (blocks.empty()) {
    return stats;
  }
  if (largest_bin > kMaxBinTriangles) {
    return Status::invalid_argument(
        std::string(kWho) + ": a block's bin holds " +
        std::to_string(largest_bin) + " triangles, past kMaxBinTriangles (" +
        std::to_string(kMaxBinTriangles) +
        "); the mesh is far finer than the grid's voxels -- decimate it "
        "toward the voxel size");
  }
  const VkDeviceSize bins_bytes =
      VkDeviceSize(bin_entries) * sizeof(std::uint32_t);
  const VkDeviceSize block_bytes =
      VkDeviceSize(blocks.size()) * sizeof(MeshBin);
  VR_TRY(check_storage_buffer_range((std::string(kWho) + ": the bins").c_str(),
                                    bins_bytes, max_storage_buffer_range_));
  VR_TRY(check_storage_buffer_range(
      (std::string(kWho) + ": the block list").c_str(), block_bytes,
      max_storage_buffer_range_));
  // The integrate dispatches take consecutive blocks while the next would keep
  // the dispatch within kMaxDispatchBinEntries, and within what one 1-D
  // dispatch can launch. Checked here, above the first write: a block too
  // large for one dispatch alone could not be split.
  const std::uint64_t max_threads = std::min<std::uint64_t>(
      std::uint64_t{max_workgroup_count_x_} * kLocalSize,
      std::numeric_limits<std::uint32_t>::max());
  const std::uint64_t max_dispatch_blocks = max_threads / vpb;
  if (max_dispatch_blocks == 0) {
    return Status::invalid_argument(
        std::string(kWho) +
        ": voxels_per_block exceeds what one dispatch can launch");
  }

  VR_ASSIGN(Buffer bins_buf, device_storage_buffer(*allocator_, bins_bytes));
  VR_ASSIGN(Buffer block_buf,
            upload_storage_buffer(*allocator_, blocks.data(), block_bytes));
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(bins_buf.handle()),
                           "tsdf.mesh_bins");

  // Fill.
  bin_.set.write_storage_buffer(8, bins_buf.handle(), 0, VK_WHOLE_SIZE);
  const BinPush fill_push{g, triangle_count, kPassFill};
  VR_TRY(dispatch(*device_, bin_, &fill_push, sizeof(fill_push),
                  group_count(work_items), max_workgroup_count_x_, &stage));

  integrate_.set.write_storage_buffer(0, tsdf_view.buffer->handle(), 0,
                                      VK_WHOLE_SIZE);
  integrate_.set.write_storage_buffer(1, weight_view.buffer->handle(), 0,
                                      VK_WHOLE_SIZE);
  integrate_.set.write_storage_buffer(2, vertex_buf.handle(), 0, VK_WHOLE_SIZE);
  integrate_.set.write_storage_buffer(3, index_buf.handle(), 0, VK_WHOLE_SIZE);
  integrate_.set.write_storage_buffer(4, block_buf.handle(), 0, VK_WHOLE_SIZE);
  integrate_.set.write_storage_buffer(5, bins_buf.handle(), 0, VK_WHOLE_SIZE);

  for (std::size_t first = 0; first < blocks.size();) {
    std::size_t end = first + 1;
    std::uint64_t entries = blocks[first].count;
    while (end < blocks.size() && end - first < max_dispatch_blocks &&
           entries + blocks[end].count <= kMaxDispatchBinEntries) {
      entries += blocks[end].count;
      ++end;
    }
    const auto n = static_cast<std::uint32_t>(end - first);
    const IntegratePush push{g, static_cast<std::uint32_t>(first), n,
                             static_cast<std::uint32_t>(params.mode),
                             is_signed ? 0.0f : shell_m};
    VR_TRY(dispatch(*device_, integrate_, &push, sizeof(push),
                    group_count(n * vpb), max_workgroup_count_x_, &stage));
    ++stats.dispatches;
    first = end;
  }

  stats.blocks = static_cast<std::uint32_t>(blocks.size());
  stats.bin_entries = static_cast<std::uint32_t>(bin_entries);
  return stats;
}

}  // namespace volumetric_kit::recon::tsdf
