// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/tsdf/tsdf_integrator.hpp"

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>
#include <vector>

#include "volumetric_kit/recon/core/compute_kernel.hpp"
#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "tsdf_integrate_comp.spv.hpp"

namespace volumetric_kit::recon::tsdf {
namespace {

using volume::AttributeView;
using volume::BlockIndex;
using volume::DepthCameraParams;
using volume::VoxelBlockGrid;
using volume::VoxelGridParams;

// Local group size, matching `layout(local_size_x = 256)` in the kernel.
constexpr std::uint32_t kLocalSize = 256;

// The push-constant block (mirrors `PushConstants` in tsdf_common.glsl): the
// grid, the active-block count, the fusion weight cap, the integration mode,
// and two color flags. `has_color` fuses the supplied color frame;
// `has_color_attr` says binding 6 is the grid's real color attribute (so
// dynamic can clear a stale color even on a depth-only frame) -- the two differ
// because a grid can carry `color` without a color image arriving this call.
// The camera rides the SSBO as volume::DepthCameraParams verbatim -- the kernel
// derives world -> camera from its rigid cam_to_world, so there is no separate
// pre-inverted per-dispatch struct.
struct PushConstants {
  VoxelGridParams grid;
  std::uint32_t num_active_blocks;
  float max_weight;
  std::uint32_t mode;       // tsdf::IntegrationMode (0 = classic, 1 = dynamic).
  std::uint32_t has_color;  // 0 = depth only; 1 = fuse the color frame.
  std::uint32_t has_color_attr;  // 1 = binding 6 is the grid's color attribute.
};

// Pin the scalar-block-layout ABI: this struct must stay byte-identical to the
// `PushConstants` block in tsdf_common.glsl. VoxelGridParams is 32 all-scalar
// bytes, so every field lands at its host offset (no std430 vec padding). A
// drift is a compile error, not silent buffer corruption -- the discipline the
// volume/mesh shader-facing PODs already follow.
static_assert(sizeof(PushConstants) == 52, "PushConstants must be 52 bytes");
static_assert(offsetof(PushConstants, grid) == 0, "PushConstants layout drift");
static_assert(offsetof(PushConstants, num_active_blocks) == 32,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, max_weight) == 36,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, mode) == 40,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, has_color) == 44,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, has_color_attr) == 48,
              "PushConstants layout drift");

// Ceil-divide without the `items + kLocalSize - 1` term, which overflows uint32
// for items near UINT32_MAX (yielding ~0 groups -> a silent no-op dispatch).
std::uint32_t group_count(std::uint32_t items) {
  return items / kLocalSize + (items % kLocalSize != 0u ? 1u : 0u);
}

// A host-visible, host-mapped storage buffer of the given byte size.
Result<Buffer> storage_buffer(Allocator& allocator, VkDeviceSize bytes,
                              HostAccess access = HostAccess::Random) {
  BufferDesc desc;
  desc.size = bytes;
  desc.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
  desc.memory = MemoryUsage::HostVisible;
  desc.mapped = true;
  desc.host_access = access;
  return allocator.create_buffer(desc);
}

// A host-visible storage buffer of `bytes`, filled from `src` -- the alloc +
// map + memcpy every per-call upload (active blocks, depth, color) repeats.
// Ties the allocation size and the copy length to one argument.
Result<Buffer> upload_storage_buffer(Allocator& allocator, const void* src,
                                     VkDeviceSize bytes) {
  VR_ASSIGN(Buffer buf,
            storage_buffer(allocator, bytes, HostAccess::SequentialWrite));
  std::memcpy(buf.mapped(), src, static_cast<std::size_t>(bytes));
  return buf;
}

}  // namespace

Result<TsdfIntegrator> TsdfIntegrator::create(Device& device,
                                              Allocator& allocator) {
  const VkDevice dev = device.handle();

  TsdfIntegrator integ;
  integ.device_ = &device;
  integ.allocator_ = &allocator;

  // The integrate kernel: 8 storage-buffer bindings (tsdf, weight, active,
  // depth, depth-camera, color image, color attribute, color camera) + the
  // PushConstants range. KernelSetBuilder builds its layout + pipeline and
  // allocates its set from a shared pool (sized to the exact descriptor total).
  VkPushConstantRange push_range{};
  push_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push_range.offset = 0;
  push_range.size = sizeof(PushConstants);
  KernelSetBuilder kb(dev);
  VR_TRY(kb.add(integ.kernel_, vr_tsdf_integrate_comp_spv,
                vr_tsdf_integrate_comp_spv_size, 8, &push_range));
  VR_ASSIGN(integ.pool_, kb.build());

  // A 1-D dispatch's groupCountX is capped by maxComputeWorkGroupCount[0] (only
  // >= 65535 is guaranteed); cache it so integrate() can reject an over-large
  // active set as a clean error rather than risk a device-lost on a min-spec
  // GPU -- the guard the volume tier's dispatch() applies.
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  integ.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];

  // The camera params are fixed-size, so persist the SSBO (bound once at
  // binding 4) and rewrite its contents each integrate() -- not a per-call
  // allocation. Only the variable-size active/depth buffers are per-call.
  VR_ASSIGN(integ.cam_buf_, storage_buffer(allocator, sizeof(DepthCameraParams),
                                           HostAccess::SequentialWrite));
  integ.kernel_.set.write_storage_buffer(4, integ.cam_buf_.handle(), 0,
                                         VK_WHOLE_SIZE);

  // Color path: a persistent color-camera SSBO at binding 7, and a 1-element
  // dummy at the color-image (5) and color-attribute (6) slots so every
  // descriptor stays bound when no color is fused; integrate() rebinds 5/6 and
  // rewrites the color camera when a frame arrives.
  VR_ASSIGN(integ.color_cam_buf_,
            storage_buffer(allocator, sizeof(ColorCameraParams),
                           HostAccess::SequentialWrite));
  VR_ASSIGN(integ.color_dummy_,
            storage_buffer(allocator, sizeof(std::uint32_t)));
  integ.kernel_.set.write_storage_buffer(5, integ.color_dummy_.handle(), 0,
                                         VK_WHOLE_SIZE);
  integ.kernel_.set.write_storage_buffer(6, integ.color_dummy_.handle(), 0,
                                         VK_WHOLE_SIZE);
  integ.kernel_.set.write_storage_buffer(7, integ.color_cam_buf_.handle(), 0,
                                         VK_WHOLE_SIZE);

  return integ;
}

Status TsdfIntegrator::integrate(VoxelBlockGrid& grid, const float* depth,
                                 const DepthCameraParams& cam, float max_weight,
                                 IntegrationMode mode,
                                 const ColorFrame* color) {
  if (!valid()) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: moved-from integrator");
  }
  if (depth == nullptr) {
    return Status::invalid_argument("TsdfIntegrator::integrate: depth is null");
  }
  if (cam.width == 0 || cam.height == 0) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: depth image is empty");
  }

  // The float tsdf + weight attributes to fuse into.
  VR_ASSIGN(AttributeView tsdf_view, grid.attribute("tsdf"));
  VR_ASSIGN(AttributeView weight_view, grid.attribute("weight"));
  if (tsdf_view.element_size != sizeof(float) ||
      weight_view.element_size != sizeof(float)) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: tsdf/weight attributes must be float");
  }

  // Resolve the color path up front, before any per-call allocation or binding
  // (so an invalid request leaves the persistent set untouched). A supplied
  // color frame must be non-empty and the grid must carry a `uint32` `color`
  // attribute. Independently, note whether the grid carries `color` at all:
  // dynamic mode must clear a stale color even on a depth-only frame, so
  // binding 6 tracks the grid's real attribute (`has_color_attr`) whenever
  // there is one
  // -- matching the prior engine, which clears color whenever the grid holds a
  // color block, not only when a color image arrives.
  const Buffer* color_attr_buf = nullptr;
  if (color != nullptr) {
    if (color->pixels == nullptr || color->cam.width == 0 ||
        color->cam.height == 0) {
      return Status::invalid_argument(
          "TsdfIntegrator::integrate: color frame is empty");
    }
    VR_ASSIGN(AttributeView color_view, grid.attribute("color"));
    if (color_view.element_size != sizeof(std::uint32_t)) {
      return Status::invalid_argument(
          "TsdfIntegrator::integrate: color attribute must be uint32 (packed "
          "RGB)");
    }
    color_attr_buf = color_view.buffer;
  } else if (grid.has_attribute("color")) {
    VR_ASSIGN(AttributeView color_view, grid.attribute("color"));
    if (color_view.element_size == sizeof(std::uint32_t)) {
      color_attr_buf = color_view.buffer;
    }
  }

  // Snapshot the active blocks; nothing to fuse into an empty grid.
  VR_ASSIGN(std::vector<BlockIndex> active, grid.map().compact_active_blocks());
  if (active.empty()) {
    return {};
  }

  // Upload the block list, the depth frame (metres), and the camera params.
  VR_ASSIGN(
      Buffer active_buf,
      upload_storage_buffer(*allocator_, active.data(),
                            VkDeviceSize(active.size()) * sizeof(BlockIndex)));

  const auto pixels = static_cast<std::size_t>(cam.width) *
                      static_cast<std::size_t>(cam.height);
  VR_ASSIGN(Buffer depth_buf,
            upload_storage_buffer(*allocator_, depth,
                                  VkDeviceSize(pixels) * sizeof(float)));

  // The camera params ride the SSBO verbatim; the kernel derives world ->
  // camera from the rigid cam_to_world, so there is no host-side pose
  // inversion.
  std::memcpy(cam_buf_.mapped(), &cam, sizeof(DepthCameraParams));

  // The camera binding (4) was written once at create(); only the per-call
  // tsdf/weight/active/depth buffers are (re)bound here.
  kernel_.set.write_storage_buffer(0, tsdf_view.buffer->handle(), 0,
                                   VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(1, weight_view.buffer->handle(), 0,
                                   VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(2, active_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(3, depth_buf.handle(), 0, VK_WHOLE_SIZE);

  // Color bindings. Slot 6 is the grid's `color` attribute whenever it carries
  // one (resolved above), so dynamic can clear a stale color even on a
  // depth-only frame; slot 5 is the color image only when a frame is supplied
  // this call. Unused color slots fall back to the 1-element dummy so every
  // descriptor stays bound. color_buf lives at function scope so it outlives
  // the dispatch.
  const std::uint32_t has_color_attr = (color_attr_buf != nullptr) ? 1u : 0u;
  kernel_.set.write_storage_buffer(6,
                                   (color_attr_buf != nullptr)
                                       ? color_attr_buf->handle()
                                       : color_dummy_.handle(),
                                   0, VK_WHOLE_SIZE);

  Buffer color_buf;
  std::uint32_t has_color = 0;
  if (color != nullptr) {
    const auto cpixels = static_cast<std::size_t>(color->cam.width) *
                         static_cast<std::size_t>(color->cam.height);
    VR_ASSIGN(color_buf, upload_storage_buffer(
                             *allocator_, color->pixels,
                             VkDeviceSize(cpixels) * sizeof(std::uint32_t)));
    std::memcpy(color_cam_buf_.mapped(), &color->cam,
                sizeof(ColorCameraParams));
    kernel_.set.write_storage_buffer(5, color_buf.handle(), 0, VK_WHOLE_SIZE);
    has_color = 1;
  } else {
    // No color image this call; restore the dummy at slot 5 (a prior call may
    // have bound a real image there). Slot 6 already reflects the grid above.
    kernel_.set.write_storage_buffer(5, color_dummy_.handle(), 0,
                                     VK_WHOLE_SIZE);
  }

  const VoxelGridParams& grid_params = grid.grid();
  const PushConstants push{
      grid_params, static_cast<std::uint32_t>(active.size()),
      max_weight,  static_cast<std::uint32_t>(mode),
      has_color,   has_color_attr};

  // One thread per voxel of every active block. The flattened thread count must
  // fit a uint32; dispatch() caps groupCountX at the device limit and emits the
  // barrier that makes the fused tsdf/weight writes visible to a host read-back
  // and to the next frame's dispatch (the running average).
  const std::uint64_t threads64 =
      static_cast<std::uint64_t>(active.size()) *
      static_cast<std::uint64_t>(grid_params.voxels_per_block);
  if (threads64 > std::numeric_limits<std::uint32_t>::max()) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: active_blocks * voxels_per_block exceeds "
        "2^32");
  }
  return dispatch(*device_, kernel_, &push, sizeof(push),
                  group_count(static_cast<std::uint32_t>(threads64)),
                  max_workgroup_count_x_);
}

}  // namespace volumetric_kit::recon::tsdf
