// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/tsdf/tsdf_integrator.hpp"

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>
#include <type_traits>
#include <vector>

#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/math/vector_types.hpp"  // Mat4f, glm::inverse
#include "volumetric_kit/recon/core/shader.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "tsdf_integrate_comp.spv.hpp"

namespace volumetric_kit::recon::tsdf {
namespace {

using volume::AttributeView;
using volume::BlockIndex;
using volume::DepthCameraParams;
using volume::VoxelBlockGrid;
using volume::VoxelGridParams;

// Local group size, matching `layout(local_size_x = 256)` in the kernel.
constexpr std::uint32_t kLocalSize = 256;

// The push-constant block (mirrors `PushConstants` in tsdf_common.glsl).
struct PushConstants {
  VoxelGridParams grid;
  std::uint32_t num_active_blocks;
};

// Per-dispatch camera + fusion params, uploaded as a single-element SSBO
// (mirrors `IntegrateParams` in tsdf_common.glsl): scalars at their 4-byte
// offsets, the mat4 at offset 36. static_asserts pin the layout the shader
// mirrors through scalar block layout.
struct IntegrateParams {
  float fx;
  float fy;
  float cx;
  float cy;
  float min_depth;
  float max_depth;
  float max_weight;
  std::uint32_t width;
  std::uint32_t height;
  Mat4f world_to_cam;
};
static_assert(sizeof(IntegrateParams) == 100,
              "IntegrateParams must be 100 bytes");
static_assert(offsetof(IntegrateParams, min_depth) == 16, "layout drift");
static_assert(offsetof(IntegrateParams, max_depth) == 20, "layout drift");
static_assert(offsetof(IntegrateParams, width) == 28, "layout drift");
static_assert(offsetof(IntegrateParams, world_to_cam) == 36, "layout drift");
static_assert(std::is_trivially_copyable_v<IntegrateParams>,
              "IntegrateParams must be trivially copyable");

// Ceil-divide without the `items + kLocalSize - 1` term, which overflows uint32
// for items near UINT32_MAX (yielding ~0 groups -> a silent no-op dispatch).
std::uint32_t group_count(std::uint32_t items) {
  return items / kLocalSize + (items % kLocalSize != 0u ? 1u : 0u);
}

// `count` storage-buffer bindings at 0..count-1, all compute-stage.
std::vector<VkDescriptorSetLayoutBinding> storage_bindings(
    std::uint32_t count) {
  std::vector<VkDescriptorSetLayoutBinding> bindings(count);
  for (std::uint32_t i = 0; i < count; ++i) {
    bindings[i].binding = i;
    bindings[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    bindings[i].descriptorCount = 1;
    bindings[i].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  }
  return bindings;
}

// A host-visible, host-mapped storage buffer of the given byte size.
Result<Buffer> storage_buffer(Allocator& allocator, VkDeviceSize bytes,
                              HostAccess access = HostAccess::Random) {
  BufferDesc desc;
  desc.size = bytes;
  desc.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
  desc.memory = MemoryUsage::HostVisible;
  desc.mapped = true;
  desc.host_access = access;
  return allocator.create_buffer(desc);
}

}  // namespace

Result<TsdfIntegrator> TsdfIntegrator::create(Device& device,
                                              Allocator& allocator) {
  const VkDevice dev = device.handle();

  TsdfIntegrator integ;
  integ.device_ = &device;
  integ.allocator_ = &allocator;

  const auto bindings = storage_bindings(5);
  VR_ASSIGN(integ.layout_,
            DescriptorSetLayout::create(dev, bindings.data(), 5));

  VR_ASSIGN(ShaderModule module,
            ShaderModule::create(dev,
                                 reinterpret_cast<const std::uint32_t*>(
                                     vr_tsdf_integrate_comp_spv),
                                 vr_tsdf_integrate_comp_spv_size));
  VkPushConstantRange push_range{};
  push_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push_range.offset = 0;
  push_range.size = sizeof(PushConstants);
  const VkDescriptorSetLayout set_layout = integ.layout_.handle();
  ComputePipelineDesc desc;
  desc.shader = &module;
  desc.set_layouts = &set_layout;
  desc.set_layout_count = 1;
  desc.push_ranges = &push_range;
  desc.push_range_count = 1;
  VR_ASSIGN(integ.pipeline_, ComputePipeline::create(dev, desc));

  VkDescriptorPoolSize pool_size{};
  pool_size.type = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
  pool_size.descriptorCount = 5;
  VR_ASSIGN(integ.pool_, DescriptorPool::create(dev, &pool_size, 1, 1));
  VR_ASSIGN(integ.set_, integ.pool_.allocate(integ.layout_.handle()));

  // A 1-D dispatch's groupCountX is capped by maxComputeWorkGroupCount[0] (only
  // >= 65535 is guaranteed); cache it so integrate() can reject an over-large
  // active set as a clean error rather than risk a device-lost on a min-spec
  // GPU -- the guard the volume tier's dispatch() applies.
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  integ.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];

  // The per-dispatch params are fixed-size, so persist the SSBO (bound once at
  // binding 4) and rewrite its contents each integrate() -- not a per-call
  // allocation. Only the variable-size active/depth buffers are per-call.
  VR_ASSIGN(integ.params_buf_,
            storage_buffer(allocator, sizeof(IntegrateParams),
                           HostAccess::SequentialWrite));
  integ.set_.write_storage_buffer(4, integ.params_buf_.handle(), 0,
                                  VK_WHOLE_SIZE);

  return integ;
}

Status TsdfIntegrator::integrate(VoxelBlockGrid& grid, const float* depth,
                                 const DepthCameraParams& cam,
                                 float max_weight) {
  if (!valid()) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: moved-from integrator");
  }
  if (depth == nullptr) {
    return Status::invalid_argument("TsdfIntegrator::integrate: depth is null");
  }
  if (cam.width == 0 || cam.height == 0) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: depth image is empty");
  }

  // The float tsdf + weight attributes to fuse into.
  VR_ASSIGN(AttributeView tsdf_view, grid.attribute("tsdf"));
  VR_ASSIGN(AttributeView weight_view, grid.attribute("weight"));
  if (tsdf_view.element_size != sizeof(float) ||
      weight_view.element_size != sizeof(float)) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: tsdf/weight attributes must be float");
  }

  // Snapshot the active blocks; nothing to fuse into an empty grid.
  VR_ASSIGN(std::vector<BlockIndex> active, grid.map().compact_active_blocks());
  if (active.empty()) {
    return {};
  }

  // Upload the block list, the depth frame (metres), and the camera params.
  VR_ASSIGN(Buffer active_buf,
            storage_buffer(*allocator_,
                           VkDeviceSize(active.size()) * sizeof(BlockIndex),
                           HostAccess::SequentialWrite));
  std::memcpy(active_buf.mapped(), active.data(),
              active.size() * sizeof(BlockIndex));

  const auto pixels = static_cast<std::size_t>(cam.width) *
                      static_cast<std::size_t>(cam.height);
  VR_ASSIGN(Buffer depth_buf,
            storage_buffer(*allocator_, VkDeviceSize(pixels) * sizeof(float),
                           HostAccess::SequentialWrite));
  std::memcpy(depth_buf.mapped(), depth, pixels * sizeof(float));

  IntegrateParams params{};
  params.fx = cam.fx;
  params.fy = cam.fy;
  params.cx = cam.cx;
  params.cy = cam.cy;
  params.min_depth = cam.min_depth;
  params.max_depth = cam.max_depth;
  params.max_weight = max_weight;
  params.width = cam.width;
  params.height = cam.height;
  params.world_to_cam = glm::inverse(cam.cam_to_world);
  std::memcpy(params_buf_.mapped(), &params, sizeof(IntegrateParams));

  // Params binding (4) was written once at create(); only the per-call
  // tsdf/weight/active/depth buffers are (re)bound here.
  set_.write_storage_buffer(0, tsdf_view.buffer->handle(), 0, VK_WHOLE_SIZE);
  set_.write_storage_buffer(1, weight_view.buffer->handle(), 0, VK_WHOLE_SIZE);
  set_.write_storage_buffer(2, active_buf.handle(), 0, VK_WHOLE_SIZE);
  set_.write_storage_buffer(3, depth_buf.handle(), 0, VK_WHOLE_SIZE);

  const VoxelGridParams& grid_params = grid.grid();
  const PushConstants push{grid_params,
                           static_cast<std::uint32_t>(active.size())};

  // One thread per voxel of every active block. Guard the launch size as the
  // volume tier does: the flattened thread count must fit a uint32, and the
  // resulting groupCountX must fit the device's maxComputeWorkGroupCount[0].
  const std::uint64_t threads64 =
      static_cast<std::uint64_t>(active.size()) *
      static_cast<std::uint64_t>(grid_params.voxels_per_block);
  if (threads64 > std::numeric_limits<std::uint32_t>::max()) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: active_blocks * voxels_per_block exceeds "
        "2^32");
  }
  const std::uint32_t threads = static_cast<std::uint32_t>(threads64);
  const std::uint32_t groups = group_count(threads);
  if (groups > max_workgroup_count_x_) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: workgroup count exceeds the device's "
        "maxComputeWorkGroupCount[0] -- active set too large for a 1-D "
        "dispatch");
  }

  // A barrier makes the fused tsdf/weight writes visible to a host read-back
  // and to the next frame's dispatch (the running average).
  return device_->submit_single_time([&](VkCommandBuffer cmd) {
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_.handle());
    VkDescriptorSet set = set_.handle();
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                            pipeline_.layout(), 0, 1, &set, 0, nullptr);
    vkCmdPushConstants(cmd, pipeline_.layout(), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       sizeof(PushConstants), &push);
    vkCmdDispatch(cmd, groups, 1, 1);
    VkMemoryBarrier barrier{};
    barrier.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
    barrier.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT |
                            VK_ACCESS_SHADER_WRITE_BIT |
                            VK_ACCESS_HOST_READ_BIT;
    vkCmdPipelineBarrier(
        cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_HOST_BIT, 0, 1,
        &barrier, 0, nullptr, 0, nullptr);
  });
}

}  // namespace volumetric_kit::recon::tsdf
