// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/tsdf/tsdf_integrator.hpp"

#include <cstddef>
#include <cstdint>
#include <limits>
#include <vector>

#include "volumetric_kit/recon/core/command_batch.hpp"
#include "volumetric_kit/recon/core/compute_kernel.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/gpu_timer.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "tsdf_integrate_comp.spv.hpp"

namespace volumetric_kit::recon::tsdf {
namespace {

using volume::AttributeView;
using volume::BlockIndex;
using volume::VoxelBlockGrid;
using volume::VoxelGridParams;

// Local group size, matching `layout(local_size_x = 256)` in the kernel.
constexpr std::uint32_t kLocalSize = 256;

// The push-constant block (mirrors `PushConstants` in tsdf_common.glsl): the
// grid, the active-block count, the fusion weight cap, the integration mode,
// and two color flags. `has_color` fuses the supplied color frame;
// `has_color_attr` says binding 6 is the grid's real color attribute (so
// dynamic can clear a stale color even on a depth-only frame) -- the two differ
// because a grid can carry `color` without a color image arriving this call.
// The camera rides the SSBO as DepthCameraParams verbatim -- the kernel
// derives world -> camera from its rigid cam_to_world, so there is no separate
// pre-inverted per-dispatch struct.
struct PushConstants {
  VoxelGridParams grid;
  std::uint32_t num_active_blocks;
  float max_weight;
  std::uint32_t mode;       // tsdf::IntegrationMode (0 = classic, 1 = dynamic).
  std::uint32_t has_color;  // 0 = depth only; 1 = fuse the color frame.
  std::uint32_t has_color_attr;  // 1 = binding 6 is the grid's color attribute.
  std::uint32_t tick;  // the map's tick, which a changed block is stamped with
  // 1 = a colour word with a zero high byte is no colour
  // (ColorFrame::coverage_in_alpha).
  std::uint32_t coverage_in_alpha;
};

// Pin the scalar-block-layout ABI: this struct must stay byte-identical to the
// `PushConstants` block in tsdf_common.glsl. VoxelGridParams is 32 all-scalar
// bytes, so every field lands at its host offset (no std430 vec padding). A
// drift is a compile error, not silent buffer corruption -- the discipline the
// volume/mesh shader-facing PODs already follow.
static_assert(sizeof(PushConstants) == 60, "PushConstants must be 60 bytes");
static_assert(offsetof(PushConstants, grid) == 0, "PushConstants layout drift");
static_assert(offsetof(PushConstants, num_active_blocks) == 32,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, max_weight) == 36,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, mode) == 40,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, has_color) == 44,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, has_color_attr) == 48,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, tick) == 52,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, coverage_in_alpha) == 56,
              "PushConstants layout drift");

// Where a colour frame's image is: its host pixels or its device buffer (the
// caller has checked that exactly one is set).
StorageInput color_input(const ColorFrame& color) noexcept {
  return color.buffer != nullptr ? StorageInput(*color.buffer)
                                 : StorageInput(color.pixels);
}

// This tier's local_size, bound once so every call site reads group_count(n).
std::uint32_t group_count(std::uint32_t items) {
  return volumetric_kit::recon::group_count(items, kLocalSize);
}

}  // namespace

Result<TsdfIntegrator> TsdfIntegrator::create(Device& device,
                                              Allocator& allocator) {
  VR_TRY(check_device_requirements(device, "TsdfIntegrator::create"));
  TsdfIntegrator integ;
  integ.device_ = &device;
  integ.allocator_ = &allocator;

  // The integrate kernel: 9 storage-buffer bindings (0 tsdf, 1 weight,
  // 2 active, 3 depth, 4 depth-camera, 5 color image, 6 color attribute,
  // 7 color camera, 8 the map's block stamps) + the PushConstants range. This
  // count is the single source of truth for both the layout
  // (KernelSetBuilder::add creates bindings 0..N-1) and the auto-sized pool --
  // the deliberate cost of the "explicit, not reflected" decision -- so it and
  // the list above have to move together with the shader. KernelSetBuilder
  // builds its layout + pipeline and allocates its set from a shared pool
  // (sized to the exact descriptor total).
  VkPushConstantRange push_range{};
  push_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push_range.offset = 0;
  push_range.size = sizeof(PushConstants);
  KernelSetBuilder kb(device);
  VR_TRY(kb.add(integ.kernel_, "tsdf_integrate", vr_tsdf_integrate_comp_spv,
                vr_tsdf_integrate_comp_spv_size, 9, &push_range));
  VR_ASSIGN(integ.pool_, kb.build());

  // A 1-D dispatch's groupCountX is capped by maxComputeWorkGroupCount[0] (only
  // >= 65535 is guaranteed); cache it so integrate() can reject an over-large
  // active set as a clean error rather than risk a device-lost on a min-spec
  // GPU -- the guard the volume tier's dispatch() applies.
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  integ.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  // The device-span collector; see the member's declaration, and GpuTimer for
  // why a pool that will not allocate cannot fail this create().
  VR_ASSIGN(integ.gpu_timer_, GpuTimer::create(device));
  // Likewise for the per-call depth / colour frame uploads, which are bound
  // whole: a frame past this limit is invalid usage, not a slow path.
  integ.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;

  // The camera params are fixed-size, so persist the SSBOs and rewrite them
  // inline in each integrate()'s batch -- not a per-call allocation -- and a
  // 1-element dummy for the colour slots a call leaves unused.
  // All of these are device-local, as every buffer the kernel reads is (the
  // 2026-09-28 residency decision). integrate() writes every binding of every
  // set it dispatches.
  VR_ASSIGN(integ.cam_buf_,
            device_storage_buffer(allocator, sizeof(DepthCameraParams)));
  VR_ASSIGN(integ.color_cam_buf_,
            device_storage_buffer(allocator, sizeof(ColorCameraParams)));
  VR_ASSIGN(integ.color_dummy_,
            device_storage_buffer(allocator, sizeof(std::uint32_t)));

  // Name the persistent buffers for a GPU capture. A no-op where the device
  // resolved no debug-utils entry points.
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(integ.cam_buf_.handle()),
                         "tsdf.depth_cam");
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(integ.color_cam_buf_.handle()),
                         "tsdf.color_cam");
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(integ.color_dummy_.handle()),
                         "tsdf.dummy");

  return integ;
}

Status TsdfIntegrator::integrate(VoxelBlockGrid& grid, const float* depth,
                                 const DepthCameraParams& cam, float max_weight,
                                 IntegrationMode mode, const ColorFrame* color,
                                 StageMetrics* metrics) {
  return integrate(grid, {FrameInput{{StorageInput(depth), cam}, color}},
                   max_weight, mode, metrics);
}

Status TsdfIntegrator::integrate(VoxelBlockGrid& grid, const Buffer& depth,
                                 const DepthCameraParams& cam, float max_weight,
                                 IntegrationMode mode, const ColorFrame* color,
                                 StageMetrics* metrics) {
  return integrate(grid, {FrameInput{{StorageInput(depth), cam}, color}},
                   max_weight, mode, metrics);
}

Status TsdfIntegrator::integrate(VoxelBlockGrid& grid,
                                 const std::vector<FrameInput>& frames,
                                 float max_weight, IntegrationMode mode,
                                 StageMetrics* metrics) {
  // Opened before the validity check so a refused call still costs its row -- a
  // stage that reports nothing when it fails reads on an overlay as a stage
  // that did not run, which is the reading a frozen pipeline most needs not to
  // give. Inert when metrics is null, and it publishes both halves on every
  // return below rather than only the one that reaches the dispatch.
  GpuStageScope stage(metrics, gpu_timer_, "integrate");
  if (!valid()) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: moved-from integrator");
  }
  // Every frame's O(1) checks come first, ahead of the compaction dispatch and
  // every binding below, so a refused call does no work and leaves the
  // persistent set as it was -- an empty grid included. A frame with no pixels
  // dispatches nothing, as allocate_from_depth allocates nothing for it.
  std::vector<std::size_t> live;  // the frames that dispatch, in order
  std::vector<VkDeviceSize> depth_bytes(frames.size());
  std::vector<VkDeviceSize> color_bytes(frames.size(), 0);
  bool any_color = false;
  for (std::size_t i = 0; i < frames.size(); ++i) {
    const DepthCameraParams& cam = frames[i].camera;
    const auto pixels = static_cast<std::size_t>(cam.width) *
                        static_cast<std::size_t>(cam.height);
    depth_bytes[i] = VkDeviceSize(pixels) * sizeof(float);
    VR_TRY(frames[i].depth.check("TsdfIntegrator::integrate: depth",
                                 depth_bytes[i]));
    if (pixels == 0) continue;
    live.push_back(i);
    VR_TRY(check_storage_buffer_range(
        "TsdfIntegrator::integrate: the depth buffer", depth_bytes[i],
        max_storage_buffer_range_));
    const ColorFrame* color = frames[i].color;
    if (color == nullptr) continue;
    if ((color->pixels == nullptr && color->buffer == nullptr) ||
        color->cam.width == 0 || color->cam.height == 0) {
      return Status::invalid_argument(
          "TsdfIntegrator::integrate: color frame is empty");
    }
    if (color->pixels != nullptr && color->buffer != nullptr) {
      return Status::invalid_argument(
          "TsdfIntegrator::integrate: color frame sets both pixels and "
          "buffer");
    }
    color_bytes[i] = VkDeviceSize(color->cam.width) * color->cam.height *
                     sizeof(std::uint32_t);
    VR_TRY(
        color_input(*color).check("TsdfIntegrator::integrate: the colour "
                                  "image",
                                  color_bytes[i]));
    VR_TRY(check_storage_buffer_range(
        "TsdfIntegrator::integrate: the colour buffer", color_bytes[i],
        max_storage_buffer_range_));
    // The kernel decodes with exactly one curve, so a frame that is not already
    // in the canonical encoded form is refused rather than fused through the
    // wrong one -- "convert once at the sensor boundary" is a contract, and a
    // silently-misinterpreted curve is precisely the quiet error the
    // 2026-08-02 color-space decision exists to prevent. `sensor::to_canonical`
    // is the conversion; it is a copy when the declaration already matches.
    if (!is_canonical(color->encoding)) {
      return Status::invalid_argument(
          "TsdfIntegrator::integrate: color frame is not in the canonical "
          "encoded form (sRGB transfer, BT.709 primaries); convert it at the "
          "capture boundary with sensor::to_canonical");
    }
    any_color = true;
  }
  if (live.empty()) {
    return {};
  }

  // The float tsdf + weight attributes to fuse into.
  VR_ASSIGN(AttributeView tsdf_view, grid.attribute("tsdf"));
  VR_ASSIGN(AttributeView weight_view, grid.attribute("weight"));
  if (tsdf_view.element_size != sizeof(float) ||
      weight_view.element_size != sizeof(float)) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: tsdf/weight attributes must be float");
  }

  // The grid's colour attribute: required as uint32 when a frame brings
  // colour, and used whenever the grid carries one, since dynamic mode must
  // clear a stale color even on a depth-only frame -- matching the prior
  // engine, which clears color whenever the grid holds a color block, not only
  // when a color image arrives.
  const Buffer* color_attr_buf = nullptr;
  if (any_color) {
    VR_ASSIGN(AttributeView color_view, grid.attribute("color"));
    if (color_view.element_size != sizeof(std::uint32_t)) {
      return Status::invalid_argument(
          "TsdfIntegrator::integrate: color attribute must be uint32 (packed "
          "RGB)");
    }
    color_attr_buf = color_view.buffer;
  } else if (grid.has_attribute("color")) {
    VR_ASSIGN(AttributeView color_view, grid.attribute("color"));
    if (color_view.element_size == sizeof(std::uint32_t)) {
      color_attr_buf = color_view.buffer;
    }
  }

  // Compact the active blocks once for every frame, leaving the list on the
  // device; only its count comes back. This is a second GPU dispatch inside
  // this stage's host row, so it reports its own "  ..active set" breakdown --
  // otherwise its device time is invisible and the gap between integrate's two
  // halves reads as submit overhead when a good part of it is another kernel.
  // Nothing to fuse into an empty grid.
  // TODO(tsdf): dispatch indirect off the device count, saving the fence wait
  // between the two submits, if a host row shows that wait.
  VR_ASSIGN(const volume::DeviceBlockList active,
            grid.map().compact_active_blocks_on_device(metrics));
  if (active.count == 0) {
    return {};
  }

  // One thread per voxel of every active block. The flattened thread count must
  // fit a uint32; the batch refuses a groupCountX past the device limit.
  const VoxelGridParams& grid_params = grid.grid();
  const std::uint64_t threads64 =
      static_cast<std::uint64_t>(active.count) *
      static_cast<std::uint64_t>(grid_params.voxels_per_block);
  if (threads64 > std::numeric_limits<std::uint32_t>::max()) {
    return Status::invalid_argument(
        "TsdfIntegrator::integrate: active_blocks * voxels_per_block exceeds "
        "2^32");
  }

  // The call is one tick: every block it changes is stamped with the new one,
  // so a reader that recorded the tick before sees the change as newer.
  grid.map().advance_tick();
  const std::uint32_t tick = grid.map().tick();
  // A set and a device span a frame.
  const auto count = static_cast<std::uint32_t>(live.size());
  VR_TRY(frame_sets_.reserve(*device_, kernel_, count));
  VR_TRY(gpu_timer_.reserve(*device_, count));

  // One batch: per frame, its images staged, its cameras inline, then its
  // dispatch, on a set of its own. The two camera buffers are shared by every
  // frame and rewritten ahead of each dispatch, which the batch's barrier
  // around every dispatch orders after the one before read them. Every set is
  // written whole before its dispatch is recorded, as the batch requires.
  // TODO(tsdf): one dispatch looping over the cameras, reading and writing
  // each voxel once, if integrate's device time comes to matter after
  // PERF.md's P3 (DECISIONS.md, 2026-09-30).
  CommandBatch batch(*device_, *allocator_);
  std::vector<Buffer> depth_bufs(frames.size());  // host arrays' device copies
  std::vector<Buffer> color_bufs(frames.size());  // alive across the batch
  const std::uint32_t has_color_attr = (color_attr_buf != nullptr) ? 1u : 0u;
  for (std::size_t k = 0; k < live.size(); ++k) {
    const std::size_t i = live[k];
    const FrameInput& frame = frames[i];
    const DescriptorSet& set = frame_sets_[k];
    VR_ASSIGN(
        const VkBuffer depth_handle,
        frame.depth.buffer(batch, *allocator_, depth_bytes[i], depth_bufs[i]));
    if (depth_bufs[i].valid()) {
      // Named because it is the biggest thing this call moves -- a few
      // megabytes a frame at a scanner's resolution -- and so the first row a
      // capture's transfer view should be able to attribute.
      device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                               debug_object_handle(depth_bufs[i].handle()),
                               "tsdf.depth_frame");
    }
    // The camera params ride the SSBO verbatim; the kernel derives world ->
    // camera from the rigid cam_to_world, so there is no host-side pose
    // inversion.
    VR_TRY(batch.upload(cam_buf_, 0, &frame.camera, sizeof(DepthCameraParams)));

    set.write_storage_buffer(0, tsdf_view.buffer->handle(), 0, VK_WHOLE_SIZE);
    set.write_storage_buffer(1, weight_view.buffer->handle(), 0, VK_WHOLE_SIZE);
    set.write_storage_buffer(2, active.buffer->handle(), 0,
                             VkDeviceSize(active.count) * sizeof(BlockIndex));
    // The images' exact ranges, never VK_WHOLE_SIZE: a caller's buffer may be
    // past maxStorageBufferRange where the image it holds is not.
    set.write_storage_buffer(3, depth_handle, 0, depth_bytes[i]);
    set.write_storage_buffer(4, cam_buf_.handle(), 0, VK_WHOLE_SIZE);
    // Slot 6 is the grid's `color` attribute whenever it carries one, so
    // dynamic can clear a stale color even on a depth-only frame; slot 5 is the
    // frame's color image only when it brings one. Unused color slots take the
    // 1-element dummy so every descriptor stays bound.
    set.write_storage_buffer(6,
                             (color_attr_buf != nullptr)
                                 ? color_attr_buf->handle()
                                 : color_dummy_.handle(),
                             0, VK_WHOLE_SIZE);
    set.write_storage_buffer(7, color_cam_buf_.handle(), 0, VK_WHOLE_SIZE);
    set.write_storage_buffer(8, grid.map().stamps_buffer().handle(), 0,
                             VK_WHOLE_SIZE);
    std::uint32_t has_color = 0;
    if (frame.color != nullptr) {
      VR_ASSIGN(const VkBuffer color_handle,
                color_input(*frame.color)
                    .buffer(batch, *allocator_, color_bytes[i], color_bufs[i]));
      if (color_bufs[i].valid()) {
        device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                                 debug_object_handle(color_bufs[i].handle()),
                                 "tsdf.color_frame");
      }
      VR_TRY(batch.upload(color_cam_buf_, 0, &frame.color->cam,
                          sizeof(ColorCameraParams)));
      set.write_storage_buffer(5, color_handle, 0, color_bytes[i]);
      has_color = 1;
    } else {
      set.write_storage_buffer(5, color_dummy_.handle(), 0, VK_WHOLE_SIZE);
    }

    const PushConstants push{
        grid_params,
        active.count,
        max_weight,
        static_cast<std::uint32_t>(mode),
        has_color,
        has_color_attr,
        tick,
        (frame.color != nullptr && frame.color->coverage_in_alpha) ? 1u : 0u};
    VR_TRY(batch.dispatch(kernel_, set, &push, sizeof(push),
                          group_count(static_cast<std::uint32_t>(threads64)),
                          max_workgroup_count_x_, &stage));
  }
  return batch.submit();
}

}  // namespace volumetric_kit::recon::tsdf
