// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/volume/voxel_hash_map.hpp"

#include <algorithm>
#include <cstring>
#include <limits>
#include <string>
#include <utility>
#include <vector>

#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/shader.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"
#include "volumetric_kit/recon/volume/hash.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "hash_allocate_coords_comp.spv.hpp"
#include "hash_allocate_depth_comp.spv.hpp"
#include "hash_allocate_points_comp.spv.hpp"
#include "hash_compact_comp.spv.hpp"
#include "hash_compact_frustum_comp.spv.hpp"
#include "hash_delete_coords_comp.spv.hpp"
#include "hash_init_comp.spv.hpp"

namespace volumetric_kit::recon::volume {
namespace {

// Local group size, matching `layout(local_size_x = 256)` in every kernel.
constexpr std::uint32_t kLocalSize = 256;

// Bounded passes for the resize re-insert. allocate() is idempotent, so re-
// driving the whole snapshot absorbs transient bucket-lock contention; the cap
// keeps a genuine (near-impossible post-growth) overflow from looping forever.
constexpr int kReinsertPasses = 3;

// The push-constant block every kernel shares: the grid shape plus one
// kernel-specific argument (mirrors `PushConstants` in hash_common.glsl).
struct PushConstants {
  VoxelGridParams grid;
  std::uint32_t arg;
};

// Ceil-divide without the `items + kLocalSize - 1` term, which overflows uint32
// for items near UINT32_MAX (yielding ~0 groups -> a silent no-op dispatch).
std::uint32_t group_count(std::uint32_t items) {
  return items / kLocalSize + (items % kLocalSize != 0u ? 1u : 0u);
}

// `count` storage-buffer bindings at 0..count-1, all compute-stage.
std::vector<VkDescriptorSetLayoutBinding> storage_bindings(
    std::uint32_t count) {
  std::vector<VkDescriptorSetLayoutBinding> bindings(count);
  for (std::uint32_t i = 0; i < count; ++i) {
    bindings[i].binding = i;
    bindings[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    bindings[i].descriptorCount = 1;
    bindings[i].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  }
  return bindings;
}

// Build a compute pipeline from embedded SPIR-V + a descriptor-set layout, with
// a single PushConstants range. The shader module is transient (the pipeline
// does not retain it).
Result<ComputePipeline> make_pipeline(VkDevice device, const unsigned char* spv,
                                      std::size_t spv_size,
                                      VkDescriptorSetLayout layout) {
  VR_ASSIGN(ShaderModule module,
            ShaderModule::create(
                device, reinterpret_cast<const std::uint32_t*>(spv), spv_size));
  VkPushConstantRange push{};
  push.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push.offset = 0;
  push.size = sizeof(PushConstants);

  ComputePipelineDesc desc;
  desc.shader = &module;
  desc.set_layouts = &layout;
  desc.set_layout_count = 1;
  desc.push_ranges = &push;
  desc.push_range_count = 1;
  return ComputePipeline::create(device, desc);
}

// Record + submit one 1-D dispatch: bind, push, dispatch, then a memory barrier
// that makes this kernel's SSBO writes available and visible to (a) the next
// dispatch's shader reads/writes of the same persistent buffers and (b) a host
// read of the mapped results. Each kernel runs as its own one-shot submission
// (submit_single_time fully fence-waits it), and a fence orders execution but
// is NOT a memory dependency -- so this barrier, not the fence, is what carries
// cross-dispatch visibility (init -> allocate, allocate -> compact). Cheap: one
// global barrier per already-serialized dispatch.
Status dispatch(Device& device, const ComputePipeline& pipeline,
                VkDescriptorSet set, const PushConstants& push,
                std::uint32_t groups, std::uint32_t max_groups) {
  // A 1-D dispatch flattens the whole input onto groupCountX, but Vulkan only
  // guarantees maxComputeWorkGroupCount[0] >= 65535 -- an oversized depth frame
  // / point cloud (or huge grid) would be invalid usage on a min-spec (mobile)
  // driver. Reject it as a clean error rather than risk a device-lost.
  if (groups > max_groups) {
    return Status::invalid_argument(
        "VoxelHashMap dispatch: workgroup count exceeds the device's "
        "maxComputeWorkGroupCount[0] -- input too large for a 1-D dispatch");
  }
  return device.submit_single_time([&](VkCommandBuffer cmd) {
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline.handle());
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                            pipeline.layout(), 0, 1, &set, 0, nullptr);
    vkCmdPushConstants(cmd, pipeline.layout(), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       sizeof(PushConstants), &push);
    vkCmdDispatch(cmd, groups, 1, 1);
    VkMemoryBarrier barrier{};
    barrier.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
    barrier.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT |
                            VK_ACCESS_SHADER_WRITE_BIT |
                            VK_ACCESS_HOST_READ_BIT;
    vkCmdPipelineBarrier(
        cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_HOST_BIT, 0, 1,
        &barrier, 0, nullptr, 0, nullptr);
  });
}

// A host-visible, host-mapped storage buffer of the given byte size.
Result<Buffer> storage_buffer(Allocator& allocator, VkDeviceSize bytes,
                              HostAccess access = HostAccess::Random) {
  BufferDesc desc;
  desc.size = bytes;
  desc.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
  desc.memory = MemoryUsage::HostVisible;
  desc.mapped = true;
  desc.host_access = access;
  return allocator.create_buffer(desc);
}

// All the persistent device buffers, sized for one grid. Returned as a bundle
// so a caller commits them only once every allocation has succeeded: create()
// into a fresh map, resize() as an all-or-nothing swap over the live one (a
// partial in-place swap would strand descriptors on a freed buffer). Keeps the
// buffer sizing in one place -- the counterpart to write_persistent_bindings().
struct PersistentBuffers {
  Buffer entries;
  Buffer heap;
  Buffer heap_counter;
  Buffer bucket_mutex;
  Buffer fail_counts;
  Buffer compacted;
  Buffer active_count;
};

Result<PersistentBuffers> make_persistent_buffers(Allocator& allocator,
                                                  const VoxelGridParams& grid) {
  const auto total_entries = static_cast<std::uint32_t>(grid.num_buckets) *
                             static_cast<std::uint32_t>(grid.bucket_size);
  const auto num_blocks = static_cast<std::uint32_t>(grid.num_blocks);
  const auto num_buckets = static_cast<std::uint32_t>(grid.num_buckets);
  PersistentBuffers bufs;
  VR_ASSIGN(bufs.entries,
            storage_buffer(allocator,
                           VkDeviceSize(total_entries) * sizeof(HashEntry)));
  VR_ASSIGN(bufs.heap, storage_buffer(allocator, VkDeviceSize(num_blocks) *
                                                     sizeof(std::uint32_t)));
  VR_ASSIGN(bufs.heap_counter,
            storage_buffer(allocator, sizeof(std::uint32_t)));
  VR_ASSIGN(bufs.bucket_mutex,
            storage_buffer(allocator,
                           VkDeviceSize(num_buckets) * sizeof(std::int32_t)));
  VR_ASSIGN(bufs.fail_counts,
            storage_buffer(allocator, 4 * sizeof(std::uint32_t)));
  VR_ASSIGN(bufs.compacted, storage_buffer(allocator, VkDeviceSize(num_blocks) *
                                                          sizeof(BlockIndex)));
  VR_ASSIGN(bufs.active_count,
            storage_buffer(allocator, sizeof(std::uint32_t)));
  return bufs;
}

}  // namespace

Result<VoxelHashMap> VoxelHashMap::create(Device& device, Allocator& allocator,
                                          const VoxelGridParams& grid) {
  // Validate the full grid contract -- positivity AND the product invariants
  // (num_blocks == bucket_size*num_buckets, voxels_per_block == block_size^3)
  // that the buffer sizing and the block-pointer math below rely on.
  // VoxelGridParams::validate is the single source of truth for a usable grid.
  VR_TRY(grid.validate());

  const VkDevice dev = device.handle();

  VoxelHashMap map;
  map.device_ = &device;
  map.allocator_ = &allocator;
  map.grid_ = grid;

  // Persistent buffers + scratch (host-visible for this slice; device-local +
  // staging is a follow-up perf pass -- see the header TODO). Built as a bundle
  // and moved in together so the sizing lives in one place (make_persistent_-
  // buffers), shared with resize().
  VR_ASSIGN(PersistentBuffers bufs, make_persistent_buffers(allocator, grid));
  map.entries_ = std::move(bufs.entries);
  map.heap_ = std::move(bufs.heap);
  map.heap_counter_ = std::move(bufs.heap_counter);
  map.bucket_mutex_ = std::move(bufs.bucket_mutex);
  map.fail_counts_ = std::move(bufs.fail_counts);
  map.compacted_ = std::move(bufs.compacted);
  map.active_count_ = std::move(bufs.active_count);

  // Camera params for allocate_from_depth: a small (96 B), fixed-size buffer,
  // so persist it (bound once at binding 6 of depth_set_) and rewrite the
  // contents each call -- like fail_counts_, not a per-call allocation.
  // Grid-independent, so it is not part of the resized bundle.
  VR_ASSIGN(map.camera_params_,
            storage_buffer(allocator, sizeof(DepthCameraParams),
                           HostAccess::SequentialWrite));

  // A 1-D dispatch's groupCountX is capped by maxComputeWorkGroupCount[0] (>=
  // 65535 guaranteed); cache it so every dispatch can reject an over-large
  // input (an 8K+ depth frame / dense point cloud on a min-spec GPU) as a clean
  // error.
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  map.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];

  // One layout + pipeline per kernel (bindings match each shader's set 0).
  const auto init_b = storage_bindings(4);
  VR_ASSIGN(map.init_layout_,
            DescriptorSetLayout::create(
                dev, init_b.data(), static_cast<std::uint32_t>(init_b.size())));
  const auto alloc_b = storage_bindings(6);
  VR_ASSIGN(
      map.allocate_layout_,
      DescriptorSetLayout::create(dev, alloc_b.data(),
                                  static_cast<std::uint32_t>(alloc_b.size())));
  const auto compact_b = storage_bindings(3);
  VR_ASSIGN(
      map.compact_layout_,
      DescriptorSetLayout::create(
          dev, compact_b.data(), static_cast<std::uint32_t>(compact_b.size())));
  const auto delete_b = storage_bindings(6);
  VR_ASSIGN(
      map.delete_layout_,
      DescriptorSetLayout::create(dev, delete_b.data(),
                                  static_cast<std::uint32_t>(delete_b.size())));
  // Depth adds the camera-params buffer at binding 6 (7 bindings); allocate-
  // from-points reuses allocate_layout_ (same 6-binding shape as coords).
  const auto depth_b = storage_bindings(7);
  VR_ASSIGN(map.depth_layout_, DescriptorSetLayout::create(
                                   dev, depth_b.data(),
                                   static_cast<std::uint32_t>(depth_b.size())));
  // Frustum compaction adds the planes buffer (binding 3) to compact's shape.
  const auto compact_frustum_b = storage_bindings(4);
  VR_ASSIGN(map.compact_frustum_layout_,
            DescriptorSetLayout::create(
                dev, compact_frustum_b.data(),
                static_cast<std::uint32_t>(compact_frustum_b.size())));

  VR_ASSIGN(map.init_pipeline_, make_pipeline(dev, vr_hash_init_comp_spv,
                                              vr_hash_init_comp_spv_size,
                                              map.init_layout_.handle()));
  VR_ASSIGN(map.allocate_pipeline_,
            make_pipeline(dev, vr_hash_allocate_coords_comp_spv,
                          vr_hash_allocate_coords_comp_spv_size,
                          map.allocate_layout_.handle()));
  VR_ASSIGN(map.compact_pipeline_, make_pipeline(dev, vr_hash_compact_comp_spv,
                                                 vr_hash_compact_comp_spv_size,
                                                 map.compact_layout_.handle()));
  VR_ASSIGN(map.delete_pipeline_,
            make_pipeline(dev, vr_hash_delete_coords_comp_spv,
                          vr_hash_delete_coords_comp_spv_size,
                          map.delete_layout_.handle()));
  VR_ASSIGN(map.depth_pipeline_,
            make_pipeline(dev, vr_hash_allocate_depth_comp_spv,
                          vr_hash_allocate_depth_comp_spv_size,
                          map.depth_layout_.handle()));
  VR_ASSIGN(map.points_pipeline_,
            make_pipeline(dev, vr_hash_allocate_points_comp_spv,
                          vr_hash_allocate_points_comp_spv_size,
                          map.allocate_layout_.handle()));
  VR_ASSIGN(map.compact_frustum_pipeline_,
            make_pipeline(dev, vr_hash_compact_frustum_comp_spv,
                          vr_hash_compact_frustum_comp_spv_size,
                          map.compact_frustum_layout_.handle()));

  // Pool: one set per kernel, sized to the exact descriptor total. points_set_
  // is allocated from allocate_layout_, so it costs another alloc_b worth.
  VkDescriptorPoolSize pool_size{};
  pool_size.type = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
  pool_size.descriptorCount = static_cast<std::uint32_t>(
      init_b.size() + alloc_b.size() + compact_b.size() + delete_b.size() +
      depth_b.size() + alloc_b.size() + compact_frustum_b.size());
  VR_ASSIGN(map.pool_, DescriptorPool::create(dev, &pool_size, 1, 7));
  VR_ASSIGN(map.init_set_, map.pool_.allocate(map.init_layout_.handle()));
  VR_ASSIGN(map.allocate_set_,
            map.pool_.allocate(map.allocate_layout_.handle()));
  VR_ASSIGN(map.compact_set_, map.pool_.allocate(map.compact_layout_.handle()));
  VR_ASSIGN(map.delete_set_, map.pool_.allocate(map.delete_layout_.handle()));
  VR_ASSIGN(map.depth_set_, map.pool_.allocate(map.depth_layout_.handle()));
  VR_ASSIGN(map.points_set_, map.pool_.allocate(map.allocate_layout_.handle()));
  VR_ASSIGN(map.compact_frustum_set_,
            map.pool_.allocate(map.compact_frustum_layout_.handle()));

  // Point every set at the persistent buffers (the per-call coords buffer is
  // written before each allocate/delete dispatch). Shared with resize().
  map.write_persistent_bindings();

  VR_TRY(map.init_table());
  return map;
}

void VoxelHashMap::write_persistent_bindings() {
  // Bindings 0-3 (the table) are identical across the init, allocate, delete,
  // depth, and points sets. The four allocate-family sets (allocate / delete /
  // depth / points) additionally share the fail-counts buffer at binding 5 --
  // they never run in the same dispatch, and each re-zeroes it before use.
  // Their per-call input (coords / points at binding 4, depth+camera at 4+6) is
  // written before each dispatch. Compact uses entries + the compaction output
  // + its counter.
  const VkBuffer entries = entries_.handle();
  const VkBuffer heap = heap_.handle();
  const VkBuffer counter = heap_counter_.handle();
  const VkBuffer mutex = bucket_mutex_.handle();
  for (const DescriptorSet* set :
       {&init_set_, &allocate_set_, &delete_set_, &depth_set_, &points_set_}) {
    set->write_storage_buffer(0, entries, 0, VK_WHOLE_SIZE);
    set->write_storage_buffer(1, heap, 0, VK_WHOLE_SIZE);
    set->write_storage_buffer(2, counter, 0, VK_WHOLE_SIZE);
    set->write_storage_buffer(3, mutex, 0, VK_WHOLE_SIZE);
  }
  const VkBuffer fail = fail_counts_.handle();
  for (const DescriptorSet* set :
       {&allocate_set_, &delete_set_, &depth_set_, &points_set_}) {
    set->write_storage_buffer(5, fail, 0, VK_WHOLE_SIZE);
  }
  // depth_set_ alone has binding 6: the persistent camera params (its contents
  // are rewritten per call; only the depth buffer at binding 4 is transient).
  depth_set_.write_storage_buffer(6, camera_params_.handle(), 0, VK_WHOLE_SIZE);
  compact_set_.write_storage_buffer(0, entries, 0, VK_WHOLE_SIZE);
  compact_set_.write_storage_buffer(1, compacted_.handle(), 0, VK_WHOLE_SIZE);
  compact_set_.write_storage_buffer(2, active_count_.handle(), 0,
                                    VK_WHOLE_SIZE);
  // Frustum compaction shares the compaction output + counter with plain
  // compact; its planes buffer (binding 3) is written per call.
  compact_frustum_set_.write_storage_buffer(0, entries, 0, VK_WHOLE_SIZE);
  compact_frustum_set_.write_storage_buffer(1, compacted_.handle(), 0,
                                            VK_WHOLE_SIZE);
  compact_frustum_set_.write_storage_buffer(2, active_count_.handle(), 0,
                                            VK_WHOLE_SIZE);
}

std::uint32_t VoxelHashMap::total_entries() const noexcept {
  return static_cast<std::uint32_t>(grid_.num_buckets) *
         static_cast<std::uint32_t>(grid_.bucket_size);
}

Status VoxelHashMap::init_table() {
  const std::uint32_t widest =
      std::max({total_entries(), static_cast<std::uint32_t>(grid_.num_blocks),
                static_cast<std::uint32_t>(grid_.num_buckets)});
  const PushConstants push{grid_, 0};
  return dispatch(*device_, init_pipeline_, init_set_.handle(), push,
                  group_count(widest), max_workgroup_count_x_);
}

// Dispatch `pipeline` (bound through `set`, push arg = `arg`) over `groups`
// groups, re-dispatching while the reported failure count keeps dropping.
// Allocations spuriously fail under heavy same-bucket contention (a GPU
// spin-lock livelock within a SIMD group) -- worst for depth, whose adjacent
// pixels hammer the same block. Already-processed elements take the lock-free
// fast path on the next round (allocate / depth / points) or become a no-op
// (remove -- the delete kernel skips a coord it no longer finds without
// counting a failure), so contention falls and the set converges, unless a
// genuine capacity limit (chain full / heap empty) stalls progress. Mirrors the
// prior engine's launchWithRetry.
//
// fail_counts_[0] is the shared total-failures tally (allocate / depth / points
// also split reasons into [1]=lock/[2]=chain/[3]=heap); re-zeroed each round.
Result<std::uint32_t> VoxelHashMap::dispatch_with_retry(
    const ComputePipeline& pipeline, DescriptorSet& set, std::uint32_t arg,
    std::uint32_t groups) {
  const PushConstants push{grid_, arg};
  constexpr int kMaxRounds = 10;
  constexpr int kStallLimit = 2;  // consecutive no-progress rounds -> give up
  std::uint32_t failures = 0;
  std::uint32_t prev_failures = std::numeric_limits<std::uint32_t>::max();
  int stall = 0;
  for (int round = 0; round < kMaxRounds; ++round) {
    std::memset(fail_counts_.mapped(), 0, 4 * sizeof(std::uint32_t));
    VR_TRY(dispatch(*device_, pipeline, set.handle(), push, groups,
                    max_workgroup_count_x_));
    std::memcpy(&failures, fail_counts_.mapped(), sizeof(std::uint32_t));
    if (failures == 0) {
      break;
    }
    if (failures < prev_failures) {
      prev_failures = failures;
      stall = 0;
    } else if (++stall >= kStallLimit) {
      break;  // no progress across kStallLimit rounds -> a real capacity limit
    }
  }
  return failures;
}

Result<Buffer> VoxelHashMap::upload_to_binding(DescriptorSet& set,
                                               std::uint32_t binding,
                                               const void* data,
                                               VkDeviceSize bytes) {
  VR_ASSIGN(Buffer buf,
            storage_buffer(*allocator_, bytes, HostAccess::SequentialWrite));
  std::memcpy(buf.mapped(), data, static_cast<std::size_t>(bytes));
  set.write_storage_buffer(binding, buf.handle(), 0, VK_WHOLE_SIZE);
  return buf;  // caller keeps it alive across the (synchronous) dispatch
}

Result<std::uint32_t> VoxelHashMap::run_input_kernel(
    const char* op, const void* data, std::size_t elem_size,
    std::uint32_t count, DescriptorSet& set, const ComputePipeline& pipeline) {
  if (!valid()) {
    return Status::invalid_argument(std::string(op) + ": moved-from map");
  }
  if (count == 0) {
    return std::uint32_t{0};
  }
  if (data == nullptr) {
    return Status::invalid_argument(std::string(op) + ": input is null");
  }

  // The input is genuinely per-call (variable count), so this buffer is
  // transient; fail_counts_ is persistent and re-zeroed per round inside
  // dispatch_with_retry.
  VR_ASSIGN(Buffer input_buf,
            upload_to_binding(set, 4, data, VkDeviceSize(count) * elem_size));
  return dispatch_with_retry(pipeline, set, count, group_count(count));
}

Result<std::uint32_t> VoxelHashMap::allocate(const BlockIndex* coords,
                                             std::uint32_t count) {
  return run_input_kernel("VoxelHashMap::allocate", coords, sizeof(BlockIndex),
                          count, allocate_set_, allocate_pipeline_);
}

Result<std::uint32_t> VoxelHashMap::allocate_from_depth(
    const float* depth, const DepthCameraParams& camera) {
  if (!valid()) {
    return Status::invalid_argument(
        "VoxelHashMap::allocate_from_depth: moved-from map");
  }
  if (depth == nullptr) {
    return Status::invalid_argument(
        "VoxelHashMap::allocate_from_depth: depth is null");
  }
  const std::uint64_t pixel_count =
      static_cast<std::uint64_t>(camera.width) * camera.height;
  if (pixel_count == 0) {
    return std::uint32_t{0};
  }
  // One dispatch thread per pixel. width*height feeds the 32-bit group count
  // (the depth shader derives its own bound from cam.width*cam.height); reject
  // a pathological image dimension here rather than let the uint64 product
  // truncate. dispatch() separately caps groupCountX at the device limit.
  if (pixel_count > std::numeric_limits<std::uint32_t>::max()) {
    return Status::invalid_argument(
        "VoxelHashMap::allocate_from_depth: width*height exceeds 2^32");
  }
  const auto pixels = static_cast<std::uint32_t>(pixel_count);

  // Depth samples are per-call/variable (transient, binding 4); the camera
  // params ride the persistent camera_params_ buffer (binding 6, bound once at
  // create), rewritten in place here.
  VR_ASSIGN(Buffer depth_buf,
            upload_to_binding(depth_set_, 4, depth,
                              VkDeviceSize(pixels) * sizeof(float)));
  std::memcpy(camera_params_.mapped(), &camera, sizeof(DepthCameraParams));

  return dispatch_with_retry(depth_pipeline_, depth_set_, pixels,
                             group_count(pixels));
}

Result<std::uint32_t> VoxelHashMap::allocate_from_points(const Vec3f* points,
                                                         std::uint32_t count) {
  return run_input_kernel("VoxelHashMap::allocate_from_points", points,
                          sizeof(Vec3f), count, points_set_, points_pipeline_);
}

Result<std::uint32_t> VoxelHashMap::remove(const BlockIndex* coords,
                                           std::uint32_t count) {
  return run_input_kernel("VoxelHashMap::remove", coords, sizeof(BlockIndex),
                          count, delete_set_, delete_pipeline_);
}

Result<std::vector<BlockIndex>> VoxelHashMap::collect_compacted(
    const ComputePipeline& pipeline, DescriptorSet& set) {
  // The active set is at most num_blocks entries; the persistent output buffer
  // is sized to that upper bound, so no grow/retry is needed for this slice.
  const auto capacity = static_cast<std::uint32_t>(grid_.num_blocks);
  std::memset(active_count_.mapped(), 0, sizeof(std::uint32_t));

  const PushConstants push{grid_, capacity};
  VR_TRY(dispatch(*device_, pipeline, set.handle(), push,
                  group_count(total_entries()), max_workgroup_count_x_));

  std::uint32_t count = 0;
  std::memcpy(&count, active_count_.mapped(), sizeof(std::uint32_t));
  count = std::min(count, capacity);
  std::vector<BlockIndex> active(count);
  if (count > 0) {
    std::memcpy(active.data(), compacted_.mapped(),
                static_cast<std::size_t>(count) * sizeof(BlockIndex));
  }
  return active;
}

Result<std::vector<BlockIndex>> VoxelHashMap::compact_active_blocks() {
  if (!valid()) {
    return Status::invalid_argument(
        "VoxelHashMap::compact_active_blocks: moved-from map");
  }
  return collect_compacted(compact_pipeline_, compact_set_);
}

Result<std::vector<BlockIndex>> VoxelHashMap::compact_active_blocks_in_frustum(
    const FrustumPlanes& planes) {
  if (!valid()) {
    return Status::invalid_argument(
        "VoxelHashMap::compact_active_blocks_in_frustum: moved-from map");
  }
  // The six planes are per-call; upload them to binding 3 of the frustum set.
  VR_ASSIGN(Buffer planes_buf,
            storage_buffer(*allocator_, sizeof(FrustumPlanes),
                           HostAccess::SequentialWrite));
  std::memcpy(planes_buf.mapped(), planes.data(), sizeof(FrustumPlanes));
  compact_frustum_set_.write_storage_buffer(3, planes_buf.handle(), 0,
                                            VK_WHOLE_SIZE);
  return collect_compacted(compact_frustum_pipeline_, compact_frustum_set_);
}

Result<std::vector<BlockIndex>> VoxelHashMap::compact_active_blocks_in_frustum(
    const DepthCameraParams& camera) {
  return compact_active_blocks_in_frustum(make_frustum_planes(
      camera.fx, camera.fy, camera.cx, camera.cy, camera.width, camera.height,
      camera.min_depth, camera.max_depth, camera.cam_to_world));
}

Status VoxelHashMap::clear() {
  if (!valid()) {
    return Status::invalid_argument("VoxelHashMap::clear: moved-from map");
  }
  return init_table();
}

Status VoxelHashMap::resize(std::int32_t new_num_buckets) {
  if (!valid()) {
    return Status::invalid_argument("VoxelHashMap::resize: moved-from map");
  }
  if (new_num_buckets <= grid_.num_buckets) {
    return Status::invalid_argument(
        "VoxelHashMap::resize: new_num_buckets must exceed the current count");
  }

  // Snapshot the active blocks before growing (compact reads the old table).
  VR_ASSIGN(std::vector<BlockIndex> active, compact_active_blocks());

  // The grown grid: num_blocks == bucket_size * num_buckets (one block per
  // slot), the invariant create() validates.
  VoxelGridParams new_grid = grid_;
  new_grid.num_buckets = new_num_buckets;
  new_grid.num_blocks =
      static_cast<std::int32_t>(static_cast<std::uint32_t>(new_num_buckets) *
                                static_cast<std::uint32_t>(grid_.bucket_size));

  // Build the larger buffers off to the side and commit only once all of them
  // exist, so a mid-grow allocation failure leaves the live map untouched (a
  // partial in-place swap would strand descriptors on a freed buffer while
  // valid() still reported true). compacted_ tracks num_blocks, so it grows
  // too.
  VR_ASSIGN(PersistentBuffers bufs,
            make_persistent_buffers(*allocator_, new_grid));
  entries_ = std::move(bufs.entries);
  heap_ = std::move(bufs.heap);
  heap_counter_ = std::move(bufs.heap_counter);
  bucket_mutex_ = std::move(bufs.bucket_mutex);
  fail_counts_ = std::move(bufs.fail_counts);
  compacted_ = std::move(bufs.compacted);
  active_count_ = std::move(bufs.active_count);
  grid_ = new_grid;

  // Point the sets at the new buffers, init the larger table, and re-insert.
  write_persistent_bindings();
  VR_TRY(init_table());

  // Re-drive the whole snapshot up to kReinsertPasses times: allocate() skips
  // already-present coords, and the grown table has strictly less hash pressure
  // than the one the set already fit, so this converges past any transient
  // bucket-lock contention. A residual failure is a genuine overflow.
  std::uint32_t failed = 0;
  for (int pass = 0; pass < kReinsertPasses && !active.empty(); ++pass) {
    VR_ASSIGN(failed, allocate(active.data(),
                               static_cast<std::uint32_t>(active.size())));
    if (failed == 0) {
      break;
    }
  }
  if (failed != 0) {
    return Status::out_of_memory(
        "VoxelHashMap::resize: re-insert failed after growing");
  }
  return {};
}

Result<std::vector<HashEntry>> VoxelHashMap::read_entries() {
  if (!valid()) {
    return Status::invalid_argument(
        "VoxelHashMap::read_entries: moved-from map");
  }
  const std::uint32_t total = total_entries();
  std::vector<HashEntry> entries(total);
  std::memcpy(entries.data(), entries_.mapped(),
              static_cast<std::size_t>(total) * sizeof(HashEntry));
  return entries;
}

Result<HashDiagnostics> VoxelHashMap::diagnostics() {
  if (!valid()) {
    return Status::invalid_argument(
        "VoxelHashMap::diagnostics: moved-from map");
  }
  VR_ASSIGN(std::vector<HashEntry> entries, read_entries());
  std::uint32_t heap_free = 0;
  std::memcpy(&heap_free, heap_counter_.mapped(), sizeof(std::uint32_t));

  const int num_buckets = grid_.num_buckets;
  const int bucket_size = grid_.bucket_size;
  const int total_slots = static_cast<int>(total_entries());

  HashDiagnostics diag;
  diag.heap_free_count = static_cast<std::int32_t>(heap_free);
  diag.total_blocks = grid_.num_blocks;

  // One pass per bucket: count active primary slots, then walk the collision
  // chain from the anchor (last slot of the bucket) counting its length + the
  // active overflow slots on it. Host port of computeDiagnostics.
  // TODO(volume): a GPU-side scan is a perf follow-up for very large tables.
  for (int bucket = 0; bucket < num_buckets; ++bucket) {
    const int start = bucket * bucket_size;
    for (int i = 0; i < bucket_size; ++i) {
      const int ptr = entries[start + i].ptr;
      if (ptr != kFreeEntry && ptr != kLockEntry) {
        ++diag.active_count;
      }
    }
    const int anchor = (bucket + 1) * bucket_size - 1;
    int chain_length = 0;
    int curr = anchor;
    for (int hop = 0; hop < grid_.max_chain; ++hop) {
      const int off = entries[curr].offset;
      if (off == kNoOffset) {
        break;
      }
      // offset is relative to the anchor and may be negative; wrap into range.
      const long long raw = static_cast<long long>(anchor) + off;
      const int next =
          static_cast<int>(((raw % total_slots) + total_slots) % total_slots);
      ++chain_length;
      const int ptr = entries[next].ptr;
      if (ptr != kFreeEntry && ptr != kLockEntry) {
        ++diag.overflow_count;
      }
      curr = next;
    }
    diag.max_chain_length = std::max(diag.max_chain_length, chain_length);
  }

  if (total_slots > 0) {
    diag.load_factor =
        static_cast<float>(diag.active_count) / static_cast<float>(total_slots);
  }
  if (diag.total_blocks > 0) {
    diag.heap_utilization = 1.0f - static_cast<float>(heap_free) /
                                       static_cast<float>(diag.total_blocks);
  }
  return diag;
}

}  // namespace volumetric_kit::recon::volume
