// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/volume/voxel_hash_map.hpp"

#include <algorithm>
#include <atomic>
#include <functional>
#include <limits>
#include <string>
#include <utility>
#include <vector>

#include "volumetric_kit/core/vulkan/command_batch.hpp"
#include "volumetric_kit/core/vulkan/compute_util.hpp"
#include "volumetric_kit/core/vulkan/device.hpp"
#include "volumetric_kit/core/vulkan/gpu_timer.hpp"
#include "volumetric_kit/core/vulkan/vulkan.hpp"
#include "volumetric_kit/recon/core/device_requirements.hpp"
#include "volumetric_kit/recon/volume/hash.hpp"
#include "volumetric_kit/recon/volume/triangle_candidates.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "hash_allocate_coords_comp.spv.hpp"
#include "hash_allocate_depth_comp.spv.hpp"
#include "hash_allocate_points_comp.spv.hpp"
#include "hash_allocate_triangles_comp.spv.hpp"
#include "hash_compact_comp.spv.hpp"
#include "hash_compact_frustum_comp.spv.hpp"
#include "hash_delete_coords_comp.spv.hpp"
#include "hash_init_comp.spv.hpp"
#include "hash_rehash_comp.spv.hpp"

namespace volumetric_kit::recon::volume {
namespace {

// Local group size, matching `layout(local_size_x = 256)` in every kernel.
constexpr std::uint32_t kLocalSize = 256;

// Bounded passes for the resize rehash. insert_block is idempotent (an
// already-present coord is a no-op), so re-driving the whole snapshot absorbs
// transient bucket-lock contention; the cap keeps a genuine chain overflow --
// a bucket the changed modulus concentrates past max_chain, still possible even
// though the set fit the old table -- from looping forever.
constexpr int kReinsertPasses = 3;

// dispatch_with_retry's bound on rounds; see there.
constexpr std::uint32_t kMaxRounds = 10;

// The push-constant block every kernel shares: the grid shape plus one
// kernel-specific argument (mirrors `PushConstants` in hash_common.glsl).
struct PushConstants {
  VoxelGridParams grid;
  std::uint32_t arg;
  std::uint32_t tick;  // what allocation stamps a block with
};

// This tier's local_size, bound once so every call site reads group_count(n).
std::uint32_t group_count(std::uint32_t items) {
  return core::group_count(items, kLocalSize);
}

// The depth kernel's tile side: a workgroup is a kDepthTile x kDepthTile tile
// of pixels (mirrored by hash_allocate_depth.comp's kTile), so it dispatches a
// group a tile.
constexpr std::uint32_t kDepthTile = 16;
static_assert(kDepthTile * kDepthTile == kLocalSize,
              "a depth tile is one workgroup");

// A frame's tiles along x, which the kernel reads to place each group, and in
// all. Rounded up in 64 bits, since a width near 2^32 would wrap; the total
// fits 32, as allocate_from_depth refuses a frame past 2^32 pixels.
struct DepthTiles {
  std::uint32_t x;
  std::uint32_t total;
};
DepthTiles depth_tiles(const DepthCameraParams& camera) {
  const std::uint64_t x =
      (std::uint64_t{camera.width} + kDepthTile - 1) / kDepthTile;
  const std::uint64_t y =
      (std::uint64_t{camera.height} + kDepthTile - 1) / kDepthTile;
  return {static_cast<std::uint32_t>(x), static_cast<std::uint32_t>(x * y)};
}

// All the persistent device buffers, sized for one grid. Returned as a bundle
// so a caller commits them only once every allocation has succeeded: create()
// into a fresh map, resize() as an all-or-nothing swap over the live one (a
// partial in-place swap would strand descriptors on a freed buffer). Keeps the
// buffer sizing in one place -- the counterpart to write_persistent_bindings().
struct PersistentBuffers {
  core::Buffer entries;
  core::Buffer heap;
  core::Buffer heap_counter;
  core::Buffer bucket_mutex;
  core::Buffer fail_counts;
  core::Buffer compacted;
  core::Buffer active_count;
  core::Buffer stamps;
};

core::Result<PersistentBuffers> make_persistent_buffers(
    core::Allocator& allocator, const VoxelGridParams& grid) {
  const auto total_entries = static_cast<std::uint32_t>(grid.num_buckets) *
                             static_cast<std::uint32_t>(grid.bucket_size);
  const auto num_blocks = static_cast<std::uint32_t>(grid.num_blocks);
  const auto num_buckets = static_cast<std::uint32_t>(grid.num_buckets);
  // All device-local: only the kernels read and write them, and the host
  // reaches the counters through a CommandBatch (the 2026-09-28 residency
  // decision). The bucket locks were the first measured case: a spin lock in
  // host-visible memory is an atomic across PCIe per attempt, which took
  // 1.97 s to allocate a 5 000-triangle sheet on an RTX 5090 (3.4 ms
  // device-local).
  PersistentBuffers bufs;
  VKC_ASSIGN(bufs.entries,
             core::device_storage_buffer(
                 allocator, VkDeviceSize(total_entries) * sizeof(HashEntry)));
  VKC_ASSIGN(bufs.heap,
             core::device_storage_buffer(
                 allocator, VkDeviceSize(num_blocks) * sizeof(std::uint32_t)));
  VKC_ASSIGN(bufs.heap_counter,
             core::device_storage_buffer(allocator, sizeof(std::uint32_t)));
  VKC_ASSIGN(bufs.bucket_mutex,
             core::device_storage_buffer(
                 allocator, VkDeviceSize(num_buckets) * sizeof(std::int32_t)));
  VKC_ASSIGN(bufs.fail_counts,
             core::device_storage_buffer(allocator,
                                         kFailSlots * sizeof(std::uint32_t)));
  VKC_ASSIGN(bufs.compacted,
             core::device_storage_buffer(
                 allocator, VkDeviceSize(num_blocks) * sizeof(BlockIndex)));
  VKC_ASSIGN(bufs.active_count,
             core::device_storage_buffer(allocator, sizeof(std::uint32_t)));
  VKC_ASSIGN(bufs.stamps,
             core::device_storage_buffer(
                 allocator, VkDeviceSize(num_blocks) * sizeof(BlockStamp)));
  return bufs;
}

}  // namespace

core::Result<VoxelHashMap> VoxelHashMap::create(core::Device& device,
                                                core::Allocator& allocator,
                                                const VoxelGridParams& grid) {
  VKC_TRY(check_device_requirements(device, "VoxelHashMap::create"));
  // Validate the full grid contract -- positivity AND the product invariants
  // (num_blocks == bucket_size*num_buckets, voxels_per_block == block_size^3)
  // that the buffer sizing and the block-pointer math below rely on.
  // VoxelGridParams::validate is the single source of truth for a usable grid.
  VKC_TRY(grid.validate());

  VoxelHashMap map;
  map.device_ = &device;
  map.allocator_ = &allocator;
  map.grid_ = grid;
  // Drawn here and not left at 0, so this table's very first topology is
  // already distinct from every other table's -- including one that lived at
  // this address and has since been destroyed. A per-map count starting at 0
  // would make a fresh map indistinguishable from a dead one whose cache is
  // still anchored (see topology_epoch()).
  map.topology_epoch_ = next_topology_epoch();

  // Persistent buffers + scratch, all device-local. Built as a bundle and
  // moved in together so the sizing lives in one place (make_persistent_-
  // buffers), shared with resize().
  VKC_ASSIGN(PersistentBuffers bufs, make_persistent_buffers(allocator, grid));
  map.entries_ = std::move(bufs.entries);
  map.heap_ = std::move(bufs.heap);
  map.heap_counter_ = std::move(bufs.heap_counter);
  map.bucket_mutex_ = std::move(bufs.bucket_mutex);
  map.fail_counts_ = std::move(bufs.fail_counts);
  map.compacted_ = std::move(bufs.compacted);
  map.active_count_ = std::move(bufs.active_count);
  map.stamps_ = std::move(bufs.stamps);

  // Camera params for allocate_from_depth: a small (96 B), fixed-size buffer,
  // so persist it (binding 6 of every depth set) and rewrite it inline ahead
  // of each frame's dispatch. Grid-independent, so it is not part of the
  // resized bundle.
  VKC_ASSIGN(map.camera_params_,
             core::device_storage_buffer(allocator, sizeof(DepthCameraParams)));
  // Frustum planes for compact_active_blocks_in_frustum: likewise a small
  // (96 B), fixed-size buffer, persisted at binding 3 of compact_frustum_.set.
  VKC_ASSIGN(map.frustum_planes_,
             core::device_storage_buffer(allocator, sizeof(FrustumPlanes)));

  // A 1-D dispatch's groupCountX is capped by maxComputeWorkGroupCount[0] (>=
  // 65535 guaranteed); cache it so every dispatch can reject an over-large
  // input (an 8K+ depth frame / dense point cloud on a min-spec GPU) as a clean
  // error.
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  map.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  // The device-span collector, created once rather than per call: a query pool
  // of a few timestamps costs nothing and a diagnostic that can fail on first
  // use is worse. A pool that will not allocate degrades to unavailable inside
  // create() rather than failing here -- see GpuTimer.
  VKC_ASSIGN(map.gpu_timer_, core::GpuTimer::create(device));
  map.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;

  // Build every kernel's layout + pipeline and size the shared pool_ to them
  // via KernelSetBuilder (core/vulkan/compute_kernel.hpp) -- one add() per
  // shader, its storage-buffer binding count matching that shader's set 0.
  // Every kernel pushes the shared PushConstants block. allocate-from-coords
  // and -from-points have the same 7-binding shape but each owns its kernel;
  // depth adds the camera-params buffer at binding 6 (8 bindings), delete its
  // done flags there; frustum compaction adds the planes buffer at binding 3 (4
  // bindings). The stamps go last in every kernel that writes them: init's 4,
  // the allocators' and delete's after their own inputs.
  VkPushConstantRange push{};
  push.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push.offset = 0;
  push.size = sizeof(PushConstants);

  core::KernelSetBuilder kb(device);
  VKC_TRY(kb.add(map.init_, "hash_init", vr_hash_init_comp_spv,
                 vr_hash_init_comp_spv_size, 5, &push));
  VKC_TRY(kb.add(map.allocate_, "hash_allocate_coords",
                 vr_hash_allocate_coords_comp_spv,
                 vr_hash_allocate_coords_comp_spv_size, 7, &push));
  VKC_TRY(kb.add(map.compact_, "hash_compact", vr_hash_compact_comp_spv,
                 vr_hash_compact_comp_spv_size, 3, &push));
  VKC_TRY(kb.add(map.delete_, "hash_delete_coords",
                 vr_hash_delete_coords_comp_spv,
                 vr_hash_delete_coords_comp_spv_size, 8, &push));
  VKC_TRY(kb.add(map.depth_, "hash_allocate_depth",
                 vr_hash_allocate_depth_comp_spv,
                 vr_hash_allocate_depth_comp_spv_size, 8, &push));
  VKC_TRY(kb.add(map.points_, "hash_allocate_points",
                 vr_hash_allocate_points_comp_spv,
                 vr_hash_allocate_points_comp_spv_size, 7, &push));
  VKC_TRY(kb.add(map.triangles_, "hash_allocate_triangles",
                 vr_hash_allocate_triangles_comp_spv,
                 vr_hash_allocate_triangles_comp_spv_size, 9, &push));
  VKC_TRY(kb.add(map.compact_frustum_, "hash_compact_frustum",
                 vr_hash_compact_frustum_comp_spv,
                 vr_hash_compact_frustum_comp_spv_size, 4, &push));
  VKC_TRY(kb.add(map.rehash_, "hash_rehash", vr_hash_rehash_comp_spv,
                 vr_hash_rehash_comp_spv_size, 6, &push));
  VKC_ASSIGN(map.pool_, kb.build());

  // Point every set at the persistent buffers (the per-call coords buffer is
  // written before each allocate/delete dispatch). Shared with resize().
  map.write_persistent_bindings();

  VKC_TRY(map.init_table());
  return map;
}

void VoxelHashMap::write_persistent_bindings() {
  // Bindings 0-3 (the table) are identical across the init, allocate, delete,
  // points, and triangles sets. The allocate-family sets (allocate / delete /
  // points / triangles) additionally share the fail-counts buffer at binding
  // 5 -- they never run in the same dispatch, and each re-zeroes it before
  // use. Their per-call input (coords / points at binding 4, delete's done
  // flags at 6, vertices+indices+offsets at 4+6+7) is written before each
  // dispatch. The depth kernel's sets (depth_sets_) are written whole by each
  // allocate_from_depth. Compact uses entries + the compaction output + its
  // counter.
  const VkBuffer entries = entries_.handle();
  const VkBuffer heap = heap_.handle();
  const VkBuffer counter = heap_counter_.handle();
  const VkBuffer mutex = bucket_mutex_.handle();
  for (const core::DescriptorSet* set :
       {&init_.set, &allocate_.set, &delete_.set, &points_.set, &triangles_.set,
        &rehash_.set}) {
    set->write_storage_buffer(0, entries, 0, VK_WHOLE_SIZE);
    set->write_storage_buffer(1, heap, 0, VK_WHOLE_SIZE);
    set->write_storage_buffer(2, counter, 0, VK_WHOLE_SIZE);
    set->write_storage_buffer(3, mutex, 0, VK_WHOLE_SIZE);
  }
  const VkBuffer fail = fail_counts_.handle();
  for (const core::DescriptorSet* set :
       {&allocate_.set, &delete_.set, &points_.set, &triangles_.set,
        &rehash_.set}) {
    set->write_storage_buffer(5, fail, 0, VK_WHOLE_SIZE);
  }
  const VkBuffer stamps = stamps_.handle();
  init_.set.write_storage_buffer(4, stamps, 0, VK_WHOLE_SIZE);
  allocate_.set.write_storage_buffer(6, stamps, 0, VK_WHOLE_SIZE);
  points_.set.write_storage_buffer(6, stamps, 0, VK_WHOLE_SIZE);
  delete_.set.write_storage_buffer(7, stamps, 0, VK_WHOLE_SIZE);
  triangles_.set.write_storage_buffer(8, stamps, 0, VK_WHOLE_SIZE);
  compact_.set.write_storage_buffer(0, entries, 0, VK_WHOLE_SIZE);
  compact_.set.write_storage_buffer(1, compacted_.handle(), 0, VK_WHOLE_SIZE);
  compact_.set.write_storage_buffer(2, active_count_.handle(), 0,
                                    VK_WHOLE_SIZE);
  // Frustum compaction shares the compaction output + counter with plain
  // compact; its planes buffer (binding 3) is persistent, rewritten per call.
  compact_frustum_.set.write_storage_buffer(0, entries, 0, VK_WHOLE_SIZE);
  compact_frustum_.set.write_storage_buffer(1, compacted_.handle(), 0,
                                            VK_WHOLE_SIZE);
  compact_frustum_.set.write_storage_buffer(2, active_count_.handle(), 0,
                                            VK_WHOLE_SIZE);
  compact_frustum_.set.write_storage_buffer(3, frustum_planes_.handle(), 0,
                                            VK_WHOLE_SIZE);

  // Name each buffer for a GPU capture, here rather than at create: this runs
  // on every path that swaps a buffer in -- create AND each resize commit --
  // so a name cannot drift from the handle it describes. (A grown table is a
  // fresh handle, and a name lives on the handle.)
  if (device_ != nullptr) {
    const struct {
      VkBuffer handle;
      const char* name;
    } named[] = {
        {entries, "hash.entries"},
        {heap, "hash.heap"},
        {counter, "hash.heap_counter"},
        {mutex, "hash.bucket_mutex"},
        {fail, "hash.fail_counts"},
        {compacted_.handle(), "hash.compacted"},
        {active_count_.handle(), "hash.active_count"},
        {stamps, "hash.stamps"},
        {camera_params_.handle(), "hash.camera_params"},
        {frustum_planes_.handle(), "hash.frustum_planes"},
    };
    for (const auto& entry : named) {
      device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                               core::debug_object_handle(entry.handle),
                               entry.name);
    }
  }
}

std::uint32_t VoxelHashMap::total_entries() const noexcept {
  return static_cast<std::uint32_t>(grid_.num_buckets) *
         static_cast<std::uint32_t>(grid_.bucket_size);
}

VkBuffer VoxelHashMap::entries_buffer() const noexcept {
  return entries_.valid() ? entries_.handle() : VK_NULL_HANDLE;
}

VkDeviceSize VoxelHashMap::entries_buffer_size() const noexcept {
  // Gated on the same `valid()` as entries_buffer() one function above, not on
  // grid_ alone: grid_ is a POD the defaulted move COPIES, so a moved-from map
  // still knows its table shape while owning no buffer. Reporting the shape
  // there would pair a VK_NULL_HANDLE with a non-zero range in exactly the
  // descriptor write these two accessors exist to spell -- invalid usage this
  // repo cannot detect (neither nullDescriptor nor robustBufferAccess is
  // enabled), and one that looks well-formed in a debugger.
  return entries_.valid()
             ? static_cast<VkDeviceSize>(total_entries()) * sizeof(HashEntry)
             : 0;
}

core::Status VoxelHashMap::init_table() {
  const std::uint32_t widest =
      std::max({total_entries(), static_cast<std::uint32_t>(grid_.num_blocks),
                static_cast<std::uint32_t>(grid_.num_buckets)});
  const PushConstants push{grid_, 0, tick_};
  VKC_TRY(core::dispatch(*device_, init_, &push, sizeof(push),
                         group_count(widest), max_workgroup_count_x_));
  // The init kernel hands every block back to the heap.
  heap_free_ = static_cast<std::uint32_t>(grid_.num_blocks);
  return {};
}

core::Status VoxelHashMap::rebuild_heap_excluding(
    const std::vector<BlockIndex>& active) {
  const auto num_blocks = static_cast<std::uint32_t>(grid_.num_blocks);
  const auto vpb = static_cast<std::uint32_t>(grid_.voxels_per_block);

  // Mark the block indices the snapshot preserves (ptr = block_idx * vpb, so
  // block_idx = ptr / vpb; the old capacity <= the new, so every index is in
  // range). init_table left the heap holding all indices; overwrite it to hold
  // only the free ones so a future allocation never hands out a live block.
  std::vector<std::uint8_t> used(num_blocks, 0);
  for (const BlockIndex& b : active) {
    used[static_cast<std::uint32_t>(b.ptr) / vpb] = 1;
  }
  std::vector<std::uint32_t> heap;
  heap.reserve(num_blocks);
  for (std::uint32_t i = 0; i < num_blocks; ++i) {
    if (used[i] == 0) {
      heap.push_back(i);
    }
  }
  const auto free_count = static_cast<std::uint32_t>(heap.size());
  // TODO(volume): rebuild the heap on the device from the compacted list, so
  // a resize needs no host pass over num_blocks.
  core::CommandBatch batch(*device_, *allocator_);
  VKC_TRY(batch.upload(heap_, 0, heap.data(),
                       VkDeviceSize(free_count) * sizeof(std::uint32_t)));
  VKC_TRY(batch.upload(heap_counter_, 0, &free_count, sizeof(free_count)));
  VKC_TRY(batch.submit());
  heap_free_ = free_count;
  return {};
}

// Record what `dispatches` records each round, re-dispatching while failures
// remain, up to kMaxRounds.
// Allocations spuriously fail under heavy same-bucket contention (a GPU
// spin-lock livelock within a SIMD group) -- worst where one dispatch makes
// many new blocks, as depth's first frame does. Already-processed elements
// take the lock-free fast path on the next round (allocate / depth / points)
// or are skipped by their done flag (remove), so contention falls and the set
// converges. Only a genuine capacity limit (chain full / heap empty / table
// full) that stops progress for kStallLimit rounds ends the loop early;
// contention alone never does, since another round is what resolves it.
// Mirrors the prior engine's launchWithRetry.
//
// fail_counts_[kFailTotal] is the shared *retryable* tally, split by reason
// into [1]=lock/[2]=chain/[3]=heap/[5]=table (remove reports only lock);
// re-zeroed each round, since re-dispatching is what is supposed to drive it
// down.
//
// fail_counts_[kFailTerminal] is the failure the loop above cannot resolve, and
// it is accumulated across rounds rather than read from the last one. Only the
// delete kernel reports it: its heap append runs *after* the entry is cleared,
// so a coord whose block could not be returned to the free heap is absent on
// the next round and counts nothing. Reading only the final round would then
// report zero failures over a permanently leaked block index -- the convergence
// heuristic erasing the report instead of resolving it -- so the two are summed
// and the caller sees a non-zero count exactly when something did not complete.
core::Result<std::uint32_t> VoxelHashMap::dispatch_with_retry(
    const std::function<core::Status(core::CommandBatch&)>& dispatches,
    AllocFailures* out_failures,
    const std::function<core::Status(core::CommandBatch&)>& prepare) {
  constexpr int kStallLimit = 2;  // consecutive no-progress rounds -> give up
  std::uint32_t failures = 0;
  std::uint32_t terminal = 0;
  std::uint32_t prev_failures = std::numeric_limits<std::uint32_t>::max();
  int stall = 0;
  for (std::uint32_t round = 0; round < kMaxRounds; ++round) {
    // One submit a round: the call's parameters (the first round only -- they
    // persist), the cleared tally, the dispatch, and the two small results
    // the host decides on -- the tally, and the heap counter behind
    // load_factor().
    std::uint32_t slots[kFailSlots] = {};
    std::uint32_t heap_free = 0;
    core::CommandBatch batch(*device_, *allocator_);
    if (round == 0 && prepare) {
      VKC_TRY(prepare(batch));
    }
    VKC_TRY(batch.fill(fail_counts_, 0, sizeof(slots), 0u));
    VKC_TRY(dispatches(batch));
    VKC_TRY(batch.readback(fail_counts_, 0, sizeof(slots), slots));
    VKC_TRY(batch.readback(heap_counter_, 0, sizeof(heap_free), &heap_free));
    VKC_TRY(batch.submit());
    heap_free_ = heap_free;
    failures = slots[kFailTotal];
    terminal += slots[kFailTerminal];
    // The retryable reasons describe this round; terminal accumulates, since
    // no later round can restate it.
    const AllocFailures reported{failures,          slots[kFailLock],
                                 slots[kFailChain], slots[kFailHeap],
                                 slots[kFailTable], terminal};
    if (out_failures != nullptr) {
      *out_failures = reported;
    }
    if (failures == 0) {
      break;
    }
    if (failures < prev_failures) {
      prev_failures = failures;
      stall = 0;
    } else if (reported.capacity_limited() && ++stall >= kStallLimit) {
      break;  // a capacity limit stopped progress; another round cannot help
    }
  }
  return failures + terminal;
}

core::Result<core::Buffer> VoxelHashMap::upload_to_binding(
    core::CommandBatch& batch, const core::DescriptorSet& set,
    std::uint32_t binding, const void* data, VkDeviceSize bytes) {
  VKC_ASSIGN(core::Buffer buf, core::device_storage_buffer(*allocator_, bytes));
  VKC_TRY(batch.upload(buf, 0, data, bytes));
  set.write_storage_buffer(binding, buf.handle(), 0, VK_WHOLE_SIZE);
  return buf;  // caller keeps it alive until the batch has run
}

core::Result<std::uint32_t> VoxelHashMap::run_input_kernel(
    const char* op, const core::StorageInput& input, std::size_t elem_size,
    std::uint32_t count, const core::ComputeKernel& kernel,
    AllocFailures* out_failures, bool removes) {
  if (!valid()) {
    return core::Status::invalid_argument(std::string(op) + ": moved-from map");
  }
  if (count == 0) {
    return std::uint32_t{0};
  }
  // Host input is staged once; a device input stays where its producer wrote
  // it. fail_counts_ is persistent and re-zeroed per round inside
  // dispatch_with_retry. Bound the input to the logical count and reject a
  // range larger than one storage binding may cover.
  const VkDeviceSize input_bytes = VkDeviceSize(count) * elem_size;
  VKC_TRY(input.check(op, input_bytes));
  VKC_TRY(core::check_storage_buffer_range(op, input_bytes,
                                           max_storage_buffer_range_));
  if (removes) {
    // Moved once the input is accepted and BEFORE the dispatch: this is the
    // only place a block index is handed back to the heap, so a slot-keyed
    // cache is stale the moment the kernel runs -- whether it removes every
    // coord, some of them, or reports failures. A caller that reads the token
    // between the dispatch and a check placed after it would read the
    // pre-removal value.
    topology_epoch_ = next_topology_epoch();
  }
  core::Buffer input_buf;  // alive across every round
  core::Buffer done_buf;
  const PushConstants push{grid_, count, tick_};
  return dispatch_with_retry(
      [&](core::CommandBatch& batch) {
        return batch.dispatch(kernel, &push, sizeof(push), group_count(count),
                              max_workgroup_count_x_);
      },
      out_failures,
      [&](core::CommandBatch& batch) -> core::Status {
        VKC_ASSIGN(const VkBuffer input_handle,
                   input.buffer(batch, *allocator_, input_bytes, input_buf));
        kernel.set.write_storage_buffer(4, input_handle, 0, input_bytes);
        if (removes) {
          const VkDeviceSize bytes =
              VkDeviceSize(count) * sizeof(std::uint32_t);
          VKC_ASSIGN(done_buf, core::device_storage_buffer(*allocator_, bytes));
          VKC_TRY(batch.fill(done_buf, 0, bytes, 0u));
          kernel.set.write_storage_buffer(6, done_buf.handle(), 0,
                                          VK_WHOLE_SIZE);
        }
        return {};
      });
}

core::Result<std::uint32_t> VoxelHashMap::allocate(
    const BlockIndex* coords, std::uint32_t count,
    AllocFailures* out_failures) {
  return run_input_kernel("VoxelHashMap::allocate", core::StorageInput(coords),
                          sizeof(BlockIndex), count, allocate_, out_failures);
}

core::Result<std::uint32_t> VoxelHashMap::allocate_from_depth(
    const float* depth, const DepthCameraParams& camera,
    AllocFailures* out_failures, core::StageMetrics* metrics) {
  return allocate_from_depth({DepthInput{core::StorageInput(depth), camera}},
                             out_failures, metrics);
}

core::Result<std::uint32_t> VoxelHashMap::allocate_from_depth(
    const core::Buffer& depth, const DepthCameraParams& camera,
    AllocFailures* out_failures, core::StageMetrics* metrics) {
  return allocate_from_depth({DepthInput{core::StorageInput(depth), camera}},
                             out_failures, metrics);
}

core::Result<std::uint32_t> VoxelHashMap::allocate_from_depth(
    const std::vector<DepthInput>& frames, AllocFailures* out_failures,
    core::StageMetrics* metrics) {
  // Before the validity check, so a refused call still costs its row -- a stage
  // silent on failure reads as one that did not run. Inert when null, and it
  // publishes both halves on every return below, including the failing ones.
  core::GpuStageScope stage(metrics, gpu_timer_, "allocate");
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::allocate_from_depth: moved-from map");
  }
  // Every frame checked before any work. The shader indexes a pixel as
  // v*width + u in 32 bits, so an image past 2^32 pixels is refused here
  // rather than wrapped. A frame with no pixels dispatches nothing.
  std::vector<std::size_t> live;  // the frames that dispatch, in order
  std::vector<std::uint32_t> pixels(frames.size(), 0);
  for (std::size_t i = 0; i < frames.size(); ++i) {
    const DepthCameraParams& camera = frames[i].camera;
    const std::uint64_t count =
        static_cast<std::uint64_t>(camera.width) * camera.height;
    if (count > std::numeric_limits<std::uint32_t>::max()) {
      return core::Status::invalid_argument(
          "VoxelHashMap::allocate_from_depth: width*height exceeds 2^32");
    }
    const VkDeviceSize bytes = VkDeviceSize(count) * sizeof(float);
    VKC_TRY(frames[i].depth.check("VoxelHashMap::allocate_from_depth: depth",
                                  bytes));
    if (count == 0) continue;
    VKC_TRY(core::check_storage_buffer_range(
        "VoxelHashMap::allocate_from_depth: the depth buffer", bytes,
        max_storage_buffer_range_));
    pixels[i] = static_cast<std::uint32_t>(count);
    live.push_back(i);
  }
  if (live.empty()) {
    return std::uint32_t{0};
  }
  // A set a frame, and a device span a frame a round.
  const auto count = static_cast<std::uint32_t>(live.size());
  VKC_TRY(depth_sets_.reserve(*device_, depth_, count));
  VKC_TRY(gpu_timer_.reserve(*device_, kMaxRounds * count));

  // Each frame's depth is per-call (binding 4: a host array's device copy, or
  // the caller's buffer), and the camera rides the one persistent
  // camera_params_ (binding 6), rewritten inline ahead of each dispatch: the
  // batch's barrier around every dispatch orders the rewrite after the read.
  std::vector<core::Buffer> uploads(frames.size());  // alive across every round
  return dispatch_with_retry(
      [&](core::CommandBatch& batch) -> core::Status {
        // TODO(volume): re-dispatch only the frames that failed, from a tally
        // of each frame's own, if retries stay common after PERF.md's P3
        // (DECISIONS.md, 2026-09-30).
        for (std::size_t k = 0; k < live.size(); ++k) {
          const std::size_t i = live[k];
          VKC_TRY(batch.upload(camera_params_, 0, &frames[i].camera,
                               sizeof(DepthCameraParams)));
          const DepthTiles tiles = depth_tiles(frames[i].camera);
          const PushConstants push{grid_, tiles.x, tick_};
          VKC_TRY(batch.dispatch(depth_, depth_sets_[k], &push, sizeof(push),
                                 tiles.total, max_workgroup_count_x_, &stage));
        }
        return {};
      },
      out_failures,
      [&](core::CommandBatch& batch) -> core::Status {
        // Every binding of every set, so a set another call wrote, or one a
        // resize left naming freed buffers, is whole again.
        for (std::size_t k = 0; k < live.size(); ++k) {
          const std::size_t i = live[k];
          const VkDeviceSize bytes = VkDeviceSize(pixels[i]) * sizeof(float);
          VKC_ASSIGN(
              const VkBuffer depth,
              frames[i].depth.buffer(batch, *allocator_, bytes, uploads[i]));
          const core::DescriptorSet& set = depth_sets_[k];
          set.write_storage_buffer(0, entries_.handle(), 0, VK_WHOLE_SIZE);
          set.write_storage_buffer(1, heap_.handle(), 0, VK_WHOLE_SIZE);
          set.write_storage_buffer(2, heap_counter_.handle(), 0, VK_WHOLE_SIZE);
          set.write_storage_buffer(3, bucket_mutex_.handle(), 0, VK_WHOLE_SIZE);
          set.write_storage_buffer(4, depth, 0, bytes);
          set.write_storage_buffer(5, fail_counts_.handle(), 0, VK_WHOLE_SIZE);
          set.write_storage_buffer(6, camera_params_.handle(), 0,
                                   VK_WHOLE_SIZE);
          set.write_storage_buffer(7, stamps_.handle(), 0, VK_WHOLE_SIZE);
        }
        return {};
      });
}

core::Result<std::uint32_t> VoxelHashMap::allocate_from_points(
    const Vec3f* points, std::uint32_t count, AllocFailures* out_failures) {
  return run_input_kernel("VoxelHashMap::allocate_from_points",
                          core::StorageInput(points), sizeof(Vec3f), count,
                          points_, out_failures);
}

core::Result<std::uint32_t> VoxelHashMap::allocate_from_triangles(
    const Vec3f* vertices, std::uint32_t vertex_count,
    const std::uint32_t* indices, std::uint32_t triangle_count,
    AllocFailures* out_failures, core::StageMetrics* metrics) {
  // Before the validity check, as allocate_from_depth: a refused call still
  // costs its row, and here the row's CPU half is the point -- the host pass
  // below is the one part of this call a GPU capture cannot see.
  core::GpuStageScope stage(metrics, gpu_timer_, "allocate");
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::allocate_from_triangles: moved-from map");
  }
  if (triangle_count == 0) {
    return std::uint32_t{0};
  }

  // The host pass: one candidate-block count per triangle, as an exclusive
  // prefix sum (see triangle_candidate_offsets). It buys the kernel a uniform
  // work item, and it is where every index is bounds-checked and a degenerate
  // or non-finite triangle is dropped.
  VKC_ASSIGN(std::vector<std::uint32_t> offsets,
             triangle_candidate_offsets(
                 grid_, vertices, vertex_count, indices, triangle_count,
                 "VoxelHashMap::allocate_from_triangles"));
  const std::uint32_t total = offsets[triangle_count];
  if (total == 0) {
    return std::uint32_t{0};  // every triangle degenerate or non-finite
  }

  // Three transient inputs (the mesh is per-call and variable), each bound
  // whole, so each is checked against what one binding may cover.
  const VkDeviceSize vertex_bytes = VkDeviceSize(vertex_count) * sizeof(Vec3f);
  const VkDeviceSize index_bytes =
      VkDeviceSize(triangle_count) * 3 * sizeof(std::uint32_t);
  const VkDeviceSize offset_bytes =
      VkDeviceSize(offsets.size()) * sizeof(std::uint32_t);
  VKC_TRY(core::check_storage_buffer_range(
      "VoxelHashMap::allocate_from_triangles: the vertex buffer", vertex_bytes,
      max_storage_buffer_range_));
  VKC_TRY(core::check_storage_buffer_range(
      "VoxelHashMap::allocate_from_triangles: the index buffer", index_bytes,
      max_storage_buffer_range_));
  VKC_TRY(core::check_storage_buffer_range(
      "VoxelHashMap::allocate_from_triangles: the offset buffer", offset_bytes,
      max_storage_buffer_range_));
  core::Buffer vertex_buf, index_buf, offset_buf;  // alive across every round

  // pc.arg is the TRIANGLE count (the kernel's binary-search bound), not the
  // dispatch width -- the kernel reads that from offsets[pc.arg].
  const PushConstants push{grid_, triangle_count, tick_};
  return dispatch_with_retry(
      [&](core::CommandBatch& batch) {
        return batch.dispatch(triangles_, &push, sizeof(push),
                              group_count(total), max_workgroup_count_x_,
                              &stage);
      },
      out_failures,
      [&](core::CommandBatch& batch) -> core::Status {
        VKC_ASSIGN(vertex_buf, upload_to_binding(batch, triangles_.set, 4,
                                                 vertices, vertex_bytes));
        VKC_ASSIGN(index_buf, upload_to_binding(batch, triangles_.set, 6,
                                                indices, index_bytes));
        VKC_ASSIGN(offset_buf, upload_to_binding(batch, triangles_.set, 7,
                                                 offsets.data(), offset_bytes));
        return {};
      });
}

core::Result<std::uint32_t> VoxelHashMap::remove(const BlockIndex* coords,
                                                 std::uint32_t count,
                                                 AllocFailures* out_failures) {
  return run_input_kernel("VoxelHashMap::remove", core::StorageInput(coords),
                          sizeof(BlockIndex), count, delete_, out_failures,
                          true);
}

core::Result<std::uint32_t> VoxelHashMap::remove(const core::Buffer& coords,
                                                 std::uint32_t count,
                                                 AllocFailures* out_failures) {
  return run_input_kernel("VoxelHashMap::remove", core::StorageInput(coords),
                          sizeof(BlockIndex), count, delete_, out_failures,
                          true);
}

core::Result<std::uint32_t> VoxelHashMap::compact_into_device_list(
    const core::ComputeKernel& kernel, core::GpuStageScope* stage,
    const std::function<core::Status(core::CommandBatch&)>& prepare,
    BlockIndex* head, std::uint32_t head_count) {
  // The active set is at most num_blocks entries; the persistent output buffer
  // is sized to that upper bound, so no grow/retry is needed for this slice.
  const auto capacity = static_cast<std::uint32_t>(grid_.num_blocks);
  const PushConstants push{grid_, capacity, tick_};
  ++compaction_serial_;  // before the submit, which may have run in part
  std::uint32_t count = 0;
  core::CommandBatch batch(*device_, *allocator_);
  if (prepare) {
    VKC_TRY(prepare(batch));
  }
  VKC_TRY(batch.fill(active_count_, 0, sizeof(count), 0u));
  VKC_TRY(batch.dispatch(kernel, &push, sizeof(push),
                         group_count(total_entries()), max_workgroup_count_x_,
                         stage));
  VKC_TRY(batch.readback(active_count_, 0, sizeof(count), &count));
  VKC_TRY(batch.readback(compacted_, 0,
                         VkDeviceSize(head_count) * sizeof(BlockIndex), head));
  VKC_TRY(batch.submit());
  return std::min(count, capacity);
}

core::Result<std::vector<BlockIndex>> VoxelHashMap::collect_compacted(
    const core::ComputeKernel& kernel, std::uint32_t& last_count,
    core::GpuStageScope* stage,
    const std::function<core::Status(core::CommandBatch&)>& prepare) {
  // The list comes back beside its count, as far as a guess a quarter past
  // this kernel's last count, so a set that has not outgrown it costs one
  // submit rather than two (0.38 ms each on an RTX 5090).
  // TODO(volume): size the fuse's and the extract's dispatches on the device,
  // so no count reaches the host either.
  const std::uint32_t guess =
      static_cast<std::uint32_t>(std::min<std::uint64_t>(
          grid_.num_blocks, std::uint64_t(last_count) + last_count / 4));
  std::vector<BlockIndex> active(guess);
  VKC_ASSIGN(
      const std::uint32_t count,
      compact_into_device_list(kernel, stage, prepare, active.data(), guess));
  last_count = count;
  active.resize(count);
  if (count > guess) {
    // It outgrew the guess: the rest in a second submit.
    core::CommandBatch batch(*device_, *allocator_);
    VKC_TRY(batch.readback(compacted_, VkDeviceSize(guess) * sizeof(BlockIndex),
                           VkDeviceSize(count - guess) * sizeof(BlockIndex),
                           active.data() + guess));
    VKC_TRY(batch.submit());
  }
  return active;
}

// "active set" rather than "compact": rows merge by content, and the mesh tier
// already publishes a "  ..compact" breakdown for the same call inside its own
// extract. Two stages' compactions summed under one row is the collision
// kBreakdownPrefix exists to avoid, not to cause.
//
// Which of the two names applies is the caller's nesting, not this call's:
// under a fusion tier's open stage the host span is already counted by that
// stage's row, so the sub-row must carry the prefix to stay out of
// total_cpu_ms; at top level the same row would then be counted by no total at
// all, so it is named as the stage it is.
const char* VoxelHashMap::active_set_row(
    const core::StageMetrics* metrics) noexcept {
  return metrics != nullptr && metrics->in_stage() ? "  ..active set"
                                                   : "active set";
}

core::Result<std::vector<BlockIndex>> VoxelHashMap::compact_active_blocks(
    core::StageMetrics* metrics) {
  core::GpuStageScope stage(metrics, gpu_timer_, active_set_row(metrics));
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::compact_active_blocks: moved-from map");
  }
  return collect_compacted(compact_, last_active_count_, &stage);
}

core::Result<DeviceBlockList> VoxelHashMap::compact_active_blocks_on_device(
    core::StageMetrics* metrics) {
  // Above the row: a list that still holds is no compaction, so none is
  // reported.
  if (valid() && holds(last_device_list_)) return last_device_list_;
  core::GpuStageScope stage(metrics, gpu_timer_, active_set_row(metrics));
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::compact_active_blocks_on_device: moved-from map");
  }
  VKC_ASSIGN(const std::uint32_t count,
             compact_into_device_list(compact_, &stage));
  last_device_list_ = DeviceBlockList{&compacted_, count, topology_epoch_,
                                      compaction_serial_, heap_free_};
  return last_device_list_;
}

// The epoch moves on a remove or clear, the serial on any compaction or
// resize, and the heap's free count on an allocation: within one epoch it only
// falls.
bool VoxelHashMap::holds(const DeviceBlockList& list) const noexcept {
  return list.buffer == &compacted_ && list.epoch == topology_epoch_ &&
         list.serial == compaction_serial_ && list.heap_free == heap_free_;
}

core::Status VoxelHashMap::check_device_block_list(const DeviceBlockList& list,
                                                   const char* who) const {
  if (list.count == 0) return {};
  if (!valid()) {
    return core::Status::invalid_argument(std::string(who) +
                                          ": moved-from map");
  }
  if (list.buffer != &compacted_) {
    return core::Status::invalid_argument(
        std::string(who) +
        ": the device block list is not this map's, or the map has moved "
        "since it was compacted");
  }
  if (!holds(list)) {
    return core::Status::invalid_argument(
        std::string(who) +
        ": the device block list is stale: the map has compacted, allocated, "
        "resized, removed or cleared since");
  }
  return {};
}

core::Result<std::vector<BlockIndex>>
VoxelHashMap::compact_active_blocks_in_frustum(const FrustumPlanes& planes,
                                               core::StageMetrics* metrics) {
  core::GpuStageScope stage(metrics, gpu_timer_, active_set_row(metrics));
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::compact_active_blocks_in_frustum: moved-from map");
  }
  // The six planes are per-call; they go inline into the persistent buffer
  // bound once at binding 3 of the frustum set (like camera_params_).
  return collect_compacted(compact_frustum_, last_frustum_count_, &stage,
                           [&](core::CommandBatch& batch) {
                             return batch.upload(frustum_planes_, 0,
                                                 planes.data(),
                                                 sizeof(FrustumPlanes));
                           });
}

core::Result<std::vector<BlockIndex>>
VoxelHashMap::compact_active_blocks_in_frustum(const DepthCameraParams& camera,
                                               core::StageMetrics* metrics) {
  return compact_active_blocks_in_frustum(
      make_frustum_planes(camera.fx, camera.fy, camera.cx, camera.cy,
                          camera.width, camera.height, camera.min_depth,
                          camera.max_depth, camera.cam_to_world),
      metrics);
}

core::Status VoxelHashMap::clear() {
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::clear: moved-from map");
  }
  // Every index is about to go back to the heap, so every slot-keyed cache is
  // stale. Drawn before init_table for the same reason remove draws before its
  // dispatch. init_table itself must NOT draw: resize calls it too, and a
  // resize preserves block indices (see topology_epoch()).
  topology_epoch_ = next_topology_epoch();
  return init_table();
}

std::uint64_t VoxelHashMap::next_topology_epoch() noexcept {
  // Process-wide, so a token identifies a table's topology across the whole
  // program rather than within one object -- which is what makes an anchor
  // holding a stale token unrevivable by any later map. Atomic because nothing
  // stops two threads from building or mutating two different grids at once;
  // relaxed because the only thing required of it is that the values differ,
  // not that they order anything.
  //
  // Pre-incremented from 0, so the first token is 1 and a default-initialized
  // (moved-from, or never-created) member never equals a live one.
  static std::atomic<std::uint64_t> counter{0};
  return counter.fetch_add(1, std::memory_order_relaxed) + 1;
}

core::Status VoxelHashMap::resize(std::int32_t new_num_buckets) {
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::resize: moved-from map");
  }
  if (new_num_buckets <= grid_.num_buckets) {
    return core::Status::invalid_argument(
        "VoxelHashMap::resize: new_num_buckets must exceed the current count");
  }

  // Snapshot the active blocks before growing (compact reads the old table).
  VKC_ASSIGN(std::vector<BlockIndex> active, compact_active_blocks());

  // The grown grid: num_blocks == bucket_size * num_buckets (one block per
  // slot). validate() re-checks that invariant AND that num_blocks *
  // voxels_per_block still fits a signed 32-bit block pointer -- before any
  // mutation, so an over-large grow fails here with the live map untouched.
  VoxelGridParams new_grid = grid_;
  new_grid.num_buckets = new_num_buckets;
  // Widened before the cast. A uint32 product silently wraps, and it used to
  // wrap into a num_blocks that validate() -- which computed the same narrow
  // product -- then agreed with, so an over-large grow passed both checks and
  // sized the entries buffer from the wrapped value while the kernels indexed
  // it by the unwrapped bucket count.
  const std::int64_t new_num_blocks =
      static_cast<std::int64_t>(new_num_buckets) * grid_.bucket_size;
  if (new_num_blocks > std::numeric_limits<std::int32_t>::max()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::resize: new_num_buckets * bucket_size overflows a "
        "signed 32-bit num_blocks");
  }
  new_grid.num_blocks = static_cast<std::int32_t>(new_num_blocks);
  VKC_TRY(new_grid.validate());

  // Build the larger buffers off to the side; a failure here leaves the live
  // map untouched (nothing swapped yet). compacted_ tracks num_blocks, so it
  // grows too.
  VKC_ASSIGN(PersistentBuffers bufs,
             make_persistent_buffers(*allocator_, new_grid));

  // Swap the new buffers in, holding the old ones (and old grid) aside so ANY
  // failure past this point rolls the live map back to exactly its prior state.
  // resize is all-or-nothing across init_table / rehash too, not only the
  // allocation above: a half-swapped map (a grown grid_ over a partial or
  // uninitialised table, or a heap still listing the preserved live indices)
  // would corrupt later allocations while valid() reported true.
  PersistentBuffers old{std::move(entries_),      std::move(heap_),
                        std::move(heap_counter_), std::move(bucket_mutex_),
                        std::move(fail_counts_),  std::move(compacted_),
                        std::move(active_count_), std::move(stamps_)};
  const VoxelGridParams old_grid = grid_;
  const std::uint32_t old_heap_free = heap_free_;
  auto commit = [this](PersistentBuffers& b, const VoxelGridParams& g) {
    entries_ = std::move(b.entries);
    heap_ = std::move(b.heap);
    heap_counter_ = std::move(b.heap_counter);
    bucket_mutex_ = std::move(b.bucket_mutex);
    fail_counts_ = std::move(b.fail_counts);
    compacted_ = std::move(b.compacted);
    ++compaction_serial_;
    active_count_ = std::move(b.active_count);
    stamps_ = std::move(b.stamps);
    grid_ = g;
    write_persistent_bindings();  // point the sets at the committed buffers
  };
  commit(bufs, new_grid);

  // Init the larger table, then rehash the snapshot into it; on any failure,
  // roll back to the old buffers so a failed grow is a no-op.
  auto grow = [&]() -> core::Status {
    VKC_TRY(
        init_table());  // entries free, heap holds every index, mutexes clear
    // Each slot keeps its stamps, as it keeps its index; the new slots stay
    // zeroed.
    {
      core::CommandBatch batch(*device_, *allocator_);
      VKC_TRY(batch.copy(old.stamps, 0, stamps_, 0, old.stamps.size()));
      VKC_TRY(batch.submit());
    }
    if (active.empty()) {
      return {};  // fresh table + full heap is complete; nothing to rehash
    }
    // Rehash: re-insert each block with its ORIGINAL pointer (rehash_'s preset
    // path, not a fresh heap draw), so per-voxel data keyed by that pointer
    // survives the grow. The snapshot is loop-invariant, so upload it once;
    // insert_block is idempotent, so re-driving the dispatch absorbs transient
    // bucket-lock contention. A residual failure is a genuine chain overflow.
    const auto count = static_cast<std::uint32_t>(active.size());
    core::Buffer snapshot;
    const auto upload_snapshot =
        [&](core::CommandBatch& batch) -> core::Status {
      if (snapshot.valid()) return {};  // the first pass uploaded it
      VKC_ASSIGN(snapshot,
                 upload_to_binding(batch, rehash_.set, 4, active.data(),
                                   VkDeviceSize(count) * sizeof(BlockIndex)));
      return {};
    };
    // Keep the per-reason split rather than passing nullptr: this is the one
    // failure a caller cannot answer by growing (it *is* the grow), so the
    // reason is the only thing that makes it diagnosable -- chain overflow in
    // the new table reads very differently from residual lock contention.
    std::uint32_t failed = 0;
    AllocFailures rehash_failures{};
    const PushConstants push{grid_, count, tick_};
    const auto rehash = [&](core::CommandBatch& batch) {
      return batch.dispatch(rehash_, &push, sizeof(push), group_count(count),
                            max_workgroup_count_x_);
    };
    for (int pass = 0; pass < kReinsertPasses; ++pass) {
      VKC_ASSIGN(failed, dispatch_with_retry(rehash, &rehash_failures,
                                             upload_snapshot));
      if (failed == 0) {
        break;
      }
    }
    if (failed != 0) {
      return core::Status::out_of_memory(
          "VoxelHashMap::resize: rehash failed after growing (" +
          std::to_string(failed) + " of " + std::to_string(count) +
          " blocks; lock=" + std::to_string(rehash_failures.lock) +
          " chain=" + std::to_string(rehash_failures.chain) +
          " table=" + std::to_string(rehash_failures.table) + ")");
    }
    // The rehash drew nothing from the heap, so init_table's "all free" heap
    // still lists the preserved indices; rebuild it to hold only the genuinely
    // free ones so a future allocation never hands out a live block.
    return rebuild_heap_excluding(active);
  };
  if (core::Status st = grow(); !st.ok()) {
    commit(old, old_grid);  // roll back to the untouched live map
    heap_free_ = old_heap_free;
    return st;
  }
  return {};
}

core::Result<std::vector<BlockStamp>> VoxelHashMap::read_block_stamps() const {
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::read_block_stamps: moved-from map");
  }
  std::vector<BlockStamp> out(stamps_.size() / sizeof(BlockStamp));
  core::CommandBatch batch(*device_, *allocator_);
  VKC_TRY(batch.readback(stamps_, 0, stamps_.size(), out.data()));
  VKC_TRY(batch.submit());
  return out;
}

core::Result<std::vector<HashEntry>> VoxelHashMap::read_entries() {
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::read_entries: moved-from map");
  }
  const std::uint32_t total = total_entries();
  std::vector<HashEntry> entries(total);
  core::CommandBatch batch(*device_, *allocator_);
  VKC_TRY(batch.readback(entries_, 0, VkDeviceSize(total) * sizeof(HashEntry),
                         entries.data()));
  VKC_TRY(batch.submit());
  return entries;
}

core::Result<float> VoxelHashMap::load_factor() const {
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::load_factor: moved-from map");
  }
  // num_blocks > 0 by VoxelGridParams::validate (bucket_size >= 2,
  // num_buckets > 0, and their product is num_blocks).
  return 1.0f -
         static_cast<float>(heap_free_) / static_cast<float>(grid_.num_blocks);
}

core::Result<HashDiagnostics> VoxelHashMap::diagnostics() {
  if (!valid()) {
    return core::Status::invalid_argument(
        "VoxelHashMap::diagnostics: moved-from map");
  }
  // The table and the device's own heap counter in one batch -- not the
  // host copy load_factor() reads, so this is what can catch that copy stale.
  std::vector<HashEntry> entries(total_entries());
  std::uint32_t heap_free = 0;
  core::CommandBatch batch(*device_, *allocator_);
  VKC_TRY(batch.readback(entries_, 0,
                         VkDeviceSize(entries.size()) * sizeof(HashEntry),
                         entries.data()));
  VKC_TRY(batch.readback(heap_counter_, 0, sizeof(heap_free), &heap_free));
  VKC_TRY(batch.submit());

  const int num_buckets = grid_.num_buckets;
  const int bucket_size = grid_.bucket_size;
  const int total_slots = static_cast<int>(total_entries());

  HashDiagnostics diag;
  diag.heap_free_count = static_cast<std::int32_t>(heap_free);
  diag.total_blocks = grid_.num_blocks;

  // One pass per bucket: count active primary slots, then walk the collision
  // chain from the anchor (last slot of the bucket) counting its length + the
  // active overflow slots on it. Host port of computeDiagnostics.
  // TODO(volume): a GPU-side scan is a perf follow-up for very large tables.
  for (int bucket = 0; bucket < num_buckets; ++bucket) {
    const int start = bucket * bucket_size;
    for (int i = 0; i < bucket_size; ++i) {
      const int ptr = entries[start + i].ptr;
      if (ptr != kFreeEntry && ptr != kLockEntry) {
        ++diag.active_count;
      }
    }
    const int anchor = (bucket + 1) * bucket_size - 1;
    int chain_length = 0;
    int curr = anchor;
    for (int hop = 0; hop < grid_.max_chain; ++hop) {
      const int off = entries[curr].offset;
      if (off == kNoOffset) {
        break;
      }
      // offset is relative to the anchor and may be negative; wrap into range.
      const long long raw = static_cast<long long>(anchor) + off;
      const int next =
          static_cast<int>(((raw % total_slots) + total_slots) % total_slots);
      ++chain_length;
      const int ptr = entries[next].ptr;
      if (ptr != kFreeEntry && ptr != kLockEntry) {
        ++diag.overflow_count;
      }
      curr = next;
    }
    diag.max_chain_length = std::max(diag.max_chain_length, chain_length);
  }

  if (total_slots > 0) {
    diag.load_factor =
        static_cast<float>(diag.active_count) / static_cast<float>(total_slots);
  }
  if (diag.total_blocks > 0) {
    diag.heap_utilization = 1.0f - static_cast<float>(heap_free) /
                                       static_cast<float>(diag.total_blocks);
  }
  return diag;
}

}  // namespace volumetric_kit::recon::volume
