// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/volume/voxel_hash_map.hpp"

#include <algorithm>
#include <cstring>
#include <vector>

#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/shader.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "hash_allocate_coords_comp.spv.hpp"
#include "hash_compact_comp.spv.hpp"
#include "hash_delete_coords_comp.spv.hpp"
#include "hash_init_comp.spv.hpp"

namespace volumetric_kit::recon::volume {
namespace {

// Local group size, matching `layout(local_size_x = 256)` in every kernel.
constexpr std::uint32_t kLocalSize = 256;

// The push-constant block every kernel shares: the grid shape plus one
// kernel-specific argument (mirrors `PushConstants` in hash_common.glsl).
struct PushConstants {
  VoxelGridParams grid;
  std::uint32_t arg;
};

std::uint32_t group_count(std::uint32_t items) {
  return (items + kLocalSize - 1) / kLocalSize;
}

// `count` storage-buffer bindings at 0..count-1, all compute-stage.
std::vector<VkDescriptorSetLayoutBinding> storage_bindings(
    std::uint32_t count) {
  std::vector<VkDescriptorSetLayoutBinding> bindings(count);
  for (std::uint32_t i = 0; i < count; ++i) {
    bindings[i].binding = i;
    bindings[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    bindings[i].descriptorCount = 1;
    bindings[i].stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  }
  return bindings;
}

// Build a compute pipeline from embedded SPIR-V + a descriptor-set layout, with
// a single PushConstants range. The shader module is transient (the pipeline
// does not retain it).
Result<ComputePipeline> make_pipeline(VkDevice device, const unsigned char* spv,
                                      std::size_t spv_size,
                                      VkDescriptorSetLayout layout) {
  VR_ASSIGN(ShaderModule module,
            ShaderModule::create(
                device, reinterpret_cast<const std::uint32_t*>(spv), spv_size));
  VkPushConstantRange push{};
  push.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push.offset = 0;
  push.size = sizeof(PushConstants);

  ComputePipelineDesc desc;
  desc.shader = &module;
  desc.set_layouts = &layout;
  desc.set_layout_count = 1;
  desc.push_ranges = &push;
  desc.push_range_count = 1;
  return ComputePipeline::create(device, desc);
}

// Record + submit one 1-D dispatch: bind, push, dispatch, then a memory barrier
// that makes this kernel's SSBO writes available and visible to (a) the next
// dispatch's shader reads/writes of the same persistent buffers and (b) a host
// read of the mapped results. Each kernel runs as its own one-shot submission
// (submit_single_time fully fence-waits it), and a fence orders execution but
// is NOT a memory dependency -- so this barrier, not the fence, is what carries
// cross-dispatch visibility (init -> allocate, allocate -> compact). Cheap: one
// global barrier per already-serialized dispatch.
Status dispatch(Device& device, const ComputePipeline& pipeline,
                VkDescriptorSet set, const PushConstants& push,
                std::uint32_t groups) {
  return device.submit_single_time([&](VkCommandBuffer cmd) {
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline.handle());
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                            pipeline.layout(), 0, 1, &set, 0, nullptr);
    vkCmdPushConstants(cmd, pipeline.layout(), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       sizeof(PushConstants), &push);
    vkCmdDispatch(cmd, groups, 1, 1);
    VkMemoryBarrier barrier{};
    barrier.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
    barrier.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT |
                            VK_ACCESS_SHADER_WRITE_BIT |
                            VK_ACCESS_HOST_READ_BIT;
    vkCmdPipelineBarrier(
        cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
        VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT | VK_PIPELINE_STAGE_HOST_BIT, 0, 1,
        &barrier, 0, nullptr, 0, nullptr);
  });
}

// A host-visible, host-mapped storage buffer of the given byte size.
Result<Buffer> storage_buffer(Allocator& allocator, VkDeviceSize bytes,
                              HostAccess access = HostAccess::Random) {
  BufferDesc desc;
  desc.size = bytes;
  desc.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
  desc.memory = MemoryUsage::HostVisible;
  desc.mapped = true;
  desc.host_access = access;
  return allocator.create_buffer(desc);
}

}  // namespace

Result<VoxelHashMap> VoxelHashMap::create(Device& device, Allocator& allocator,
                                          const VoxelGridParams& grid) {
  // Validate the full grid contract -- positivity AND the product invariants
  // (num_blocks == bucket_size*num_buckets, voxels_per_block == block_size^3)
  // that the buffer sizing and the block-pointer math below rely on.
  // VoxelGridParams::validate is the single source of truth for a usable grid.
  VR_TRY(grid.validate());

  const VkDevice dev = device.handle();

  VoxelHashMap map;
  map.device_ = &device;
  map.allocator_ = &allocator;
  map.grid_ = grid;

  const std::uint32_t total_entries = map.total_entries();
  const auto num_blocks = static_cast<std::uint32_t>(grid.num_blocks);
  const auto num_buckets = static_cast<std::uint32_t>(grid.num_buckets);

  // Persistent buffers (host-visible for this slice; device-local + staging is
  // a follow-up perf pass -- see the header TODO).
  VR_ASSIGN(map.entries_,
            storage_buffer(allocator,
                           VkDeviceSize(total_entries) * sizeof(HashEntry)));
  VR_ASSIGN(map.heap_, storage_buffer(allocator, VkDeviceSize(num_blocks) *
                                                     sizeof(std::uint32_t)));
  VR_ASSIGN(map.heap_counter_,
            storage_buffer(allocator, sizeof(std::uint32_t)));
  VR_ASSIGN(map.bucket_mutex_,
            storage_buffer(allocator,
                           VkDeviceSize(num_buckets) * sizeof(std::int32_t)));
  // Persistent scratch: allocate fail-counts (4 uints) and the compaction
  // output (num_blocks blocks) + its counter. Fixed size, re-zeroed per call
  // rather than re-allocated.
  VR_ASSIGN(map.fail_counts_,
            storage_buffer(allocator, 4 * sizeof(std::uint32_t)));
  VR_ASSIGN(map.compacted_, storage_buffer(allocator, VkDeviceSize(num_blocks) *
                                                          sizeof(BlockIndex)));
  VR_ASSIGN(map.active_count_,
            storage_buffer(allocator, sizeof(std::uint32_t)));

  // One layout + pipeline per kernel (bindings match each shader's set 0).
  const auto init_b = storage_bindings(4);
  VR_ASSIGN(map.init_layout_,
            DescriptorSetLayout::create(
                dev, init_b.data(), static_cast<std::uint32_t>(init_b.size())));
  const auto alloc_b = storage_bindings(6);
  VR_ASSIGN(
      map.allocate_layout_,
      DescriptorSetLayout::create(dev, alloc_b.data(),
                                  static_cast<std::uint32_t>(alloc_b.size())));
  const auto compact_b = storage_bindings(3);
  VR_ASSIGN(
      map.compact_layout_,
      DescriptorSetLayout::create(
          dev, compact_b.data(), static_cast<std::uint32_t>(compact_b.size())));
  const auto delete_b = storage_bindings(6);
  VR_ASSIGN(
      map.delete_layout_,
      DescriptorSetLayout::create(
          dev, delete_b.data(), static_cast<std::uint32_t>(delete_b.size())));

  VR_ASSIGN(map.init_pipeline_, make_pipeline(dev, vr_hash_init_comp_spv,
                                              vr_hash_init_comp_spv_size,
                                              map.init_layout_.handle()));
  VR_ASSIGN(map.allocate_pipeline_,
            make_pipeline(dev, vr_hash_allocate_coords_comp_spv,
                          vr_hash_allocate_coords_comp_spv_size,
                          map.allocate_layout_.handle()));
  VR_ASSIGN(map.compact_pipeline_, make_pipeline(dev, vr_hash_compact_comp_spv,
                                                 vr_hash_compact_comp_spv_size,
                                                 map.compact_layout_.handle()));
  VR_ASSIGN(map.delete_pipeline_,
            make_pipeline(dev, vr_hash_delete_coords_comp_spv,
                          vr_hash_delete_coords_comp_spv_size,
                          map.delete_layout_.handle()));

  // Pool: one set per kernel, sized to the exact descriptor total.
  VkDescriptorPoolSize pool_size{};
  pool_size.type = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
  pool_size.descriptorCount = static_cast<std::uint32_t>(
      init_b.size() + alloc_b.size() + compact_b.size() + delete_b.size());
  VR_ASSIGN(map.pool_, DescriptorPool::create(dev, &pool_size, 1, 4));
  VR_ASSIGN(map.init_set_, map.pool_.allocate(map.init_layout_.handle()));
  VR_ASSIGN(map.allocate_set_,
            map.pool_.allocate(map.allocate_layout_.handle()));
  VR_ASSIGN(map.compact_set_, map.pool_.allocate(map.compact_layout_.handle()));
  VR_ASSIGN(map.delete_set_, map.pool_.allocate(map.delete_layout_.handle()));

  // Bind every persistent buffer once. Bindings 0-3 are identical across the
  // init and allocate sets; allocate additionally uses binding 5 (fail-counts)
  // and, per call, binding 4 (coords). Compact uses entries + output + count.
  const VkBuffer entries = map.entries_.handle();
  const VkBuffer heap = map.heap_.handle();
  const VkBuffer counter = map.heap_counter_.handle();
  const VkBuffer mutex = map.bucket_mutex_.handle();
  for (const DescriptorSet* set :
       {&map.init_set_, &map.allocate_set_, &map.delete_set_}) {
    set->write_storage_buffer(0, entries, 0, VK_WHOLE_SIZE);
    set->write_storage_buffer(1, heap, 0, VK_WHOLE_SIZE);
    set->write_storage_buffer(2, counter, 0, VK_WHOLE_SIZE);
    set->write_storage_buffer(3, mutex, 0, VK_WHOLE_SIZE);
  }
  // allocate + delete share the persistent fail-counts buffer at binding 5 --
  // they never run in the same dispatch, and each re-zeroes it before use.
  map.allocate_set_.write_storage_buffer(5, map.fail_counts_.handle(), 0,
                                         VK_WHOLE_SIZE);
  map.delete_set_.write_storage_buffer(5, map.fail_counts_.handle(), 0,
                                       VK_WHOLE_SIZE);
  map.compact_set_.write_storage_buffer(0, entries, 0, VK_WHOLE_SIZE);
  map.compact_set_.write_storage_buffer(1, map.compacted_.handle(), 0,
                                        VK_WHOLE_SIZE);
  map.compact_set_.write_storage_buffer(2, map.active_count_.handle(), 0,
                                        VK_WHOLE_SIZE);

  VR_TRY(map.init_table());
  return map;
}

std::uint32_t VoxelHashMap::total_entries() const noexcept {
  return static_cast<std::uint32_t>(grid_.num_buckets) *
         static_cast<std::uint32_t>(grid_.bucket_size);
}

Status VoxelHashMap::init_table() {
  const std::uint32_t widest =
      std::max({total_entries(), static_cast<std::uint32_t>(grid_.num_blocks),
                static_cast<std::uint32_t>(grid_.num_buckets)});
  const PushConstants push{grid_, 0};
  return dispatch(*device_, init_pipeline_, init_set_.handle(), push,
                  group_count(widest));
}

Result<std::uint32_t> VoxelHashMap::allocate(const BlockIndex* coords,
                                             std::uint32_t count) {
  if (!valid()) {
    return Status::invalid_argument("VoxelHashMap::allocate: moved-from map");
  }
  if (count == 0) {
    return std::uint32_t{0};
  }
  if (coords == nullptr) {
    return Status::invalid_argument("VoxelHashMap::allocate: coords is null");
  }

  // Coords are genuinely per-call (variable count), so this buffer is
  // transient; fail_counts_ is persistent and just re-zeroed here.
  VR_ASSIGN(
      Buffer coords_buf,
      storage_buffer(*allocator_, VkDeviceSize(count) * sizeof(BlockIndex),
                     HostAccess::SequentialWrite));
  std::memcpy(coords_buf.mapped(), coords,
              static_cast<std::size_t>(count) * sizeof(BlockIndex));

  // fail_counts_[4]: [0]=total, [1]=lock, [2]=chain, [3]=heap. Zeroed each
  // call.
  std::memset(fail_counts_.mapped(), 0, 4 * sizeof(std::uint32_t));
  allocate_set_.write_storage_buffer(4, coords_buf.handle(), 0, VK_WHOLE_SIZE);

  const PushConstants push{grid_, count};
  VR_TRY(dispatch(*device_, allocate_pipeline_, allocate_set_.handle(), push,
                  group_count(count)));

  std::uint32_t failures = 0;
  std::memcpy(&failures, fail_counts_.mapped(), sizeof(std::uint32_t));
  // TODO(volume): on non-zero failures, grow the table (resize/rehash) and
  // retry the failed coords -- lands with the resize slice.
  return failures;
}

Result<std::uint32_t> VoxelHashMap::remove(const BlockIndex* coords,
                                           std::uint32_t count) {
  if (!valid()) {
    return Status::invalid_argument("VoxelHashMap::remove: moved-from map");
  }
  if (count == 0) {
    return std::uint32_t{0};
  }
  if (coords == nullptr) {
    return Status::invalid_argument("VoxelHashMap::remove: coords is null");
  }

  VR_ASSIGN(
      Buffer coords_buf,
      storage_buffer(*allocator_, VkDeviceSize(count) * sizeof(BlockIndex),
                     HostAccess::SequentialWrite));
  std::memcpy(coords_buf.mapped(), coords,
              static_cast<std::size_t>(count) * sizeof(BlockIndex));

  // Shares the persistent fail_counts_ buffer with allocate (never concurrent);
  // the delete kernel writes only [0]. Re-zeroed each call.
  std::memset(fail_counts_.mapped(), 0, 4 * sizeof(std::uint32_t));
  delete_set_.write_storage_buffer(4, coords_buf.handle(), 0, VK_WHOLE_SIZE);

  const PushConstants push{grid_, count};
  VR_TRY(dispatch(*device_, delete_pipeline_, delete_set_.handle(), push,
                  group_count(count)));

  std::uint32_t failures = 0;
  std::memcpy(&failures, fail_counts_.mapped(), sizeof(std::uint32_t));
  return failures;
}

Result<std::vector<BlockIndex>> VoxelHashMap::compact_active_blocks() {
  if (!valid()) {
    return Status::invalid_argument(
        "VoxelHashMap::compact_active_blocks: moved-from map");
  }
  // The active set is at most num_blocks entries; the persistent output buffer
  // is sized to that upper bound, so no grow/retry is needed for this slice.
  const auto capacity = static_cast<std::uint32_t>(grid_.num_blocks);
  std::memset(active_count_.mapped(), 0, sizeof(std::uint32_t));

  const PushConstants push{grid_, capacity};
  VR_TRY(dispatch(*device_, compact_pipeline_, compact_set_.handle(), push,
                  group_count(total_entries())));

  std::uint32_t count = 0;
  std::memcpy(&count, active_count_.mapped(), sizeof(std::uint32_t));
  count = std::min(count, capacity);
  std::vector<BlockIndex> active(count);
  if (count > 0) {
    std::memcpy(active.data(), compacted_.mapped(),
                static_cast<std::size_t>(count) * sizeof(BlockIndex));
  }
  return active;
}

Status VoxelHashMap::clear() {
  if (!valid()) {
    return Status::invalid_argument("VoxelHashMap::clear: moved-from map");
  }
  return init_table();
}

Result<std::vector<HashEntry>> VoxelHashMap::read_entries() {
  if (!valid()) {
    return Status::invalid_argument(
        "VoxelHashMap::read_entries: moved-from map");
  }
  const std::uint32_t total = total_entries();
  std::vector<HashEntry> entries(total);
  std::memcpy(entries.data(), entries_.mapped(),
              static_cast<std::size_t>(total) * sizeof(HashEntry));
  return entries;
}

}  // namespace volumetric_kit::recon::volume
