// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "dct_transform.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <string>

#include "dct_tables.hpp"
#include "volumetric_kit/recon/core/command_batch.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "dct_forward_comp.spv.hpp"
#include "dct_inverse_comp.spv.hpp"
#include "dct_observed_comp.spv.hpp"

namespace volumetric_kit::recon::codec::detail {
namespace {

// Mirrors `PushConstants` in dct_common.glsl. All 4-byte scalars, so scalar
// layout puts each at its host offset; a drift is a compile error here, not a
// kernel reading one field as another.
struct PushConstants {
  std::uint32_t block_base;
  std::uint32_t num_blocks;
  std::uint32_t coefficient_count;
  float trunc_dist;
  float observed_weight;
  float decoded_weight;
  std::int32_t num_buckets;
  std::int32_t bucket_size;
  std::int32_t max_chain;
  std::int32_t max_quantized;
  std::uint32_t tick;  // the map's tick, which the inverse stamps blocks with
};
static_assert(sizeof(PushConstants) == 44, "PushConstants must be 44 bytes");
static_assert(offsetof(PushConstants, block_base) == 0, "layout drift");
static_assert(offsetof(PushConstants, num_blocks) == 4, "layout drift");
static_assert(offsetof(PushConstants, coefficient_count) == 8, "layout drift");
static_assert(offsetof(PushConstants, trunc_dist) == 12, "layout drift");
static_assert(offsetof(PushConstants, observed_weight) == 16, "layout drift");
static_assert(offsetof(PushConstants, decoded_weight) == 20, "layout drift");
static_assert(offsetof(PushConstants, num_buckets) == 24, "layout drift");
static_assert(offsetof(PushConstants, bucket_size) == 28, "layout drift");
static_assert(offsetof(PushConstants, max_chain) == 32, "layout drift");
static_assert(offsetof(PushConstants, max_quantized) == 36, "layout drift");
static_assert(offsetof(PushConstants, tick) == 40, "layout drift");

// The kernels' lane-to-line mapping is written for this edge (kEdge in
// dct_common.glsl), which is why a grid with another block size is refused.
static_assert(kBlockSize == 8, "dct_common.glsl's kEdge is 8");

// Mirrors the `Tables` buffer in dct_common.glsl.
struct Tables {
  float basis[kBasisSize];
  std::uint32_t zigzag[kVoxelsPerBlock];
};
static_assert(sizeof(Tables) == kBasisSize * sizeof(float) +
                                    kVoxelsPerBlock * sizeof(std::uint32_t),
              "Tables layout drift");

// Mirrors the counter buffer in dct_common.glsl. Only the observed pass uses
// the second word; the transform directions read back the first alone.
struct Counts {
  std::uint32_t rejected = 0;
  std::uint32_t observed = 0;
};
static_assert(sizeof(Counts) == 8, "Counts layout drift");
static_assert(offsetof(Counts, observed) == 4, "Counts layout drift");

// The set-0 bindings of both kernels, mirroring the VR_DCT_BINDING_* defines in
// dct_common.glsl -- the compute core is explicit, not reflected (2026-07-05).
enum Binding : std::uint32_t {
  kBindingBlocks = 0,
  kBindingTsdf = 1,
  kBindingWeight = 2,
  kBindingTables = 3,
  kBindingCoefficients = 4,
  kBindingMasks = 5,
  kBindingEntries = 6,
  kBindingRejected = 7,
  kBindingStamps = 8,
  kBindingQuantization = 9,
  kBindingCount = 10,
};

Status fail(const char* op, const std::string& why) {
  return Status::invalid_argument(std::string("DctTransform::") + op + ": " +
                                  why);
}

// The device's coefficients are two to a word, each entry starting a word of
// its own (coefficient_words in dct_common.glsl), so an odd K pads each entry
// by one; the host's are K to an entry.
std::size_t padded_count(std::uint32_t k) {
  return (std::size_t(k) + 1) / 2 * 2;
}

}  // namespace

Result<DctTransform> DctTransform::create(Device& device, Allocator& allocator,
                                          const DctTransformConfig& config) {
  DctTransform t;
  t.device_ = &device;
  t.allocator_ = &allocator;

  VkPushConstantRange push_range{};
  push_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push_range.offset = 0;
  push_range.size = sizeof(PushConstants);
  KernelSetBuilder kb(device);
  VR_TRY(kb.add(t.forward_kernel_, "codec_dct_forward", vr_dct_forward_comp_spv,
                vr_dct_forward_comp_spv_size, kBindingCount, &push_range));
  VR_TRY(kb.add(t.inverse_kernel_, "codec_dct_inverse", vr_dct_inverse_comp_spv,
                vr_dct_inverse_comp_spv_size, kBindingCount, &push_range));
  VR_TRY(kb.add(t.observed_kernel_, "codec_dct_observed",
                vr_dct_observed_comp_spv, vr_dct_observed_comp_spv_size,
                kBindingCount, &push_range));
  VR_ASSIGN(t.pool_, kb.build());

  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  t.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  t.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;
  // One workgroup per block, so the device's group-count ceiling is a ceiling
  // on blocks per dispatch. Room0 alone (~107 k blocks) passes the 65535 floor
  // Vulkan guarantees, so a longer list is batched in run(), not refused.
  t.blocks_per_dispatch_ =
      config.max_blocks_per_dispatch == 0
          ? t.max_workgroup_count_x_
          : std::min(config.max_blocks_per_dispatch, t.max_workgroup_count_x_);

  // The tables are the same for every call, so they are uploaded once and
  // bound once.
  Tables tables{};
  const std::array<float, kBasisSize> basis = dct_basis<float>();
  const std::array<std::uint32_t, kVoxelsPerBlock> zigzag = zigzag_order();
  std::copy(basis.begin(), basis.end(), tables.basis);
  std::copy(zigzag.begin(), zigzag.end(), tables.zigzag);
  VR_ASSIGN(t.tables_, device_storage_buffer(allocator, sizeof(tables)));
  VR_ASSIGN(t.rejected_, device_storage_buffer(allocator, sizeof(Counts)));
  VR_ASSIGN(t.quantization_steps_,
            device_storage_buffer(allocator, kVoxelsPerBlock * sizeof(float)));
  CommandBatch batch(device, allocator);
  VR_TRY(batch.upload(t.tables_, 0, &tables, sizeof(tables)));
  VR_TRY(batch.submit());
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(t.tables_.handle()),
                         "codec.dct_tables");
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(t.rejected_.handle()),
                         "codec.rejected");
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(t.quantization_steps_.handle()),
                         "codec.quantization_steps");
  for (ComputeKernel* kernel :
       {&t.forward_kernel_, &t.inverse_kernel_, &t.observed_kernel_}) {
    kernel->set.write_storage_buffer(kBindingTables, t.tables_.handle(), 0,
                                     VK_WHOLE_SIZE);
    kernel->set.write_storage_buffer(
        kBindingQuantization, t.quantization_steps_.handle(), 0, VK_WHOLE_SIZE);
    kernel->set.write_storage_buffer(kBindingRejected, t.rejected_.handle(), 0,
                                     VK_WHOLE_SIZE);
  }
  return t;
}

Result<DctTransform::GridViews> DctTransform::check_inputs(
    const char* op, const volume::VoxelBlockGrid& grid,
    const volume::BlockList& blocks, const CodecParams& params) const {
  if (!valid()) {
    return fail(op, "moved-from transform");
  }
  VR_TRY(params.validate());
  if (!grid.valid()) {
    return fail(op, "moved-from grid");
  }
  const volume::VoxelGridParams& gp = grid.grid();
  if (gp.block_size != kBlockSize) {
    return fail(op, "the codec transforms blocks of edge " +
                        std::to_string(kBlockSize) +
                        " only, and this grid's block_size is " +
                        std::to_string(gp.block_size));
  }
  if (!std::isfinite(gp.trunc_dist) || !(gp.trunc_dist > 0.0f)) {
    return fail(op, "the grid's trunc_dist must be finite and positive");
  }
  GridViews views;
  VR_ASSIGN(views.tsdf, grid.attribute("tsdf"));
  VR_ASSIGN(views.weight, grid.attribute("weight"));
  if (views.tsdf.element_size != sizeof(float) ||
      views.weight.element_size != sizeof(float)) {
    return fail(op, "the grid's tsdf and weight must be 4-byte floats");
  }
  // Whether each entry is a live block is the kernels' to answer (see
  // block_is_live), so the host takes only the O(1) half.
  VR_TRY(grid.check_block_list(blocks,
                               (std::string("DctTransform::") + op).c_str()));
  return views;
}

Status DctTransform::record(CommandBatch& batch, ComputeKernel& kernel,
                            const volume::VoxelBlockGrid& grid,
                            const GridViews& views, VkBuffer list,
                            std::uint32_t count, const CodecParams& params,
                            VkBuffer coefficients, VkBuffer masks,
                            VkDeviceSize masks_bytes, GpuStageScope* stage) {
  // Another tier sized this one (and every resize doubles it), so it is bound
  // at its real size and range-checked, as the mesher binds it.
  const VkDeviceSize entries_bytes = grid.map().entries_buffer_size();
  VR_TRY(check_storage_buffer_range("DctTransform: the hash entries",
                                    entries_bytes, max_storage_buffer_range_));
  kernel.set.write_storage_buffer(
      kBindingBlocks, list, 0,
      VkDeviceSize(count) * sizeof(volume::BlockIndex));
  kernel.set.write_storage_buffer(kBindingTsdf, views.tsdf.buffer->handle(), 0,
                                  VK_WHOLE_SIZE);
  kernel.set.write_storage_buffer(kBindingWeight, views.weight.buffer->handle(),
                                  0, VK_WHOLE_SIZE);
  if (coefficients != VK_NULL_HANDLE) {
    const VkDeviceSize coeff_bytes = VkDeviceSize(count) *
                                     padded_count(params.coefficient_count) *
                                     sizeof(std::int16_t);
    kernel.set.write_storage_buffer(kBindingCoefficients, coefficients, 0,
                                    coeff_bytes);
  }
  kernel.set.write_storage_buffer(kBindingMasks, masks, 0, masks_bytes);
  kernel.set.write_storage_buffer(kBindingEntries, grid.map().entries_buffer(),
                                  0, entries_bytes);
  kernel.set.write_storage_buffer(
      kBindingStamps, grid.map().stamps_buffer().handle(), 0, VK_WHOLE_SIZE);

  const volume::VoxelGridParams& gp = grid.grid();
  PushConstants push{};
  push.num_blocks = count;
  push.coefficient_count = params.coefficient_count;
  push.trunc_dist = gp.trunc_dist;
  if (coefficients != VK_NULL_HANDLE) {
    // The same float products validate() checked, staged before any dispatch
    // reads them.
    std::array<float, kVoxelsPerBlock> steps{};
    for (std::size_t i = 0; i < steps.size(); ++i) {
      steps[i] = params.quantization_scale * params.quantization_weights[i];
    }
    VR_TRY(batch.upload(quantization_steps_, 0, steps.data(), sizeof(steps)));
  }
  push.observed_weight = volume::kObservedWeight;
  push.decoded_weight = kDecodedWeight;
  push.num_buckets = gp.num_buckets;
  push.bucket_size = gp.bucket_size;
  push.max_chain = gp.max_chain;
  push.max_quantized = kMaxQuantizedMagnitude;
  push.tick = grid.map().tick();
  VR_TRY(batch.fill(rejected_, 0, sizeof(Counts), 0u));
  // The batch barriers every dispatch, so the batches see each other's writes
  // -- and they touch disjoint list entries.
  for (std::uint32_t base = 0; base < count; base += blocks_per_dispatch_) {
    push.block_base = base;
    const std::uint32_t groups = std::min(blocks_per_dispatch_, count - base);
    VR_TRY(batch.dispatch(kernel, &push, sizeof(push), groups,
                          max_workgroup_count_x_, stage));
  }
  return {};
}

Status DctTransform::check_rejected(const char* op, std::uint32_t rejected,
                                    std::uint32_t count) {
  if (rejected != 0) {
    return fail(op, std::to_string(rejected) + " of " + std::to_string(count) +
                        " block list entries name no block of this grid (each "
                        "coord must be in its hash table); they were neither "
                        "read nor written");
  }
  return {};
}

Status DctTransform::ensure_scratch(Buffer& buffer, VkDeviceSize bytes,
                                    const char* name) {
  return ensure_device_scratch(*device_, *allocator_, buffer, bytes,
                               max_storage_buffer_range_, name);
}

Status DctTransform::upload_list(CommandBatch& batch,
                                 const volume::BlockList& blocks) {
  const VkDeviceSize list_bytes =
      VkDeviceSize(blocks.count) * sizeof(volume::BlockIndex);
  VR_TRY(ensure_scratch(block_list_, list_bytes, "codec.block_list"));
  return batch.upload(block_list_, 0, blocks.blocks, list_bytes);
}

Result<std::vector<volume::BlockIndex>> DctTransform::observed(
    const volume::VoxelBlockGrid& grid, const volume::DeviceBlockList& list,
    GpuStageScope* stage) {
  VR_ASSIGN(GridViews views,
            check_inputs("observed", grid, volume::BlockList{}, CodecParams{}));
  VR_TRY(grid.map().check_device_block_list(list, "DctTransform::observed"));
  std::vector<volume::BlockIndex> out;
  if (list.count == 0) {
    last_observed_.count = 0;
    return out;
  }
  const VkDeviceSize list_bytes =
      VkDeviceSize(list.count) * sizeof(volume::BlockIndex);
  VR_TRY(ensure_scratch(observed_blocks_, list_bytes, "codec.observed_blocks"));
  // Read a predicted prefix beside the count, rather than pay a second fence
  // on every call: the last observed count plus 25%, capped by the current
  // input count, or the whole input when there is no last count (the first
  // call, or one after an empty result). Only an outgrown prefix costs
  // another transfer, just as collect_compacted does.
  const std::uint32_t last = last_observed_.count;
  const std::uint32_t guess =
      last == 0 ? list.count
                : static_cast<std::uint32_t>(std::min<std::uint64_t>(
                      list.count, std::uint64_t(last) + last / 4));
  out.resize(guess);
  Counts counts;
  CommandBatch batch(*device_, *allocator_);
  VR_TRY(record(batch, observed_kernel_, grid, views, list.buffer->handle(),
                list.count, CodecParams{}, VK_NULL_HANDLE,
                observed_blocks_.handle(), list_bytes, stage));
  VR_TRY(batch.readback(rejected_, 0, sizeof(counts), &counts));
  VR_TRY(batch.readback(observed_blocks_, 0,
                        VkDeviceSize(guess) * sizeof(volume::BlockIndex),
                        out.data()));
  VR_TRY(batch.submit());
  VR_TRY(check_rejected("observed", counts.rejected, list.count));
  if (counts.observed > list.count) {
    return fail("observed", "the device observed count exceeds the input list");
  }
  out.resize(counts.observed);
  if (counts.observed > guess) {
    CommandBatch tail(*device_, *allocator_);
    VR_TRY(tail.readback(
        observed_blocks_, VkDeviceSize(guess) * sizeof(volume::BlockIndex),
        VkDeviceSize(counts.observed - guess) * sizeof(volume::BlockIndex),
        out.data() + guess));
    VR_TRY(tail.submit());
  }
  last_observed_.count = counts.observed;
  return out;
}

Result<ResidentBlocks> DctTransform::record_forward(
    CommandBatch& batch, const volume::VoxelBlockGrid& grid,
    const volume::BlockList& blocks, const CodecParams& params,
    std::uint32_t& rejected, GpuStageScope* stage) {
  rejected = 0;
  VR_ASSIGN(GridViews views, check_inputs("forward", grid, blocks, params));
  ResidentBlocks out;
  out.coefficient_count = params.coefficient_count;
  if (blocks.count == 0) {
    return out;
  }
  const VkDeviceSize coeff_bytes = VkDeviceSize(blocks.count) *
                                   padded_count(params.coefficient_count) *
                                   sizeof(std::int16_t);
  const VkDeviceSize mask_bytes =
      VkDeviceSize(blocks.count) * kMaskWordsPerBlock * sizeof(std::uint32_t);
  VR_TRY(ensure_scratch(coefficients_, coeff_bytes, "codec.coefficients"));
  VR_TRY(ensure_scratch(masks_, mask_bytes, "codec.masks"));
  VR_TRY(upload_list(batch, blocks));
  VR_TRY(record(batch, forward_kernel_, grid, views, block_list_.handle(),
                blocks.count, params, coefficients_.handle(), masks_.handle(),
                mask_bytes, stage));
  VR_TRY(batch.readback(rejected_, 0, sizeof(rejected), &rejected));
  out.list = &block_list_;
  out.masks = &masks_;
  out.coefficients = &coefficients_;
  out.count = blocks.count;
  return out;
}

Status DctTransform::forward(const volume::VoxelBlockGrid& grid,
                             const volume::BlockList& blocks,
                             const CodecParams& params, DctBlocks& out,
                             GpuStageScope* stage) {
  out.params = CodecParams{};
  out.trunc_dist = 0.0f;
  out.coefficients.clear();
  out.masks.clear();
  const std::uint32_t k = params.coefficient_count;
  const std::size_t padded = padded_count(k);
  std::uint32_t rejected = 0;
  CommandBatch batch(*device_, *allocator_);
  VR_ASSIGN(const ResidentBlocks resident,
            record_forward(batch, grid, blocks, params, rejected, stage));
  if (resident.count != 0) {
    std::vector<std::int16_t> coefficients(std::size_t(resident.count) *
                                           padded);
    std::vector<std::uint32_t> masks(std::size_t(resident.count) *
                                     kMaskWordsPerBlock);
    VR_TRY(batch.readback(coefficients_, 0,
                          coefficients.size() * sizeof(std::int16_t),
                          coefficients.data()));
    VR_TRY(batch.readback(masks_, 0, masks.size() * sizeof(std::uint32_t),
                          masks.data()));
    VR_TRY(batch.submit());
    VR_TRY(check_rejected("forward", rejected, resident.count));
    if (padded != k) {
      // Drop each entry's pad, sliding the rows down in place: std::copy
      // runs forwards, which a destination before its source allows.
      for (std::size_t i = 1; i < resident.count; ++i) {
        const auto row = coefficients.begin() + std::ptrdiff_t(i * padded);
        std::copy(row, row + k, coefficients.begin() + std::ptrdiff_t(i * k));
      }
      coefficients.resize(std::size_t(resident.count) * k);
    }
    out.coefficients = std::move(coefficients);
    out.masks = std::move(masks);
  }
  out.params = params;
  out.trunc_dist = grid.grid().trunc_dist;
  return {};
}

Status DctTransform::inverse(volume::VoxelBlockGrid& grid,
                             const volume::BlockList& blocks,
                             const DctBlocks& in, GpuStageScope* stage) {
  VR_ASSIGN(GridViews views, check_inputs("inverse", grid, blocks, in.params));
  if (in.trunc_dist != grid.grid().trunc_dist) {
    return fail("inverse", "the coefficients were normalized by trunc_dist " +
                               std::to_string(in.trunc_dist) +
                               ", but this grid's is " +
                               std::to_string(grid.grid().trunc_dist));
  }
  const std::uint32_t k = in.params.coefficient_count;
  const std::size_t coeff_count = std::size_t(blocks.count) * k;
  const std::size_t mask_count = std::size_t(blocks.count) * kMaskWordsPerBlock;
  if (in.coefficients.size() != coeff_count) {
    return fail("inverse", "expected " + std::to_string(coeff_count) +
                               " coefficients for the list, got " +
                               std::to_string(in.coefficients.size()));
  }
  if (in.masks.size() != mask_count) {
    return fail("inverse", "expected " + std::to_string(mask_count) +
                               " mask words for the list, got " +
                               std::to_string(in.masks.size()));
  }
  if (blocks.count == 0) {
    return {};
  }

  const std::size_t padded = padded_count(k);
  const VkDeviceSize coeff_bytes =
      VkDeviceSize(blocks.count) * padded * sizeof(std::int16_t);
  const VkDeviceSize mask_bytes =
      VkDeviceSize(mask_count) * sizeof(std::uint32_t);
  VR_TRY(ensure_scratch(coefficients_, coeff_bytes, "codec.coefficients"));
  VR_TRY(ensure_scratch(masks_, mask_bytes, "codec.masks"));

  std::uint32_t rejected = 0;
  CommandBatch batch(*device_, *allocator_);
  VR_TRY(upload_list(batch, blocks));
  if (padded == k) {
    VR_TRY(batch.upload(coefficients_, 0, in.coefficients.data(), coeff_bytes));
  } else {
    // Each entry padded to a whole word, as the kernel reads it.
    VR_ASSIGN(void* staged,
              batch.reserve_upload(coefficients_, 0, coeff_bytes));
    auto* rows = static_cast<std::int16_t*>(staged);
    for (std::size_t i = 0; i < blocks.count; ++i) {
      std::copy_n(in.coefficients.begin() + std::ptrdiff_t(i * k), k,
                  rows + i * padded);
      rows[i * padded + k] = 0;
    }
  }
  VR_TRY(batch.upload(masks_, 0, in.masks.data(), mask_bytes));
  // The call is one tick, which every block it changes is stamped with.
  grid.map().advance_tick();
  VR_TRY(record(batch, inverse_kernel_, grid, views, block_list_.handle(),
                blocks.count, in.params, coefficients_.handle(),
                masks_.handle(), mask_bytes, stage));
  VR_TRY(batch.readback(rejected_, 0, sizeof(rejected), &rejected));
  VR_TRY(batch.submit());
  return check_rejected("inverse", rejected, blocks.count);
}

}  // namespace volumetric_kit::recon::codec::detail
