// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "dct_transform.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <string>

#include "dct_tables.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "dct_forward_comp.spv.hpp"
#include "dct_inverse_comp.spv.hpp"

namespace volumetric_kit::recon::codec::detail {
namespace {

// Mirrors `PushConstants` in dct_common.glsl. All 4-byte scalars, so scalar
// layout puts each at its host offset; a drift is a compile error here, not a
// kernel reading the steps as the block count.
struct PushConstants {
  std::uint32_t block_base;
  std::uint32_t num_blocks;
  std::uint32_t coefficient_count;
  float trunc_dist;
  float dc_step;
  float ac_step;
  float observed_weight;
  float decoded_weight;
  std::int32_t num_buckets;
  std::int32_t bucket_size;
  std::int32_t max_chain;
  std::int32_t max_quantized;
  std::uint32_t tick;  // the map's tick, which the inverse stamps blocks with
};
static_assert(sizeof(PushConstants) == 52, "PushConstants must be 52 bytes");
static_assert(offsetof(PushConstants, block_base) == 0, "layout drift");
static_assert(offsetof(PushConstants, num_blocks) == 4, "layout drift");
static_assert(offsetof(PushConstants, coefficient_count) == 8, "layout drift");
static_assert(offsetof(PushConstants, trunc_dist) == 12, "layout drift");
static_assert(offsetof(PushConstants, dc_step) == 16, "layout drift");
static_assert(offsetof(PushConstants, ac_step) == 20, "layout drift");
static_assert(offsetof(PushConstants, observed_weight) == 24, "layout drift");
static_assert(offsetof(PushConstants, decoded_weight) == 28, "layout drift");
static_assert(offsetof(PushConstants, num_buckets) == 32, "layout drift");
static_assert(offsetof(PushConstants, bucket_size) == 36, "layout drift");
static_assert(offsetof(PushConstants, max_chain) == 40, "layout drift");
static_assert(offsetof(PushConstants, max_quantized) == 44, "layout drift");
static_assert(offsetof(PushConstants, tick) == 48, "layout drift");

// The kernels' lane-to-line mapping is written for this edge (kEdge in
// dct_common.glsl), which is why a grid with another block size is refused.
static_assert(kBlockSize == 8, "dct_common.glsl's kEdge is 8");

// Mirrors the `Tables` buffer in dct_common.glsl.
struct Tables {
  float basis[kBasisSize];
  std::uint32_t zigzag[kVoxelsPerBlock];
};
static_assert(sizeof(Tables) == kBasisSize * sizeof(float) +
                                    kVoxelsPerBlock * sizeof(std::uint32_t),
              "Tables layout drift");

// The set-0 bindings of both kernels, mirroring the VR_DCT_BINDING_* defines in
// dct_common.glsl -- the compute core is explicit, not reflected (2026-07-05).
enum Binding : std::uint32_t {
  kBindingBlocks = 0,
  kBindingTsdf = 1,
  kBindingWeight = 2,
  kBindingTables = 3,
  kBindingCoefficients = 4,
  kBindingMasks = 5,
  kBindingEntries = 6,
  kBindingRejected = 7,
  kBindingStamps = 8,
  kBindingCount = 9,
};

Status fail(const char* op, const std::string& why) {
  return Status::invalid_argument(std::string("DctTransform::") + op + ": " +
                                  why);
}

}  // namespace

Result<DctTransform> DctTransform::create(Device& device, Allocator& allocator,
                                          const DctTransformConfig& config) {
  DctTransform t;
  t.device_ = &device;
  t.allocator_ = &allocator;

  VkPushConstantRange push_range{};
  push_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push_range.offset = 0;
  push_range.size = sizeof(PushConstants);
  KernelSetBuilder kb(device);
  VR_TRY(kb.add(t.forward_kernel_, "codec_dct_forward", vr_dct_forward_comp_spv,
                vr_dct_forward_comp_spv_size, kBindingCount, &push_range));
  VR_TRY(kb.add(t.inverse_kernel_, "codec_dct_inverse", vr_dct_inverse_comp_spv,
                vr_dct_inverse_comp_spv_size, kBindingCount, &push_range));
  VR_ASSIGN(t.pool_, kb.build());

  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  t.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  t.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;
  // One workgroup per block, so the device's group-count ceiling is a ceiling
  // on blocks per dispatch. Room0 alone (~107 k blocks) passes the 65535 floor
  // Vulkan guarantees, so a longer list is batched in run(), not refused.
  t.blocks_per_dispatch_ =
      config.max_blocks_per_dispatch == 0
          ? t.max_workgroup_count_x_
          : std::min(config.max_blocks_per_dispatch, t.max_workgroup_count_x_);

  // The tables are the same for every call, so they are uploaded once and
  // bound once.
  Tables tables{};
  const std::array<float, kBasisSize> basis = dct_basis<float>();
  const std::array<std::uint32_t, kVoxelsPerBlock> zigzag = zigzag_order();
  std::copy(basis.begin(), basis.end(), tables.basis);
  std::copy(zigzag.begin(), zigzag.end(), tables.zigzag);
  VR_ASSIGN(t.tables_,
            upload_storage_buffer(allocator, &tables, sizeof(tables)));
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(t.tables_.handle()),
                         "codec.dct_tables");
  t.forward_kernel_.set.write_storage_buffer(kBindingTables, t.tables_.handle(),
                                             0, VK_WHOLE_SIZE);
  t.inverse_kernel_.set.write_storage_buffer(kBindingTables, t.tables_.handle(),
                                             0, VK_WHOLE_SIZE);

  VR_ASSIGN(t.rejected_, storage_buffer(allocator, sizeof(std::uint32_t)));
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(t.rejected_.handle()),
                         "codec.rejected");
  t.forward_kernel_.set.write_storage_buffer(
      kBindingRejected, t.rejected_.handle(), 0, VK_WHOLE_SIZE);
  t.inverse_kernel_.set.write_storage_buffer(
      kBindingRejected, t.rejected_.handle(), 0, VK_WHOLE_SIZE);
  return t;
}

Result<DctTransform::GridViews> DctTransform::check_inputs(
    const char* op, const volume::VoxelBlockGrid& grid,
    const volume::BlockList& blocks, const CodecParams& params) const {
  if (!valid()) {
    return fail(op, "moved-from transform");
  }
  VR_TRY(params.validate());
  if (!grid.valid()) {
    return fail(op, "moved-from grid");
  }
  const volume::VoxelGridParams& gp = grid.grid();
  if (gp.block_size != kBlockSize) {
    return fail(op, "the codec transforms blocks of edge " +
                        std::to_string(kBlockSize) +
                        " only, and this grid's block_size is " +
                        std::to_string(gp.block_size));
  }
  if (!std::isfinite(gp.trunc_dist) || !(gp.trunc_dist > 0.0f)) {
    return fail(op, "the grid's trunc_dist must be finite and positive");
  }
  GridViews views;
  VR_ASSIGN(views.tsdf, grid.attribute("tsdf"));
  VR_ASSIGN(views.weight, grid.attribute("weight"));
  if (views.tsdf.element_size != sizeof(float) ||
      views.weight.element_size != sizeof(float)) {
    return fail(op, "the grid's tsdf and weight must be 4-byte floats");
  }
  // Whether each entry is a live block is the kernels' to answer (see
  // block_is_live), so the host takes only the O(1) half.
  VR_TRY(grid.check_block_list(blocks,
                               (std::string("DctTransform::") + op).c_str()));
  return views;
}

Status DctTransform::run(const char* op, ComputeKernel& kernel,
                         const volume::VoxelBlockGrid& grid,
                         const GridViews& views,
                         const volume::BlockList& blocks,
                         const CodecParams& params, const Buffer& coefficients,
                         const Buffer& masks, GpuStageScope* stage) {
  const VkDeviceSize list_bytes =
      VkDeviceSize(blocks.count) * sizeof(volume::BlockIndex);
  VR_TRY(check_storage_buffer_range("DctTransform: the block list", list_bytes,
                                    max_storage_buffer_range_));
  // Another tier sized this one (and every resize doubles it), so it is bound
  // at its real size and range-checked, as the mesher binds it.
  const VkDeviceSize entries_bytes = grid.map().entries_buffer_size();
  VR_TRY(check_storage_buffer_range("DctTransform: the hash entries",
                                    entries_bytes, max_storage_buffer_range_));
  VR_ASSIGN(Buffer list_buf,
            upload_storage_buffer(*allocator_, blocks.blocks, list_bytes));
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(list_buf.handle()),
                           "codec.block_list");

  kernel.set.write_storage_buffer(kBindingBlocks, list_buf.handle(), 0,
                                  VK_WHOLE_SIZE);
  kernel.set.write_storage_buffer(kBindingTsdf, views.tsdf.buffer->handle(), 0,
                                  VK_WHOLE_SIZE);
  kernel.set.write_storage_buffer(kBindingWeight, views.weight.buffer->handle(),
                                  0, VK_WHOLE_SIZE);
  kernel.set.write_storage_buffer(kBindingCoefficients, coefficients.handle(),
                                  0, VK_WHOLE_SIZE);
  kernel.set.write_storage_buffer(kBindingMasks, masks.handle(), 0,
                                  VK_WHOLE_SIZE);
  kernel.set.write_storage_buffer(kBindingEntries, grid.map().entries_buffer(),
                                  0, entries_bytes);
  kernel.set.write_storage_buffer(
      kBindingStamps, grid.map().stamps_buffer().handle(), 0, VK_WHOLE_SIZE);

  const volume::VoxelGridParams& gp = grid.grid();
  PushConstants push{};
  push.num_blocks = blocks.count;
  push.coefficient_count = params.coefficient_count;
  push.trunc_dist = gp.trunc_dist;
  push.dc_step = params.dc_step;
  push.ac_step = params.ac_step;
  push.observed_weight = volume::kObservedWeight;
  push.decoded_weight = kDecodedWeight;
  push.num_buckets = gp.num_buckets;
  push.bucket_size = gp.bucket_size;
  push.max_chain = gp.max_chain;
  push.max_quantized = kMaxQuantizedMagnitude;
  push.tick = grid.map().tick();
  std::memset(rejected_.mapped(), 0, sizeof(std::uint32_t));
  // Each dispatch is its own fence-waited submission whose barrier makes its
  // writes visible to the next and to the host, so the batches need no
  // ordering beyond running in turn -- and they touch disjoint list entries.
  for (std::uint32_t base = 0; base < blocks.count;
       base += blocks_per_dispatch_) {
    push.block_base = base;
    const std::uint32_t groups =
        std::min(blocks_per_dispatch_, blocks.count - base);
    VR_TRY(dispatch(*device_, kernel, &push, sizeof(push), groups,
                    max_workgroup_count_x_, stage));
  }
  std::uint32_t rejected = 0;
  std::memcpy(&rejected, rejected_.mapped(), sizeof(rejected));
  if (rejected != 0) {
    return fail(op, std::to_string(rejected) + " of " +
                        std::to_string(blocks.count) +
                        " block list entries are not live blocks of this grid "
                        "(each coord must resolve to its ptr in the hash "
                        "table); they were neither read nor written");
  }
  return {};
}

Status DctTransform::forward(const volume::VoxelBlockGrid& grid,
                             const volume::BlockList& blocks,
                             const CodecParams& params, DctBlocks& out,
                             GpuStageScope* stage) {
  out.params = CodecParams{};
  out.trunc_dist = 0.0f;
  out.coefficients.clear();
  out.masks.clear();
  VR_ASSIGN(GridViews views, check_inputs("forward", grid, blocks, params));

  const std::size_t coeff_count =
      std::size_t(blocks.count) * params.coefficient_count;
  const std::size_t mask_count = std::size_t(blocks.count) * kMaskWordsPerBlock;
  if (blocks.count != 0) {
    const VkDeviceSize coeff_bytes =
        VkDeviceSize(coeff_count) * sizeof(std::int32_t);
    const VkDeviceSize mask_bytes =
        VkDeviceSize(mask_count) * sizeof(std::uint32_t);
    VR_TRY(check_storage_buffer_range("DctTransform: the coefficients",
                                      coeff_bytes, max_storage_buffer_range_));
    VR_TRY(check_storage_buffer_range("DctTransform: the masks", mask_bytes,
                                      max_storage_buffer_range_));
    VR_ASSIGN(Buffer coeff_buf, storage_buffer(*allocator_, coeff_bytes));
    VR_ASSIGN(Buffer mask_buf, storage_buffer(*allocator_, mask_bytes));
    device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                             debug_object_handle(coeff_buf.handle()),
                             "codec.coefficients");
    device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                             debug_object_handle(mask_buf.handle()),
                             "codec.masks");

    VR_TRY(run("forward", forward_kernel_, grid, views, blocks, params,
               coeff_buf, mask_buf, stage));

    out.coefficients.resize(coeff_count);
    out.masks.resize(mask_count);
    std::memcpy(out.coefficients.data(), coeff_buf.mapped(), coeff_bytes);
    std::memcpy(out.masks.data(), mask_buf.mapped(), mask_bytes);
  }
  out.params = params;
  out.trunc_dist = grid.grid().trunc_dist;
  return {};
}

Status DctTransform::inverse(volume::VoxelBlockGrid& grid,
                             const volume::BlockList& blocks,
                             const DctBlocks& in, GpuStageScope* stage) {
  VR_ASSIGN(GridViews views, check_inputs("inverse", grid, blocks, in.params));
  if (in.trunc_dist != grid.grid().trunc_dist) {
    return fail("inverse", "the coefficients were normalized by trunc_dist " +
                               std::to_string(in.trunc_dist) +
                               ", but this grid's is " +
                               std::to_string(grid.grid().trunc_dist));
  }
  const std::size_t coeff_count =
      std::size_t(blocks.count) * in.params.coefficient_count;
  const std::size_t mask_count = std::size_t(blocks.count) * kMaskWordsPerBlock;
  if (in.coefficients.size() != coeff_count) {
    return fail("inverse", "expected " + std::to_string(coeff_count) +
                               " coefficients for the list, got " +
                               std::to_string(in.coefficients.size()));
  }
  if (in.masks.size() != mask_count) {
    return fail("inverse", "expected " + std::to_string(mask_count) +
                               " mask words for the list, got " +
                               std::to_string(in.masks.size()));
  }
  if (blocks.count == 0) {
    return {};
  }

  const VkDeviceSize coeff_bytes =
      VkDeviceSize(coeff_count) * sizeof(std::int32_t);
  const VkDeviceSize mask_bytes =
      VkDeviceSize(mask_count) * sizeof(std::uint32_t);
  VR_TRY(check_storage_buffer_range("DctTransform: the coefficients",
                                    coeff_bytes, max_storage_buffer_range_));
  VR_TRY(check_storage_buffer_range("DctTransform: the masks", mask_bytes,
                                    max_storage_buffer_range_));
  VR_ASSIGN(
      Buffer coeff_buf,
      upload_storage_buffer(*allocator_, in.coefficients.data(), coeff_bytes));
  VR_ASSIGN(Buffer mask_buf,
            upload_storage_buffer(*allocator_, in.masks.data(), mask_bytes));
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(coeff_buf.handle()),
                           "codec.coefficients");
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(mask_buf.handle()),
                           "codec.masks");

  // The call is one tick, which every block it writes is stamped changed with.
  grid.map().advance_tick();
  return run("inverse", inverse_kernel_, grid, views, blocks, in.params,
             coeff_buf, mask_buf, stage);
}

}  // namespace volumetric_kit::recon::codec::detail
