// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "dct_transform.hpp"

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <string>

#include "dct_tables.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "dct_forward_comp.spv.hpp"
#include "dct_inverse_comp.spv.hpp"

namespace volumetric_kit::recon::codec::detail {
namespace {

// Mirrors `PushConstants` in dct_common.glsl. All 4-byte scalars, so scalar
// layout puts each at its host offset; a drift is a compile error here, not a
// kernel reading the steps as the block count.
struct PushConstants {
  std::uint32_t block_base;
  std::uint32_t num_blocks;
  std::uint32_t coefficient_count;
  float trunc_dist;
  float dc_step;
  float ac_step;
  float observed_weight;
  std::uint32_t reserved;
};
static_assert(sizeof(PushConstants) == 32, "PushConstants must be 32 bytes");
static_assert(offsetof(PushConstants, block_base) == 0, "layout drift");
static_assert(offsetof(PushConstants, num_blocks) == 4, "layout drift");
static_assert(offsetof(PushConstants, coefficient_count) == 8, "layout drift");
static_assert(offsetof(PushConstants, trunc_dist) == 12, "layout drift");
static_assert(offsetof(PushConstants, dc_step) == 16, "layout drift");
static_assert(offsetof(PushConstants, ac_step) == 20, "layout drift");
static_assert(offsetof(PushConstants, observed_weight) == 24, "layout drift");

// Mirrors the `Tables` buffer in dct_common.glsl (binding 3).
struct Tables {
  float basis[64];
  std::uint32_t zigzag[kVoxelsPerBlock];
};
static_assert(sizeof(Tables) == 64 * 4 + 512 * 4, "Tables layout drift");

// Bindings 0..5 of both kernels: blocks, tsdf, weight, tables, coefficients,
// masks. One literal for both, and it must match every `binding = N` in the
// two .comp files -- the compute core is explicit, not reflected (2026-07-05).
constexpr std::uint32_t kBindings = 6;

Status fail(const char* op, const std::string& why) {
  return Status::invalid_argument(std::string("DctTransform::") + op + ": " +
                                  why);
}

}  // namespace

Result<DctTransform> DctTransform::create(Device& device, Allocator& allocator,
                                          const DctTransformConfig& config) {
  DctTransform t;
  t.device_ = &device;
  t.allocator_ = &allocator;

  VkPushConstantRange push_range{};
  push_range.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push_range.offset = 0;
  push_range.size = sizeof(PushConstants);
  KernelSetBuilder kb(device);
  VR_TRY(kb.add(t.forward_kernel_, "codec_dct_forward", vr_dct_forward_comp_spv,
                vr_dct_forward_comp_spv_size, kBindings, &push_range));
  VR_TRY(kb.add(t.inverse_kernel_, "codec_dct_inverse", vr_dct_inverse_comp_spv,
                vr_dct_inverse_comp_spv_size, kBindings, &push_range));
  VR_ASSIGN(t.pool_, kb.build());

  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  t.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  t.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;
  // One workgroup per block, so the device's group-count ceiling is a ceiling
  // on blocks per dispatch. Room0 alone (~107 k blocks) passes the 65535 floor
  // Vulkan guarantees, so a longer list is batched in run(), not refused.
  t.blocks_per_dispatch_ =
      config.max_blocks_per_dispatch == 0
          ? t.max_workgroup_count_x_
          : std::min(config.max_blocks_per_dispatch, t.max_workgroup_count_x_);

  // The tables are the same for every call, so they are uploaded once and
  // bound once -- both kernels read them at binding 3.
  Tables tables{};
  const std::array<float, 64> basis = dct_basis<float>();
  const std::array<std::uint32_t, kVoxelsPerBlock> zigzag = zigzag_order();
  std::copy(basis.begin(), basis.end(), tables.basis);
  std::copy(zigzag.begin(), zigzag.end(), tables.zigzag);
  VR_ASSIGN(t.tables_,
            upload_storage_buffer(allocator, &tables, sizeof(tables)));
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         debug_object_handle(t.tables_.handle()),
                         "codec.dct_tables");
  t.forward_kernel_.set.write_storage_buffer(3, t.tables_.handle(), 0,
                                             VK_WHOLE_SIZE);
  t.inverse_kernel_.set.write_storage_buffer(3, t.tables_.handle(), 0,
                                             VK_WHOLE_SIZE);
  return t;
}

Status DctTransform::check_inputs(const char* op,
                                  const volume::VoxelBlockGrid& grid,
                                  const volume::BlockList& blocks,
                                  const CodecParams& params) const {
  if (!valid()) {
    return fail(op, "moved-from transform");
  }
  VR_TRY(params.validate());
  if (!grid.valid()) {
    return fail(op, "moved-from grid");
  }
  const volume::VoxelGridParams& gp = grid.grid();
  if (gp.block_size != kBlockSize) {
    return fail(op,
                "the codec transforms 8^3 blocks only, and this grid's "
                "block_size is " +
                    std::to_string(gp.block_size));
  }
  if (!std::isfinite(gp.trunc_dist) || !(gp.trunc_dist > 0.0f)) {
    return fail(op, "the grid's trunc_dist must be finite and positive");
  }
  if (blocks.count == 0) {
    return {};  // an empty list names no block, so it carries no epoch
  }
  if (blocks.blocks == nullptr) {
    return fail(op, "the block list is null with a non-zero count");
  }
  if (blocks.count > static_cast<std::uint32_t>(gp.num_blocks)) {
    return fail(op, "the block list holds more blocks than the grid's heap");
  }
  // A ptr addresses attribute storage directly and the heap is LIFO, so a list
  // compacted before a remove()/clear() names a different block through the
  // same, still in-range, ptr. The epoch is the only thing that can tell.
  if (blocks.epoch != grid.topology_epoch()) {
    return fail(op,
                "the block list was compacted at another topology epoch "
                "(rebuild it with VoxelBlockGrid::block_list)");
  }
  // The kernels index attribute storage with ptr unchecked, and the inverse
  // WRITES there, so a ptr outside the heap is an out-of-bounds device write.
  // O(count) on the host, against a dispatch that reads 4 KB per block.
  const auto heap_voxels = static_cast<std::int64_t>(gp.num_blocks) *
                           static_cast<std::int64_t>(kVoxelsPerBlock);
  for (std::uint32_t i = 0; i < blocks.count; ++i) {
    const std::int64_t ptr = blocks.blocks[i].ptr;
    if (ptr < 0 || ptr >= heap_voxels || ptr % kVoxelsPerBlock != 0) {
      return fail(op, "block list entry " + std::to_string(i) +
                          " has a ptr outside the grid's heap");
    }
  }
  return {};
}

Status DctTransform::run(const char* op, ComputeKernel& kernel,
                         const volume::VoxelBlockGrid& grid,
                         const volume::BlockList& blocks,
                         const CodecParams& params, const Buffer& coefficients,
                         const Buffer& masks) {
  VR_ASSIGN(volume::AttributeView tsdf_view, grid.attribute("tsdf"));
  VR_ASSIGN(volume::AttributeView weight_view, grid.attribute("weight"));
  if (tsdf_view.element_size != sizeof(float) ||
      weight_view.element_size != sizeof(float)) {
    return fail(op, "the grid's tsdf and weight must be 4-byte floats");
  }

  const VkDeviceSize list_bytes =
      VkDeviceSize(blocks.count) * sizeof(volume::BlockIndex);
  VR_TRY(check_storage_buffer_range("DctTransform: the block list", list_bytes,
                                    max_storage_buffer_range_));
  VR_ASSIGN(Buffer list_buf,
            upload_storage_buffer(*allocator_, blocks.blocks, list_bytes));
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(list_buf.handle()),
                           "codec.block_list");

  kernel.set.write_storage_buffer(0, list_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel.set.write_storage_buffer(1, tsdf_view.buffer->handle(), 0,
                                  VK_WHOLE_SIZE);
  kernel.set.write_storage_buffer(2, weight_view.buffer->handle(), 0,
                                  VK_WHOLE_SIZE);
  kernel.set.write_storage_buffer(4, coefficients.handle(), 0, VK_WHOLE_SIZE);
  kernel.set.write_storage_buffer(5, masks.handle(), 0, VK_WHOLE_SIZE);

  PushConstants push{};
  push.num_blocks = blocks.count;
  push.coefficient_count = params.coefficient_count;
  push.trunc_dist = grid.grid().trunc_dist;
  push.dc_step = params.dc_step;
  push.ac_step = params.ac_step;
  push.observed_weight = kObservedWeight;
  // Each dispatch is its own fence-waited submission whose barrier makes its
  // writes visible to the next and to the host, so the batches need no
  // ordering beyond running in turn -- and they touch disjoint list entries.
  for (std::uint32_t base = 0; base < blocks.count;
       base += blocks_per_dispatch_) {
    push.block_base = base;
    const std::uint32_t groups =
        std::min(blocks_per_dispatch_, blocks.count - base);
    VR_TRY(dispatch(*device_, kernel, &push, sizeof(push), groups,
                    max_workgroup_count_x_));
  }
  return {};
}

Status DctTransform::forward(const volume::VoxelBlockGrid& grid,
                             const volume::BlockList& blocks,
                             const CodecParams& params,
                             std::vector<std::int32_t>& coefficients,
                             std::vector<std::uint32_t>& masks) {
  coefficients.clear();
  masks.clear();
  VR_TRY(check_inputs("forward", grid, blocks, params));
  if (blocks.count == 0) {
    return {};
  }

  const std::size_t coeff_count =
      std::size_t(blocks.count) * params.coefficient_count;
  const std::size_t mask_count = std::size_t(blocks.count) * kMaskWordsPerBlock;
  const VkDeviceSize coeff_bytes = VkDeviceSize(coeff_count) * 4;
  const VkDeviceSize mask_bytes = VkDeviceSize(mask_count) * 4;
  VR_TRY(check_storage_buffer_range("DctTransform: the coefficients",
                                    coeff_bytes, max_storage_buffer_range_));
  VR_TRY(check_storage_buffer_range("DctTransform: the masks", mask_bytes,
                                    max_storage_buffer_range_));
  VR_ASSIGN(Buffer coeff_buf, storage_buffer(*allocator_, coeff_bytes));
  VR_ASSIGN(Buffer mask_buf, storage_buffer(*allocator_, mask_bytes));
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(coeff_buf.handle()),
                           "codec.coefficients");
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(mask_buf.handle()),
                           "codec.masks");

  VR_TRY(run("forward", forward_kernel_, grid, blocks, params, coeff_buf,
             mask_buf));

  coefficients.resize(coeff_count);
  masks.resize(mask_count);
  std::memcpy(coefficients.data(), coeff_buf.mapped(), coeff_bytes);
  std::memcpy(masks.data(), mask_buf.mapped(), mask_bytes);
  return {};
}

Status DctTransform::inverse(volume::VoxelBlockGrid& grid,
                             const volume::BlockList& blocks,
                             const CodecParams& params,
                             const std::vector<std::int32_t>& coefficients,
                             const std::vector<std::uint32_t>& masks) {
  VR_TRY(check_inputs("inverse", grid, blocks, params));
  const std::size_t coeff_count =
      std::size_t(blocks.count) * params.coefficient_count;
  const std::size_t mask_count = std::size_t(blocks.count) * kMaskWordsPerBlock;
  if (coefficients.size() != coeff_count) {
    return fail("inverse", "expected " + std::to_string(coeff_count) +
                               " coefficients for the list, got " +
                               std::to_string(coefficients.size()));
  }
  if (masks.size() != mask_count) {
    return fail("inverse", "expected " + std::to_string(mask_count) +
                               " mask words for the list, got " +
                               std::to_string(masks.size()));
  }
  if (blocks.count == 0) {
    return {};
  }

  const VkDeviceSize coeff_bytes = VkDeviceSize(coeff_count) * 4;
  const VkDeviceSize mask_bytes = VkDeviceSize(mask_count) * 4;
  VR_TRY(check_storage_buffer_range("DctTransform: the coefficients",
                                    coeff_bytes, max_storage_buffer_range_));
  VR_TRY(check_storage_buffer_range("DctTransform: the masks", mask_bytes,
                                    max_storage_buffer_range_));
  VR_ASSIGN(
      Buffer coeff_buf,
      upload_storage_buffer(*allocator_, coefficients.data(), coeff_bytes));
  VR_ASSIGN(Buffer mask_buf,
            upload_storage_buffer(*allocator_, masks.data(), mask_bytes));
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(coeff_buf.handle()),
                           "codec.coefficients");
  device_->set_object_name(VK_OBJECT_TYPE_BUFFER,
                           debug_object_handle(mask_buf.handle()),
                           "codec.masks");

  return run("inverse", inverse_kernel_, grid, blocks, params, coeff_buf,
             mask_buf);
}

}  // namespace volumetric_kit::recon::codec::detail
