// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "device_frame_reader.hpp"

#include <algorithm>
#include <cstring>
#include <string>

#include "rans_dispatch.hpp"
#include "volumetric_kit/recon/core/command_batch.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "rans_decode_comp.spv.hpp"
#include "rans_slots_comp.spv.hpp"

namespace volumetric_kit::recon::codec::detail {
namespace {

// The kernels' workgroup widths.
constexpr std::uint32_t kSlotsLanes = 256;
constexpr std::uint32_t kDecodeLanes = 1;

Status fail(const char* op, const std::string& why) {
  return Status::invalid_argument(std::string("DeviceFrameReader::") + op +
                                  ": " + why);
}

}  // namespace

Result<std::unique_ptr<DeviceFrameReader>> DeviceFrameReader::create(
    Device& device, Allocator& allocator) {
  VR_TRY(check_device_requirements(device, "DeviceFrameReader::create"));
  std::unique_ptr<DeviceFrameReader> owned(new DeviceFrameReader());
  DeviceFrameReader& r = *owned;
  r.device_ = &device;
  r.allocator_ = &allocator;
  VkPushConstantRange push{};
  push.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push.size = sizeof(RansPush);
  KernelSetBuilder kb(device);
  VR_TRY(kb.add(r.slots_kernel_, "codec_rans_slots", vr_rans_slots_comp_spv,
                vr_rans_slots_comp_spv_size, 2, &push));
  VR_TRY(kb.add(r.decode_kernel_, "codec_rans_decode", vr_rans_decode_comp_spv,
                vr_rans_decode_comp_spv_size, 7, &push));
  VR_ASSIGN(r.pool_, kb.build());
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  r.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  r.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;
  return owned;
}

Result<ResidentBlocks> DeviceFrameReader::record_decode(
    CommandBatch& batch, const ParsedFrame& frame, GpuStageScope* stage) {
  const std::uint32_t n = frame.header.block_count;
  const std::uint32_t k = frame.header.params.coefficient_count;
  const auto segments =
      static_cast<std::uint32_t>(frame.segment_lengths.size());
  // One invocation decodes a whole segment, and the frame sets its length.
  const std::uint32_t longest = std::min(n, frame.header.segment_size);
  if (longest > kMaxDeviceDecodeSegmentSize) {
    return fail("record_decode",
                "segments of " + std::to_string(longest) +
                    " blocks, past the " +
                    std::to_string(kMaxDeviceDecodeSegmentSize) +
                    " one invocation decodes within a GPU watchdog's limit");
  }
  ResidentBlocks out;
  out.coefficient_count = k;
  if (n == 0) {
    blocks_host_.clear();
    faults_host_.clear();
    segment_size_ = frame.header.segment_size;
    return out;
  }

  // Every size first, so a frame the device cannot hold grows nothing.
  const std::vector<std::uint32_t> entries = rans_table_entries(frame.tables);
  const std::uint32_t models = frame_model_count(k);
  const VkDeviceSize entry_bytes = entries.size() * sizeof(std::uint32_t);
  const VkDeviceSize slot_bytes =
      VkDeviceSize(models) * kRansScale * sizeof(std::uint32_t);
  const VkDeviceSize payload_bytes =
      (frame.payload_size + 3) & ~VkDeviceSize{3};
  const VkDeviceSize word_bytes =
      (VkDeviceSize(segments) + 1) * sizeof(std::uint32_t);
  const VkDeviceSize list_bytes = VkDeviceSize(n) * sizeof(volume::BlockIndex);
  const VkDeviceSize mask_bytes =
      VkDeviceSize(n) * kMaskWordsPerBlock * sizeof(std::uint32_t);
  const VkDeviceSize coeff_bytes =
      VkDeviceSize(n) * ((k + 1) / 2) * sizeof(std::uint32_t);
  const VkDeviceSize fault_bytes =
      VkDeviceSize(segments) * sizeof(std::uint32_t);
  struct Scratch {
    Buffer& buffer;
    VkDeviceSize bytes;
    const char* name;
  };
  const Scratch scratch[] = {
      {tables_, entry_bytes, "codec.rans_decode_tables"},
      {slots_, slot_bytes, "codec.rans_slots"},
      {payload_, payload_bytes, "codec.rans_decode_payload"},
      {segment_words_, word_bytes, "codec.rans_segment_words"},
      {list_, list_bytes, "codec.rans_decode_list"},
      {masks_, mask_bytes, "codec.rans_decode_masks"},
      {coefficients_, coeff_bytes, "codec.rans_decode_coefficients"},
      {faults_, fault_bytes, "codec.rans_faults"},
  };
  const VkDeviceSize range = max_storage_buffer_range_;
  for (const Scratch& b : scratch) {
    VR_TRY(check_storage_buffer_range(b.name, b.bytes, range));
  }
  for (const Scratch& b : scratch) {
    VR_TRY(ensure_device_scratch(*device_, *allocator_, b.buffer, b.bytes,
                                 range, b.name));
  }
  // Each segment's first 16-bit word. The lengths sum to the payload, which
  // the range check above holds under 4 GiB, so every offset fits.
  std::vector<std::uint32_t> segment_words(std::size_t(segments) + 1, 0);
  for (std::uint32_t s = 0; s < segments; ++s) {
    segment_words[s + 1] = segment_words[s] + frame.segment_lengths[s] / 2;
  }
  segment_size_ = frame.header.segment_size;
  // Overwritten by the readback.
  blocks_host_.resize(n);
  faults_host_.resize(segments);

  VR_TRY(batch.upload(tables_, 0, entries.data(), entry_bytes));
  VR_TRY(batch.upload(segment_words_, 0, segment_words.data(), word_bytes));
  VR_ASSIGN(void* staged, batch.reserve_upload(payload_, 0, payload_bytes));
  std::memcpy(staged, frame.payload, frame.payload_size);
  std::memset(static_cast<std::uint8_t*>(staged) + frame.payload_size, 0,
              payload_bytes - frame.payload_size);

  slots_kernel_.set.write_storage_buffer(0, tables_.handle(), 0, entry_bytes);
  slots_kernel_.set.write_storage_buffer(1, slots_.handle(), 0, slot_bytes);
  ComputeKernel& decode = decode_kernel_;
  decode.set.write_storage_buffer(0, slots_.handle(), 0, slot_bytes);
  decode.set.write_storage_buffer(1, payload_.handle(), 0, payload_bytes);
  decode.set.write_storage_buffer(2, segment_words_.handle(), 0, word_bytes);
  decode.set.write_storage_buffer(3, list_.handle(), 0, list_bytes);
  decode.set.write_storage_buffer(4, masks_.handle(), 0, mask_bytes);
  decode.set.write_storage_buffer(5, coefficients_.handle(), 0, coeff_bytes);
  decode.set.write_storage_buffer(6, faults_.handle(), 0, fault_bytes);

  RansPush push;
  push.num_blocks = n;
  push.coefficient_count = k;
  push.segment_size = frame.header.segment_size;
  push.segment_count = segments;
  VR_TRY(dispatch_items(batch, slots_kernel_, push,
                        std::uint64_t(models) * kRansScale, kSlotsLanes,
                        max_workgroup_count_x_, stage));
  VR_TRY(dispatch_items(batch, decode, push, segments, kDecodeLanes,
                        max_workgroup_count_x_, stage));
  VR_TRY(batch.readback(list_, 0, list_bytes, blocks_host_.data()));
  VR_TRY(batch.readback(faults_, 0, fault_bytes, faults_host_.data()));

  out.list = &list_;
  out.masks = &masks_;
  out.coefficients = &coefficients_;
  out.count = n;
  return out;
}

Status DeviceFrameReader::check() const {
  const std::size_t r = segment_size_;
  for (std::size_t s = 0; s < faults_host_.size(); ++s) {
    const std::size_t first = s * r;
    VR_TRY(check_segment(s, static_cast<SegmentFault>(faults_host_[s]),
                         s > 0 ? &blocks_host_[first - 1].coord : nullptr,
                         blocks_host_[first].coord));
  }
  return {};
}

Result<IntraFrame> DeviceFrameReader::read(const std::uint8_t* data,
                                           std::size_t size,
                                           std::uint32_t max_blocks) {
  VR_ASSIGN(const ParsedFrame parsed,
            parse_intra_frame(data, size, max_blocks));
  const std::uint32_t n = parsed.header.block_count;
  const std::uint32_t k = parsed.header.params.coefficient_count;
  const std::uint32_t words = (k + 1) / 2;
  std::vector<std::uint32_t> packed(std::size_t(n) * words);
  IntraFrame frame;
  frame.voxel_size = parsed.header.voxel_size;
  frame.blocks.trunc_dist = parsed.header.trunc_dist;
  frame.blocks.params = parsed.header.params;
  frame.blocks.masks.resize(std::size_t(n) * kMaskWordsPerBlock);
  CommandBatch batch(*device_, *allocator_);
  VR_ASSIGN(const ResidentBlocks resident, record_decode(batch, parsed));
  if (n != 0) {
    VR_TRY(batch.readback(*resident.masks, 0,
                          frame.blocks.masks.size() * sizeof(std::uint32_t),
                          frame.blocks.masks.data()));
    VR_TRY(batch.readback(*resident.coefficients, 0,
                          packed.size() * sizeof(std::uint32_t),
                          packed.data()));
    VR_TRY(batch.submit());
  }
  VR_TRY(check());
  frame.coords.reserve(n);
  for (const volume::BlockIndex& b : blocks_host_) {
    frame.coords.push_back(b.coord);
  }
  frame.blocks.coefficients.resize(std::size_t(n) * k);
  for (std::size_t i = 0; i < n; ++i) {
    for (std::uint32_t j = 0; j < k; ++j) {
      frame.blocks.coefficients[i * k + j] = static_cast<std::int16_t>(
          packed[i * words + j / 2] >> (16 * (j & 1)));
    }
  }
  return frame;
}

}  // namespace volumetric_kit::recon::codec::detail
