// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "device_frame_writer.hpp"

#include <algorithm>
#include <cstddef>
#include <limits>
#include <string>
#include <utility>

#include "rans_dispatch.hpp"
#include "volumetric_kit/core/vulkan/command_batch.hpp"
#include "volumetric_kit/core/vulkan/compute_util.hpp"
#include "volumetric_kit/core/vulkan/device.hpp"
#include "volumetric_kit/recon/core/device_requirements.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "rans_count_comp.spv.hpp"
#include "rans_encode_comp.spv.hpp"
#include "rans_gather_comp.spv.hpp"
#include "rans_ops_comp.spv.hpp"
#include "rans_scan_comp.spv.hpp"

namespace volumetric_kit::recon::codec::detail {
namespace {

// The kernels' workgroup widths.
constexpr std::uint32_t kCountLanes = 64;
constexpr std::uint32_t kOpsLanes = 64;
constexpr std::uint32_t kEncodeLanes = 32;

// The payload readback's prediction before any frame: about three times
// what room0 codes.
constexpr std::uint64_t kFirstPayloadPerBlock = 32;

core::Status fail(const char* op, const std::string& why) {
  return core::Status::invalid_argument(std::string("DeviceFrameWriter::") +
                                        op + ": " + why);
}

}  // namespace

core::Result<std::unique_ptr<DeviceFrameWriter>> DeviceFrameWriter::create(
    core::Device& device, core::Allocator& allocator) {
  VKC_TRY(check_device_requirements(device, "DeviceFrameWriter::create"));
  std::unique_ptr<DeviceFrameWriter> owned(new DeviceFrameWriter());
  DeviceFrameWriter& w = *owned;
  w.device_ = &device;
  w.allocator_ = &allocator;
  VkPushConstantRange push{};
  push.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push.size = sizeof(RansPush);
  core::KernelSetBuilder kb(device);
  VKC_TRY(kb.add(w.count_kernel_, "codec_rans_count", vr_rans_count_comp_spv,
                 vr_rans_count_comp_spv_size, 5, &push));
  VKC_TRY(kb.add(w.ops_kernel_, "codec_rans_ops", vr_rans_ops_comp_spv,
                 vr_rans_ops_comp_spv_size, 6, &push));
  VKC_TRY(kb.add(w.encode_kernel_, "codec_rans_encode", vr_rans_encode_comp_spv,
                 vr_rans_encode_comp_spv_size, 6, &push));
  VKC_TRY(kb.add(w.scan_kernel_, "codec_rans_scan", vr_rans_scan_comp_spv,
                 vr_rans_scan_comp_spv_size, 3, &push));
  VKC_TRY(kb.add(w.gather_kernel_, "codec_rans_gather", vr_rans_gather_comp_spv,
                 vr_rans_gather_comp_spv_size, 5, &push));
  VKC_ASSIGN(w.pool_, kb.build());
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  w.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  w.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;
  VKC_ASSIGN(w.failed_,
             core::device_storage_buffer(allocator, sizeof(std::uint32_t)));
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         core::debug_object_handle(w.failed_.handle()),
                         "codec.rans_failed");
  VKC_ASSIGN(w.gather_args_, core::device_storage_buffer(
                                 allocator, sizeof(VkDispatchIndirectCommand),
                                 VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT));
  device.set_object_name(VK_OBJECT_TYPE_BUFFER,
                         core::debug_object_handle(w.gather_args_.handle()),
                         "codec.rans_gather_args");
  return owned;
}

core::Status DeviceFrameWriter::record_count(core::CommandBatch& batch,
                                             const ResidentBlocks& blocks,
                                             std::uint32_t segment_size,
                                             core::GpuStageScope* stage) {
  if (segment_size == 0) {
    return fail("record_count", "segment_size must be at least 1");
  }
  const std::uint32_t n = blocks.count;
  const std::uint32_t k = blocks.coefficient_count;
  const std::uint64_t segments = frame_segment_count(n, segment_size);
  if (segments > kMaxFrameSegments) {
    return fail("record_count", "more than 2^30 - 1 segments");
  }
  segment_size_ = segment_size;
  counts_host_.assign(frame_model_base(frame_model_count(k)), 0);
  steps_host_.assign(n, 0);
  if (n == 0) return {};

  const VkDeviceSize range = max_storage_buffer_range_;
  const VkDeviceSize count_bytes = counts_host_.size() * sizeof(std::uint32_t);
  const VkDeviceSize step_bytes = steps_host_.size() * sizeof(std::uint32_t);
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, counts_,
                                      count_bytes, range, "codec.rans_counts"));
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, block_steps_,
                                      step_bytes, range,
                                      "codec.rans_block_steps"));
  VKC_TRY(batch.zero(counts_, 0, count_bytes));

  core::ComputeKernel& kernel = count_kernel_;
  kernel.set.write_storage_buffer(0, blocks.list->handle(), 0,
                                  VkDeviceSize(n) * sizeof(volume::BlockIndex));
  kernel.set.write_storage_buffer(
      1, blocks.masks->handle(), 0,
      VkDeviceSize(n) * kMaskWordsPerBlock * sizeof(std::uint32_t));
  kernel.set.write_storage_buffer(
      2, blocks.coefficients->handle(), 0,
      VkDeviceSize(n) * ((k + 1) / 2) * sizeof(std::uint32_t));
  kernel.set.write_storage_buffer(3, counts_.handle(), 0, count_bytes);
  kernel.set.write_storage_buffer(4, block_steps_.handle(), 0, step_bytes);
  RansPush push;
  push.num_blocks = n;
  push.coefficient_count = k;
  push.segment_size = segment_size;
  push.segment_count = static_cast<std::uint32_t>(segments);
  VKC_TRY(dispatch_items(batch, kernel, push, n, kCountLanes,
                         max_workgroup_count_x_, stage));
  VKC_TRY(batch.readback(counts_, 0, count_bytes, counts_host_.data()));
  return batch.readback(block_steps_, 0, step_bytes, steps_host_.data());
}

core::Result<std::vector<std::uint8_t>> DeviceFrameWriter::finish(
    const ResidentBlocks& blocks, float voxel_size, float trunc_dist,
    const CodecParams& params, core::GpuStageScope* stage) {
  VKC_TRY(params.validate());
  const std::uint32_t n = blocks.count;
  const std::uint32_t k = params.coefficient_count;
  const std::uint32_t segment_size = segment_size_;
  if (segment_size == 0 || k != blocks.coefficient_count ||
      counts_host_.size() != frame_model_base(frame_model_count(k)) ||
      steps_host_.size() != n) {
    return fail("finish", "these blocks were not the ones record_count saw");
  }
  const auto segments =
      static_cast<std::uint32_t>(frame_segment_count(n, segment_size));

  // The tables, from the device's counts through the host's normalization.
  const std::uint32_t models = frame_model_count(k);
  std::vector<std::vector<std::uint64_t>> counts(models);
  for (std::uint32_t m = 0; m < models; ++m) {
    counts[m].assign(counts_host_.begin() + frame_model_base(m),
                     counts_host_.begin() + frame_model_base(m + 1));
  }
  CodedFrame coded;
  coded.voxel_size = voxel_size;
  coded.trunc_dist = trunc_dist;
  coded.params = params;
  coded.block_count = n;
  coded.segment_size = segment_size;
  coded.tables = frame_tables(counts);
  if (n == 0) return assemble_intra_frame(coded);

  // Each symbol's coder step; frequency 0 for one never counted, which the
  // encoder refuses.
  const std::vector<std::uint32_t> entries = rans_table_entries(coded.tables);
  // The coder takes a segment's steps last first, so its blocks are laid out
  // last first, each block's steps written down from its run's end: the
  // segment's steps are one run in the order the coder takes them. Its slot
  // holds at most a word per step and the final state's two, rounded up to
  // whole 32-bit words so no two segments share one.
  std::vector<std::uint32_t> step_ends(n);
  std::vector<std::uint32_t> segment_steps(std::size_t(segments) + 1, 0);
  std::vector<std::uint32_t> slot_offsets(std::size_t(segments) + 1, 0);
  std::uint64_t step_total = 0;
  std::uint64_t slot_words16 = 0;
  for (std::uint32_t s = 0; s < segments; ++s) {
    const std::uint64_t first = std::uint64_t(s) * segment_size;
    const std::uint64_t end = std::min<std::uint64_t>(n, first + segment_size);
    segment_steps[s] = static_cast<std::uint32_t>(step_total);
    slot_offsets[s] = static_cast<std::uint32_t>(slot_words16);
    const std::uint64_t begin = step_total;
    for (std::uint64_t i = end; i-- > first;) {
      step_total += steps_host_[i];
      step_ends[i] = static_cast<std::uint32_t>(step_total);
    }
    slot_words16 += (step_total - begin + 3) & ~std::uint64_t{1};
    if (step_total * 4 > std::numeric_limits<std::uint32_t>::max() ||
        slot_words16 * 2 > std::numeric_limits<std::uint32_t>::max()) {
      return fail("finish", "the coded segments could outgrow 4 GiB");
    }
  }
  segment_steps[segments] = static_cast<std::uint32_t>(step_total);
  slot_offsets[segments] = static_cast<std::uint32_t>(slot_words16);

  const VkDeviceSize range = max_storage_buffer_range_;
  const VkDeviceSize entry_bytes = entries.size() * sizeof(std::uint32_t);
  const VkDeviceSize offset_bytes = slot_offsets.size() * sizeof(std::uint32_t);
  const VkDeviceSize slot_bytes = slot_words16 * 2;
  const VkDeviceSize step_end_bytes = VkDeviceSize(n) * sizeof(std::uint32_t);
  const VkDeviceSize step_bytes = step_total * sizeof(std::uint32_t);
  const VkDeviceSize length_bytes =
      VkDeviceSize(segments) * sizeof(std::uint32_t);
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, tables_,
                                      entry_bytes, range, "codec.rans_tables"));
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, step_ends_,
                                      step_end_bytes, range,
                                      "codec.rans_step_ends"));
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, steps_, step_bytes,
                                      range, "codec.rans_steps"));
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, segment_steps_,
                                      offset_bytes, range,
                                      "codec.rans_segment_steps"));
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, slot_offsets_,
                                      offset_bytes, range,
                                      "codec.rans_slot_offsets"));
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, slots_, slot_bytes,
                                      range, "codec.rans_slots"));
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, lengths_,
                                      length_bytes, range,
                                      "codec.rans_lengths"));
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, payload_offsets_,
                                      offset_bytes, range,
                                      "codec.rans_payload_offsets"));
  VKC_TRY(core::ensure_device_scratch(*device_, *allocator_, payload_,
                                      slot_bytes, range, "codec.rans_payload"));

  core::CommandBatch batch(*device_, *allocator_);
  VKC_TRY(batch.upload(tables_, 0, entries.data(), entry_bytes));
  VKC_TRY(batch.upload(step_ends_, 0, step_ends.data(), step_end_bytes));
  VKC_TRY(batch.upload(segment_steps_, 0, segment_steps.data(), offset_bytes));
  VKC_TRY(batch.upload(slot_offsets_, 0, slot_offsets.data(), offset_bytes));
  VKC_TRY(batch.zero(failed_, 0, sizeof(std::uint32_t)));

  core::ComputeKernel& ops = ops_kernel_;
  ops.set.write_storage_buffer(0, blocks.list->handle(), 0,
                               VkDeviceSize(n) * sizeof(volume::BlockIndex));
  ops.set.write_storage_buffer(
      1, blocks.masks->handle(), 0,
      VkDeviceSize(n) * kMaskWordsPerBlock * sizeof(std::uint32_t));
  ops.set.write_storage_buffer(
      2, blocks.coefficients->handle(), 0,
      VkDeviceSize(n) * ((k + 1) / 2) * sizeof(std::uint32_t));
  ops.set.write_storage_buffer(3, tables_.handle(), 0, entry_bytes);
  ops.set.write_storage_buffer(4, step_ends_.handle(), 0, step_end_bytes);
  ops.set.write_storage_buffer(5, steps_.handle(), 0, step_bytes);
  core::ComputeKernel& encode = encode_kernel_;
  encode.set.write_storage_buffer(0, steps_.handle(), 0, step_bytes);
  encode.set.write_storage_buffer(1, segment_steps_.handle(), 0, offset_bytes);
  encode.set.write_storage_buffer(2, slot_offsets_.handle(), 0, offset_bytes);
  encode.set.write_storage_buffer(3, slots_.handle(), 0, slot_bytes);
  encode.set.write_storage_buffer(4, lengths_.handle(), 0, length_bytes);
  encode.set.write_storage_buffer(5, failed_.handle(), 0,
                                  sizeof(std::uint32_t));
  scan_kernel_.set.write_storage_buffer(0, lengths_.handle(), 0, length_bytes);
  scan_kernel_.set.write_storage_buffer(1, payload_offsets_.handle(), 0,
                                        offset_bytes);
  scan_kernel_.set.write_storage_buffer(2, gather_args_.handle(), 0,
                                        sizeof(VkDispatchIndirectCommand));
  core::ComputeKernel& gather = gather_kernel_;
  gather.set.write_storage_buffer(0, slot_offsets_.handle(), 0, offset_bytes);
  gather.set.write_storage_buffer(1, slots_.handle(), 0, slot_bytes);
  gather.set.write_storage_buffer(2, lengths_.handle(), 0, length_bytes);
  gather.set.write_storage_buffer(3, payload_offsets_.handle(), 0,
                                  offset_bytes);
  gather.set.write_storage_buffer(4, payload_.handle(), 0, slot_bytes);

  RansPush push;
  push.num_blocks = n;
  push.coefficient_count = k;
  push.segment_size = segment_size;
  push.segment_count = segments;
  VKC_TRY(dispatch_items(batch, ops, push, n, kOpsLanes, max_workgroup_count_x_,
                         stage));
  VKC_TRY(dispatch_items(batch, encode, push, segments, kEncodeLanes,
                         max_workgroup_count_x_, stage));
  VKC_TRY(batch.dispatch(scan_kernel_, &push, sizeof(push), 1,
                         max_workgroup_count_x_, stage));
  VKC_TRY(batch.dispatch_indirect(gather, &push, sizeof(push), gather_args_, 0,
                                  stage));

  // Read the payload's likely size with the lengths, and any rest after.
  std::vector<std::uint32_t> lengths(segments);
  std::uint32_t failed = 0;
  const std::uint64_t per_block =
      payload_per_block_ != 0 ? payload_per_block_ : kFirstPayloadPerBlock;
  const VkDeviceSize guess = std::min<VkDeviceSize>(
      slot_bytes, (per_block * n + 3) & ~VkDeviceSize{3});
  std::vector<std::uint8_t> payload(static_cast<std::size_t>(guess));
  VKC_TRY(batch.readback(lengths_, 0, length_bytes, lengths.data()));
  VKC_TRY(batch.readback(failed_, 0, sizeof(failed), &failed));
  VKC_TRY(batch.readback(payload_, 0, guess, payload.data()));
  VKC_TRY(batch.submit());
  if (failed != 0) {
    return core::Status::io_error(
        "DeviceFrameWriter::finish: a table refused a symbol it was counted "
        "from, or a segment outgrew its slot");
  }
  std::uint64_t total = 0;
  for (std::uint32_t length : lengths) total += length;
  if (total > slot_bytes) {
    return core::Status::io_error(
        "DeviceFrameWriter::finish: the segments outgrew their slots");
  }
  if (total > guess) {
    payload.resize(static_cast<std::size_t>((total + 3) & ~std::uint64_t{3}));
    core::CommandBatch tail(*device_, *allocator_);
    VKC_TRY(tail.readback(payload_, guess,
                          ((total + 3) & ~std::uint64_t{3}) - guess,
                          payload.data() + guess));
    VKC_TRY(tail.submit());
  }
  payload.resize(static_cast<std::size_t>(total));
  payload_per_block_ = static_cast<std::uint32_t>((total + total / 4) / n + 1);
  coded.segment_lengths = std::move(lengths);
  coded.payload = std::move(payload);
  return assemble_intra_frame(coded);
}

}  // namespace volumetric_kit::recon::codec::detail
