#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Tao Jin
#
# Regenerates the committed HEVC clips with the ffmpeg CLI (built with
# libx265). All are Annex B, headers repeated on every key frame and an access
# unit delimiter before each frame, BT.709 limited range.
#
#   tests/data/hevc/patches_256x144.h265   8 frames (IPPP) of 8x2 solid
#       patches that shift one patch left per frame; the test recomputes each
#       patch's value (patch, patch_y, patch_u and patch_v in
#       tests/sensor_video_hevc_test.cpp).
#   tests/data/hevc/cropped_240x128.h265   the same frames, their display
#       window moved 16 right and 16 down (a conformance window; only the
#       SPS differs).
#   tests/data/hevc/fallback_256x144.h265  the same 8 frames with B-frames,
#       then 2 frames of 4:0:0 grey, which no hardware back end decodes: Auto
#       moves to software with pictures still held for display.
#   src/.../sensor/video/probe_clip.inc    one mid-grey key frame, the clip
#       HevcDecoder::hardware_backends decodes on each back end.
#
# 256x144: NVDEC's smallest HEVC picture is 144x144.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
x265="keyint=4:min-keyint=4:bframes=0:scenecut=0:open-gop=0:repeat-headers=1"
x265+=":aud=1:info=0:qp=4:colorprim=bt709:transfer=bt709:colormatrix=bt709"
x265+=":range=limited:log-level=error"

# Patch p = (column + frame + 3 * row) mod 8, over 32x72 luma patches:
# Y = 40 + 24p, U = 64 + 16 (3p mod 8), V = 64 + 16 (5p mod 8). The chroma
# planes are half size, so their patches are 16x36.
p_luma='mod(floor(X/32)+N+3*floor(Y/72),8)'
p_chroma='mod(floor(X/16)+N+3*floor(Y/36),8)'
ffmpeg -hide_banner -loglevel error -y -f lavfi \
  -i "nullsrc=s=256x144:r=30,format=yuv420p,geq=lum='40+24*${p_luma}':cb='64+16*mod(3*${p_chroma},8)':cr='64+16*mod(5*${p_chroma},8)'" \
  -frames:v 8 -c:v libx265 -x265-params "$x265" -f hevc \
  "$root/tests/data/hevc/patches_256x144.h265"

ffmpeg -hide_banner -loglevel error -y \
  -i "$root/tests/data/hevc/patches_256x144.h265" -c copy \
  -bsf:v hevc_metadata=crop_left=16:crop_top=16 -f hevc \
  "$root/tests/data/hevc/cropped_240x128.h265"

tmp="$(mktemp)"
grey="$(mktemp)"
trap 'rm -f "$tmp" "$grey"' EXIT
ffmpeg -hide_banner -loglevel error -y -f lavfi \
  -i "nullsrc=s=256x144:r=30,format=yuv420p,geq=lum='40+24*${p_luma}':cb='64+16*mod(3*${p_chroma},8)':cr='64+16*mod(5*${p_chroma},8)'" \
  -frames:v 8 -c:v libx265 \
  -x265-params "${x265/keyint=4:min-keyint=4:bframes=0/keyint=8:min-keyint=8:bframes=3:b-adapt=0}" \
  -f hevc "$tmp"
ffmpeg -hide_banner -loglevel error -y -f lavfi \
  -i "color=c=0x808080:s=256x144:r=30,format=gray" \
  -frames:v 2 -c:v libx265 -x265-params "$x265" -f hevc "$grey"
cat "$tmp" "$grey" >"$root/tests/data/hevc/fallback_256x144.h265"

ffmpeg -hide_banner -loglevel error -y -f lavfi \
  -i "color=c=0x808080:s=256x144:r=30,format=yuv420p" \
  -frames:v 1 -c:v libx265 -x265-params "$x265" -f hevc "$tmp"
{
  echo "// SPDX-License-Identifier: MIT"
  echo "// Copyright (c) 2026 Tao Jin"
  echo "//"
  echo "// Generated by tools/make_hevc_fixtures.sh: one 256x144 mid-grey HEVC"
  echo "// key frame, Annex B. Do not edit."
  od -An -v -tx1 "$tmp" | tr -s ' \n' '\n\n' | awk 'NF {
    printf "%s0x%s,", (n % 12 ? " " : (n ? "\n" : "")), $1; n++
  } END { print "" }'
} >"$root/src/volumetric_kit/recon/sensor/video/probe_clip.inc"
