// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/mesh/marching_cubes.hpp"

#include <algorithm>
#include <chrono>
#include <cstddef>
#include <cstring>
#include <numeric>
#include <string>
#include <utility>
#include <vector>

#include "volumetric_kit/recon/core/allocator.hpp"
#include "volumetric_kit/recon/core/compute_kernel.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"
#include "volumetric_kit/recon/mesh/marching_cubes_tables.hpp"
#include "volumetric_kit/recon/volume/hash.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "marching_cubes_comp.spv.hpp"
#include "marching_cubes_sparse_comp.spv.hpp"

namespace volumetric_kit::recon::mesh {
namespace {

// Local group size, matching `layout(local_size_x = 256)` in the kernel.
constexpr std::uint32_t kLocalSize = 256;

// Worst-case triangles a single marching-cubes cell can emit (5 per the table).
constexpr std::uint64_t kMaxTrisPerCell = 5;

// The draw command is an ABI across three languages now -- the host resets it
// and reads it back, the GLSL kernel aliases its first field as the append
// atomic (`buffer DrawCommand { uint index_count; ... }`, offset 0 under scalar
// block layout), and the renderer's vkCmdDrawIndexedIndirect consumes the whole
// struct. Vulkan fixes this layout, but the raw 4-byte write in
// clamp_indirect_to_arena() and the two 20-byte reads assume it here, and this
// file already pins every other cross-language struct the same way.
static_assert(sizeof(VkDrawIndexedIndirectCommand) == 20,
              "VkDrawIndexedIndirectCommand must be 20 bytes -- the kernel's "
              "DrawCommand mirror and the host reset/readback assume it");
static_assert(offsetof(VkDrawIndexedIndirectCommand, indexCount) == 0,
              "indexCount must be field 0 -- the kernel's append atomic bumps "
              "it through a storage binding at offset 0, and the host clamps "
              "it with a 4-byte write to the start of the buffer");

// Triangles per active block the first extract plans for, before any
// measurement is available. A real scan measures 54-68 (Replica room0) against
// the 5*block_size^3 worst case -- 2560 for the default 8-voxel block, ~40x
// higher -- and the estimate self-corrects from the first completed extract, so
// this only has to be the right order of magnitude. Guessing low costs one
// extra dispatch on the first call; guessing high costs resident memory for the
// extractor's whole lifetime, since the arena never shrinks.
constexpr std::uint64_t kSeedTrisPerBlock = 64;

// A corner with weight at or below this is treated as unintegrated, and any
// cell touching it is skipped. Small and positive so a never-integrated voxel
// (weight 0) is excluded while any genuine integration counts. The `tsdf` tier
// will surface this as a tunable knob; the dense analytic path fills every
// weight.
constexpr float kWeightThreshold = 1e-6f;

// The lookup tables, flattened for upload -- byte-identical to the GLSL
// `Tables` block (scalar layout, all-int so std430 and scalar agree). One
// definition of the tables (the constexpr arrays in the header) feeds both
// sides.
struct McTables {
  std::int32_t tri_table[256 * 16];
  std::int32_t corner_offset[8 * 3];
  std::int32_t edge_to_vert[12 * 2];
};
static_assert(sizeof(McTables) ==
                  (256 * 16 + 8 * 3 + 12 * 2) * sizeof(std::int32_t),
              "McTables must be tightly packed for the shader ABI");

// The push-constant block the kernel reads (mirrors `PushConstants` in
// marching_cubes.comp under scalar layout).
struct PushConstants {
  Vec3i dims;
  float voxel_size;
  Vec3f origin;
  float iso;
  std::uint32_t capacity;
  float weight_threshold;
  std::uint32_t has_color;  // 0 = no color input; vertices get opaque white
};
static_assert(sizeof(PushConstants) == 44, "PushConstants must be 44 bytes");
static_assert(offsetof(PushConstants, dims) == 0, "PushConstants layout drift");
static_assert(offsetof(PushConstants, voxel_size) == 12, "PushConstants drift");
static_assert(offsetof(PushConstants, origin) == 16, "PushConstants drift");
static_assert(offsetof(PushConstants, iso) == 28, "PushConstants drift");
static_assert(offsetof(PushConstants, capacity) == 32, "PushConstants drift");
static_assert(offsetof(PushConstants, weight_threshold) == 36,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, has_color) == 40,
              "PushConstants layout drift");

// The push-constant block the sparse kernel reads (mirrors `PushConstants` in
// marching_cubes_sparse.comp under scalar layout). The grid geometry rides here
// (block_size / voxel_size); the block coordinates and per-voxel data come
// through the bound buffers.
struct SparsePushConstants {
  std::int32_t block_size;
  std::int32_t voxels_per_block;
  float voxel_size;
  float iso;
  std::uint32_t num_active_blocks;
  std::uint32_t capacity;
  float weight_threshold;
  std::uint32_t has_color;  // 0 = no color attribute; vertices get opaque white
  // The hash-table shape, for the kernel's on-device neighbour probe. The
  // sparse kernel resolves the 2x2x2 neighbourhood itself now, so it needs to
  // traverse the table the same way the volume tier does.
  std::int32_t num_buckets;
  std::int32_t bucket_size;
  std::int32_t max_chain;
};
// Pin every field offset (all 4-byte scalars): a same-size reorder would keep
// sizeof == 44 but silently drift the host<->GLSL push-constant ABI, so guard
// each one, matching the dense PushConstants above.
static_assert(sizeof(SparsePushConstants) == 44,
              "SparsePushConstants must be 44 bytes");
static_assert(offsetof(SparsePushConstants, block_size) == 0,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, voxels_per_block) == 4,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, voxel_size) == 8,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, iso) == 12,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, num_active_blocks) == 16,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, capacity) == 20,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, weight_threshold) == 24,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, has_color) == 28,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, num_buckets) == 32,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, bucket_size) == 36,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, max_chain) == 40,
              "SparsePushConstants layout drift");

// Bytes a vertex arena needs to hold @p capacity triangles (3 vertices each).
std::uint64_t arena_bytes_for(std::uint32_t capacity) {
  return static_cast<std::uint64_t>(capacity) * kIndicesPerTriangle *
         sizeof(Vertex);
}

// The inverse: the most triangles an arena may hold under a binding-range
// limit. Never zero for any conformant device -- Vulkan's guaranteed floor of
// 2^27 covers 699050 triangles at 192 B each.
std::uint64_t max_triangles_for(std::uint64_t max_range) {
  return max_range / (kIndicesPerTriangle * sizeof(Vertex));
}

// Read the atomic triangle count back and copy the emitted vertices into a
// Mesh with the trivial 0,1,2,... index run (independent triangles; a later
// shared-vertex dedup can shrink `vertices` without changing the Mesh
// contract). The dense extract's readback; the sparse path leaves its result on
// the device and downloads it separately.
Mesh collect_mesh(const Buffer& vertices, const Buffer& indirect,
                  std::uint32_t capacity,
                  std::uint32_t* emitted_out = nullptr) {
  // The counter *is* the command's indexCount, so triangles are a third of it
  // -- see mcEmitCell, which adds kIndicesPerTriangle per triangle.
  VkDrawIndexedIndirectCommand command{};
  std::memcpy(&command, indirect.mapped(), sizeof(command));
  std::uint32_t emitted = command.indexCount / kIndicesPerTriangle;
  // The dense path is worst-case sized, so the kernel never drops -- but the
  // count is a device write, and this clamp is what keeps the copy below inside
  // the arena regardless.
  emitted = std::min(emitted, capacity);
  if (emitted_out != nullptr) *emitted_out = emitted;

  const auto vertex_count =
      static_cast<std::size_t>(emitted) * kIndicesPerTriangle;
  Mesh mesh;
  // TODO(mesh): resize() zero-initializes the vector and the memcpy below
  // immediately overwrites it -- two passes over the whole readback. There is
  // no resize-without-init on std::vector; revisit if the download shows up in
  // an ExtractTimings profile.
  mesh.vertices.resize(vertex_count);
  if (vertex_count > 0) {
    std::memcpy(mesh.vertices.data(), vertices.mapped(),
                vertex_count * sizeof(Vertex));
  }
  mesh.indices.resize(vertex_count);
  std::iota(mesh.indices.begin(), mesh.indices.end(), std::uint32_t{0});
  return mesh;
}

// Stopwatch for the opt-in ExtractTimings. Reading the clock is cheap, but it
// is skipped entirely when the caller wants no measurement, so the untimed path
// costs one branch per phase.
class PhaseClock {
 public:
  explicit PhaseClock(bool enabled) : enabled_(enabled) { restart(); }

  void restart() {
    if (enabled_) start_ = std::chrono::steady_clock::now();
  }

  // Milliseconds since the last restart, then restart for the next phase.
  double lap() {
    if (!enabled_) return 0.0;
    const auto now = std::chrono::steady_clock::now();
    const double ms =
        std::chrono::duration<double, std::milli>(now - start_).count();
    start_ = now;
    return ms;
  }

 private:
  bool enabled_;
  std::chrono::steady_clock::time_point start_{};
};

}  // namespace

std::uint32_t MarchingCubes::plan_capacity(std::uint32_t num_active,
                                           std::uint64_t worst_case) const {
  // Predict from density rather than react to an overflow: the last extract
  // measured how many triangles an active block carries, and scaling that by
  // THIS call's active set moves the plan ahead of a growing surface. A purely
  // reactive plan (whatever the arena happens to hold) discovers every size
  // increase by overflowing, which throws a whole dispatch away each time.
  const std::uint64_t per_block =
      tris_per_block_ != 0 ? tris_per_block_ : kSeedTrisPerBlock;
  const std::uint64_t estimate =
      static_cast<std::uint64_t>(num_active) * per_block;
  // Bounded above by the worst case and by nothing else. This is a *request*,
  // and ensure_output_buffers is the only thing that reads it: it keeps
  // whatever the slot already holds and grows only when the request is larger,
  // so a floor at the held capacity would change no allocation it makes.
  //
  // That floor is gone rather than repositioned, and its absence is the fix.
  // Floored at arena_capacity() this number depends on *which slot is
  // current*, so with a ring it read the slot just written while a different
  // one was about to be grown -- every extract then asked for 1.5x the last,
  // geometrically, with the measured density never getting a say (an iPad Pro
  // reached a 1.1 GB arena for 36904 triangles, 0.59% full, in a few hundred
  // remeshes). A purely positional invariant inside a 340-line function is one
  // reordering away from coming back; with the floor deleted the plan reads no
  // slot at all and cannot compound in any call order.
  //
  // Bounded below the device's binding limit too, and that is a *clamp rather
  // than a rejection* on purpose. This number is a guess -- a density measured
  // on the previous call, scaled by this one's active set -- so rejecting it
  // fails extracts whose real surface fits: on a driver at Vulkan's guaranteed
  // 2^27 the seed density plans 704000 triangles for 11000 blocks against a
  // ceiling of 699050, for a surface that emits ~660000 and would have been
  // fine. Worse, it failed *permanently*: tris_per_block_ is written only on
  // the success path, so the estimate never corrected, and a scan's active set
  // only grows, so every later extract recomputed the same rejected number.
  // Clamped instead, the dispatch runs, the kernel reports the field's true
  // total, and an arena that genuinely cannot fit is rejected by
  // ensure_output_buffers against that *measured* count -- which is what the
  // error has always claimed to mean.
  const std::uint64_t device_cap = max_triangles_for(max_storage_buffer_range_);
  return static_cast<std::uint32_t>(
      std::min({estimate, worst_case, device_cap}));
}

Status MarchingCubes::claim_output_slot() {
  // Called once at the top of each extract, before anything is touched, with
  // `++generation_` as the very next statement. Both halves of that are
  // load-bearing and they pull in opposite directions, which is why they are
  // adjacent rather than merely ordered.
  //
  // Before the bump: refusing here must cost the caller nothing. This is the
  // path that protects slots a consumer is still reading, so a refused extract
  // has written no buffer, freed no allocation, and must leave every
  // outstanding DeviceMesh exactly as valid as it was. Bumping first would
  // break that on its own -- download()'s currency check would then refuse a
  // mesh whose slot this call deliberately did not touch, so the refusal meant
  // to protect the consumer's live mesh would instead retire it.
  //
  // Immediately before it: this advances slot_, and download() reads the
  // current slot on the strength of a *generation* comparison. Anything
  // fallible in between leaves a window where slot_ has moved and generation_
  // has not, so an outstanding DeviceMesh passes the currency check and is
  // copied out of a slot that may never have been sized -- a memcpy from
  // Buffer::mapped() == nullptr, or from an older, smaller arena once the ring
  // has turned.
  //
  // Once per extract, not once per call, is structural now rather than
  // conditional: ensure_output_buffers runs twice when a call refits against
  // its measured triangle count, and advancing there would strand the first
  // dispatch's output in the previous slot. It also makes the refit's grow safe
  // for free -- the buffer it frees is one only this extract has written.
  if (slot_count_ == 1) {
    // One slot never moves, and the contract is what it always was: a
    // DeviceMesh is superseded by the next extract, and `generation` enforces
    // it.
    return {};
  }
  // Round-robin from the slot after the current one, so growth spreads evenly
  // over the ring and the oldest slot is tried first. It *scans* rather than
  // taking that one on faith: "the next slot is always the oldest" holds only
  // while every claim goes on to publish a mesh, and two paths do not -- an
  // extract that fails after claiming, and the host overloads, which give their
  // slot straight back once the copy is taken (free_slot_of). Both leave a free
  // slot behind the cursor, and assuming would refuse with one in hand.
  //
  // Everything downstream is free to overwrite the slot this picks, and a grow
  // will *free* it outright, so it must have been released first.
  std::uint64_t oldest = 0;
  for (std::size_t i = 1; i <= slot_count_; ++i) {
    const std::size_t candidate = (slot_ + i) % slot_count_;
    if (slots_[candidate].generation <= released_through_) {
      slot_ = candidate;
      return {};
    }
    if (oldest == 0 || slots_[candidate].generation < oldest) {
      oldest = slots_[candidate].generation;
    }
  }
  return Status::invalid_argument(
      "MarchingCubes::extract: every output slot is still outstanding "
      "(oldest is generation " +
      std::to_string(oldest) + ", released through " +
      std::to_string(released_through_) +
      "); call release_through as meshes are finished with, or configure "
      "more slots than the consumer keeps in flight");
}

void MarchingCubes::free_slot_of(std::uint64_t generation) noexcept {
  // Give one slot back without moving released_through_. That distinction is
  // the whole reason this exists beside release_through: the high-water mark is
  // the *consumer's* statement about what it has finished reading, so using it
  // to retire a slot this class allocated for itself would also mark every
  // older slot released -- including one holding a DeviceMesh an extract_device
  // caller is still drawing out of, on the same extractor.
  //
  // Generations are pre-incremented from 0, so 0 is "never written" and matches
  // every untouched slot; refuse it rather than freeing the whole ring.
  if (generation == 0) return;
  for (Slot& slot : slots_) {
    if (slot.generation == generation) slot.generation = 0;
  }
}

void MarchingCubes::release_through(std::uint64_t generation) noexcept {
  // Monotonic: an older report never un-releases a slot. A consumer finishing
  // frames out of order, or reporting a stale value after a newer one, would
  // otherwise make a freed slot look busy again -- and, worse, could not make a
  // busy one look free, so the failure would be a stall rather than corruption.
  // Cheap to make impossible either way.
  released_through_ = std::max(released_through_, generation);
}

Status MarchingCubes::ensure_indirect_command() {
  if (!indirect().valid()) {
    // INDIRECT_BUFFER beside STORAGE_BUFFER: the kernel counts into field 0
    // through the storage binding, and a renderer issues
    // vkCmdDrawIndexedIndirect from the very same bytes. Both unconditional
    // rather than config-gated -- 20 bytes, and a consumer that never draws
    // indirectly pays a usage bit nobody reads. The queue families *are* the
    // consumer's, though: a renderer on a second family reads this buffer as
    // surely as it reads the arena, so it takes the same sharing treatment.
    VR_ASSIGN(
        indirect(),
        storage_buffer(
            *allocator_, sizeof(VkDrawIndexedIndirectCommand),
            HostAccess::Random,
            VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT | config_.extra_indirect_usage,
            config_.queue_family_count > 0 ? config_.queue_families : nullptr,
            config_.queue_family_count));
  }
  // The whole command, not just the counter it starts as. indexCount is zeroed
  // for the kernel to accumulate into; the other four fields are what make the
  // result a *drawable* command rather than a number a host has to build one
  // from -- one instance, no index or vertex offset, and the identity index run
  // means firstIndex is always 0.
  VkDrawIndexedIndirectCommand reset{};
  reset.indexCount = 0;
  reset.instanceCount = 1;
  reset.firstIndex = 0;
  reset.vertexOffset = 0;
  reset.firstInstance = 0;
  std::memcpy(indirect().mapped(), &reset, sizeof(reset));
  return {};
}

void MarchingCubes::clamp_indirect_to_arena() noexcept {
  if (!indirect().valid()) return;
  // What the arena can hold, which is the only thing a draw may read. On a
  // failure that freed the arena outright this is 0 -- the honest answer, since
  // there is then no geometry to draw at all.
  const auto indices = static_cast<std::uint32_t>(
      static_cast<std::uint64_t>(arena_capacity()) * kIndicesPerTriangle);
  // Field 0 only: the other four are still the drawable values the reset wrote,
  // and rewriting the whole struct would need it rebuilt here for no reason.
  std::memcpy(indirect().mapped(), &indices, sizeof(indices));
}

Status MarchingCubes::ensure_output_buffers(std::uint32_t capacity) {
  // Guard the REQUESTED capacity against the device's binding limit before any
  // growth headroom is added, so a surface that legitimately fits is never
  // rejected because the growth policy overshot.
  if (arena_bytes_for(capacity) > max_storage_buffer_range_) {
    return Status::invalid_argument(
        "MarchingCubes::extract: a vertex arena for " +
        std::to_string(capacity) +
        " triangles exceeds the device maxStorageBufferRange");
  }
  // No slot stamp here, deliberately. Marking the slot outstanding is the
  // publishing return's job (it sits beside `device_mesh.generation`), because
  // the stamp says "a consumer holds a mesh in this slot" and only a path that
  // hands one out can make that true. Stamping here instead made every failure
  // exit below -- and the dispatch, the refit, and the out_of_memory return
  // above the caller -- leave a slot marked with a generation no DeviceMesh
  // ever carried, which nothing could then release: slot_count such failures
  // and the extractor refuses forever, quoting generations it never handed out.
  //
  // The command is the only per-call reset: 20 bytes, against an arena whose
  // stale tail is never read (indexCount bounds the readback). It happens ABOVE
  // the reuse early-return below, and must stay there: a refit that reallocated
  // nothing still has to hand the retry a zeroed count, or the second dispatch
  // accumulates onto the first's.
  VR_TRY(ensure_indirect_command());

  if (arena().valid() && capacity <= arena_capacity()) {
    return {};  // the steady state -- no allocation at all
  }
  // Grow geometrically rather than to the exact request: the active set climbs
  // steadily through a scan, so exact sizing would reallocate (and re-fault)
  // this large buffer on most frames. The headroom multiplies the LARGER of
  // the request and what is held, so a refit to a measured count gets headroom
  // too (it is the request that a growing scan will outgrow next). Fall back to
  // the exact request whenever the headroom would not fit -- the request itself
  // already passed the guard above, so a surface that legitimately fits is
  // never rejected by an overshoot. Both tests run in 64-bit *before*
  // narrowing: 1.5x a near-uint32 capacity does not fit a uint32, and
  // truncating first could turn an over-large request into a small one that
  // passes the byte check.
  const std::uint64_t grown =
      std::max<std::uint64_t>(capacity, arena_capacity()) * 3 / 2;
  const bool headroom_fits =
      grown <= 0xFFFFFFFFull &&
      arena_bytes_for(static_cast<std::uint32_t>(grown)) <=
          max_storage_buffer_range_;
  const std::uint32_t grown_capacity =
      headroom_fits ? static_cast<std::uint32_t>(grown) : capacity;

  // Drop the old arena BEFORE allocating the new one, so the grow asks the
  // driver for one arena rather than two. VMA pools an emptied block instead of
  // returning it (see tests/core_memory_stats_test.cpp), so this holds against
  // the *driver* for an arena large enough to get a dedicated allocation; a
  // small one lives in a pooled block that VMA keeps, and process RSS can still
  // show both across the grow. Failing here leaves the extractor with no arena
  // rather than a capacity claiming a buffer that was never allocated.
  //
  // This assignment calls vmaDestroyBuffer *immediately* -- there is no fence
  // wait and no deferred retire. Safe for this tier's own work, which is
  // fence-blocked inside submit_single_time, but NOT for an external consumer
  // holding a DeviceMesh: see the seam-B TODO on MarchingCubesConfig, which is
  // why a bindable arena is not yet a drawable one.
  arena() = Buffer{};
  // Released together: arena_capacity() is derived from the arena's size, so
  // dropping the arena is what marks the pair unsized, and the index run must
  // not outlive the arena it indexes.
  index_run() = Buffer{};

  // Build both into locals and commit them together, so a failure on the second
  // allocation cannot leave a sized arena beside a null index run -- which
  // arena_capacity() would then report as ready and the next extract would hand
  // out as a DeviceMesh naming no index buffer.
  // config_ is applied on every grow, not just the first, so the consumer's
  // usage survives a reallocation (see MarchingCubesConfig).
  VR_ASSIGN(
      Buffer grown_arena,
      storage_buffer(
          *allocator_,
          static_cast<VkDeviceSize>(arena_bytes_for(grown_capacity)),
          HostAccess::Random, config_.extra_vertex_usage,
          config_.queue_family_count > 0 ? config_.queue_families : nullptr,
          config_.queue_family_count));

  // The index run covers the whole arena and never changes shape, so it is
  // written once here rather than rebuilt per extract. iota straight into the
  // mapped buffer: no staging copy, and only on a grow. SequentialWrite because
  // this fill is the only host access it ever gets -- download() regenerates
  // the run on the host rather than reading back from write-combined memory.
  const std::size_t index_count =
      static_cast<std::size_t>(grown_capacity) * kIndicesPerTriangle;
  VR_ASSIGN(
      Buffer indices_buf,
      storage_buffer(
          *allocator_,
          static_cast<VkDeviceSize>(index_count * sizeof(std::uint32_t)),
          HostAccess::SequentialWrite, config_.extra_index_usage,
          config_.queue_family_count > 0 ? config_.queue_families : nullptr,
          config_.queue_family_count));
  auto* indices = static_cast<std::uint32_t*>(indices_buf.mapped());
  std::iota(indices, indices + index_count, std::uint32_t{0});

  arena() = std::move(grown_arena);
  index_run() = std::move(indices_buf);
  return {};
}

Result<MarchingCubes> MarchingCubes::create(Device& device,
                                            Allocator& allocator,
                                            const MarchingCubesConfig& config) {
  // Reject the one usage bit this repo's Device provably cannot honour, here
  // where the caller supplied it rather than inside the first extract's arena
  // grow (CLAUDE.md's "validate before creating"). Device::create never enables
  // bufferDeviceAddress, and the allocator is built without
  // VMA_ALLOCATOR_CREATE_BUFFER_DEVICE_ADDRESS_BIT, so this bit trips a VMA
  // assert in a debug build and drops VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT in
  // NDEBUG. Other bits are gated by features/extensions an adopted device may
  // legitimately have enabled, so they are the embedder's call, not ours.
  const VkBufferUsageFlags unsupported =
      VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT;
  // All three output buffers, not two: the indirect command takes consumer
  // usage the same way the arena and index run do, so leaving it out of the
  // guard would let the bit through on the one buffer nothing else checks.
  if (((config.extra_vertex_usage | config.extra_index_usage |
        config.extra_indirect_usage) &
       unsupported) != 0) {
    return Status::invalid_argument(
        "MarchingCubes::create: VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT is "
        "not supported -- Device::create does not enable bufferDeviceAddress");
  }

  // Caught here rather than at the first arena grow, where it would surface as
  // a buffer-creation failure several frames into a scan. Allocator applies the
  // same limit to *distinct* families; this bounds what the config can carry at
  // all, since the array is fixed-size and a count past it would read past the
  // end.
  if (config.queue_family_count > BufferDesc::kMaxQueueFamilies) {
    return Status::invalid_argument(
        "MarchingCubes::create: queue_family_count must be 0.." +
        std::to_string(BufferDesc::kMaxQueueFamilies) + " (got " +
        std::to_string(config.queue_family_count) + ")");
  }

  if (config.slot_count == 0 || config.slot_count > kMaxSlots) {
    return Status::invalid_argument(
        "MarchingCubes::create: slot_count must be 1.." +
        std::to_string(kMaxSlots) + " (got " +
        std::to_string(config.slot_count) +
        "); 1 is the default and the single-arena behaviour, and the ceiling "
        "is what the slot array holds");
  }

  const VkDevice dev = device.handle();

  MarchingCubes mc;
  mc.device_ = &device;
  mc.allocator_ = &allocator;

  // Cache the 1-D dispatch's groupCountX ceiling so extract() can reject an
  // over-large grid cleanly (see dispatch()), plus the storage-buffer binding
  // limit so extract() can reject a worst-case vertex arena that would exceed
  // it before the allocation fails opaquely.
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  mc.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  mc.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;
  mc.config_ = config;
  // Sized once and never resized: slot_ indexes it on every extract, and the
  // buffers are filled lazily by the first extract that needs each one, so an
  // unused slot costs a Buffer's worth of null handles rather than an arena.
  mc.slot_count_ = config.slot_count;

  // Two kernels share one pool. The dense kernel binds five storage buffers:
  // tables (persistent) + the per-extract samples / colors / vertices /
  // counter. The sparse kernel binds eight: tables (persistent) + the
  // per-extract active blocks / neighbour LUT / tsdf / weight / color /
  // vertices / counter. KernelSetBuilder (core/compute_kernel.hpp) builds each
  // layout + pipeline and allocates its set from a shared pool sized to the
  // exact descriptor total.
  VkPushConstantRange push{};
  push.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push.offset = 0;
  push.size = sizeof(PushConstants);
  VkPushConstantRange push_sparse = push;
  push_sparse.size = sizeof(SparsePushConstants);
  KernelSetBuilder kb(dev);
  VR_TRY(kb.add(mc.kernel_, vr_marching_cubes_comp_spv,
                vr_marching_cubes_comp_spv_size, 5, &push));
  VR_TRY(kb.add(mc.kernel_sparse_, vr_marching_cubes_sparse_comp_spv,
                vr_marching_cubes_sparse_comp_spv_size, 8, &push_sparse));
  VR_ASSIGN(mc.pool_, kb.build());

  // Upload the lookup tables once and bind them at set binding 0 of both
  // kernels for good. The constexpr header arrays are the single source;
  // flatten them into the shader block layout.
  VR_ASSIGN(mc.tables_, storage_buffer(allocator, sizeof(McTables),
                                       HostAccess::SequentialWrite));
  McTables host_tables;
  std::memcpy(host_tables.tri_table, kTriTable, sizeof(kTriTable));
  std::memcpy(host_tables.corner_offset, kCornerOffset, sizeof(kCornerOffset));
  std::memcpy(host_tables.edge_to_vert, kEdgeToVert, sizeof(kEdgeToVert));
  std::memcpy(mc.tables_.mapped(), &host_tables, sizeof(McTables));
  mc.kernel_.set.write_storage_buffer(0, mc.tables_.handle(), 0, VK_WHOLE_SIZE);
  mc.kernel_sparse_.set.write_storage_buffer(0, mc.tables_.handle(), 0,
                                             VK_WHOLE_SIZE);

  // A 1-element dummy for the sparse kernel's color slot when a grid carries no
  // color attribute; bound now so binding 5 is always valid, overwritten with a
  // real color buffer per extract when one exists.
  VR_ASSIGN(mc.color_dummy_, storage_buffer(allocator, sizeof(std::uint32_t),
                                            HostAccess::SequentialWrite));
  std::memset(mc.color_dummy_.mapped(), 0, sizeof(std::uint32_t));
  mc.kernel_sparse_.set.write_storage_buffer(5, mc.color_dummy_.handle(), 0,
                                             VK_WHOLE_SIZE);

  return mc;
}

Result<Mesh> MarchingCubes::extract(const volume::Voxel* samples,
                                    std::size_t count, const DenseGrid& grid,
                                    float iso, const Vec3u8* colors) {
  if (!valid()) {
    return Status::invalid_argument("MarchingCubes::extract: moved-from");
  }
  if (samples == nullptr) {
    return Status::invalid_argument("MarchingCubes::extract: samples is null");
  }
  if (grid.dims.x < 2 || grid.dims.y < 2 || grid.dims.z < 2) {
    return Status::invalid_argument(
        "MarchingCubes::extract: grid must be at least 2x2x2 samples");
  }
  // `!(x > 0)` rather than `x <= 0` so a NaN voxel_size is rejected too (every
  // comparison with NaN is false, so `<= 0` would let it through).
  if (!(grid.voxel_size > 0.0f)) {
    return Status::invalid_argument(
        "MarchingCubes::extract: voxel_size must be > 0");
  }
  const auto sample_count = static_cast<std::uint64_t>(grid.dims.x) *
                            static_cast<std::uint64_t>(grid.dims.y) *
                            static_cast<std::uint64_t>(grid.dims.z);
  if (static_cast<std::uint64_t>(count) != sample_count) {
    return Status::invalid_argument(
        "MarchingCubes::extract: count must equal dims.x*dims.y*dims.z");
  }

  // Worst-case triangle capacity: one cell per (dims-1) step, 5 triangles each.
  const std::uint64_t cells = static_cast<std::uint64_t>(grid.dims.x - 1) *
                              static_cast<std::uint64_t>(grid.dims.y - 1) *
                              static_cast<std::uint64_t>(grid.dims.z - 1);
  const std::uint64_t capacity64 = cells * kMaxTrisPerCell;
  // capacity + the per-cell dispatch index both flow through 32-bit shader
  // values, so keep the worst case inside uint32.
  // The dense path keeps the worst-case sizing: it takes a caller-supplied
  // sample grid (the analytic/test entry point), so its cell count is small and
  // bounded by the caller, and one dispatch with no measurement step is the
  // simpler thing to keep correct.
  // TODO(mesh): fit this path to the surface too, as the sparse extract does.
  // The two overloads share the same ring, so a large dense call grows whatever
  // slot it lands on to the dense worst case, and that slot keeps it for the
  // extractor's lifetime -- which forfeits the fitted arena, for one slot per
  // dense call, in a process that uses both entry points.
  if (capacity64 > 0xFFFFFFFFull || cells > 0xFFFFFFFFull) {
    return Status::invalid_argument(
        "MarchingCubes::extract: grid too large for this slice");
  }
  const auto capacity = static_cast<std::uint32_t>(capacity64);

  // Claim the slot and bump the generation before this call does anything else.
  // Both placements are load-bearing and both are argued at claim_output_slot:
  // a refusal has to cost the caller nothing, and the bump has to be the very
  // next statement so no fallible work sits between slot_ moving and
  // generation_ moving. Everything below is work a refused extract would only
  // throw away.
  //
  // The bump is what invalidates every outstanding DeviceMesh, and it happens
  // here rather than on success because this call is about to overwrite -- and,
  // on a grow, reallocate -- the claimed slot's arena whether or not it
  // succeeds.
  VR_TRY(claim_output_slot());
  ++generation_;

  // Per-extract buffers (sized to this grid): the samples in, the vertex arena
  // out (3 vertices per triangle at worst-case capacity), and the atomic
  // triangle counter.
  VR_ASSIGN(
      Buffer samples_buf,
      storage_buffer(*allocator_,
                     static_cast<VkDeviceSize>(count) * sizeof(volume::Voxel),
                     HostAccess::SequentialWrite));
  std::memcpy(samples_buf.mapped(), samples, count * sizeof(volume::Voxel));

  // Colors (optional, parallel to samples): each sample's RGB packed into the
  // low three bytes of a uint (the kernel reads it back with unpackUnorm4x8 and
  // takes .rgb, so the high byte is unused and left zero). Always bound so the
  // descriptor is valid; the has_color push flag tells the kernel whether to
  // read it. Absent -> a 1-element dummy buffer + opaque-white vertices.
  const std::uint32_t has_color = colors != nullptr ? 1u : 0u;
  Buffer colors_buf;
  if (colors != nullptr) {
    VR_ASSIGN(colors_buf, storage_buffer(*allocator_,
                                         static_cast<VkDeviceSize>(count) *
                                             sizeof(std::uint32_t),
                                         HostAccess::SequentialWrite));
    // Pack straight into the mapped buffer -- SequentialWrite is exactly this
    // forward, write-once pattern, so no staging vector or second copy.
    auto* packed = static_cast<std::uint32_t*>(colors_buf.mapped());
    for (std::size_t i = 0; i < count; ++i) {
      packed[i] = static_cast<std::uint32_t>(colors[i].x) |
                  (static_cast<std::uint32_t>(colors[i].y) << 8) |
                  (static_cast<std::uint32_t>(colors[i].z) << 16);
    }
  } else {
    VR_ASSIGN(colors_buf, storage_buffer(*allocator_, sizeof(std::uint32_t),
                                         HostAccess::SequentialWrite));
    std::memset(colors_buf.mapped(), 0, sizeof(std::uint32_t));
  }

  VR_TRY(ensure_output_buffers(capacity));

  kernel_.set.write_storage_buffer(1, samples_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(2, colors_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(3, arena().handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(4, indirect().handle(), 0, VK_WHOLE_SIZE);

  const PushConstants push{grid.dims, grid.voxel_size,  grid.origin, iso,
                           capacity,  kWeightThreshold, has_color};
  VR_TRY(dispatch(*device_, kernel_, &push, sizeof(push),
                  group_count(static_cast<std::uint32_t>(cells), kLocalSize),
                  max_workgroup_count_x_));

  Mesh mesh = collect_mesh(arena(), indirect(), capacity);
  // Nothing to give back, and that is a property rather than an omission: this
  // overload's whole product is the host copy above, so it hands out no
  // DeviceMesh and never stamps its slot -- which leaves the slot exactly as
  // claimable as claim_output_slot found it, on this path and on every failure
  // exit above.
  //
  // It used to call release_through(generation_) here, which kept a host-only
  // caller off the ring contract but did it with the *consumer's* high-water
  // mark: that also marked every older slot released, including one holding a
  // DeviceMesh an extract_device caller on this same extractor was still
  // drawing out of. See free_slot_of, which is the sparse overload's answer to
  // the same problem.
  return mesh;
}

Result<Mesh> MarchingCubes::extract(volume::VoxelBlockGrid& grid, float iso,
                                    ExtractTimings* timings) {
  VR_ASSIGN(const DeviceMesh device_mesh, extract_device(grid, iso, timings));
  // The host copy is part of this call's readback, so it belongs in the phase
  // that names it -- extract_device stamped readback_ms with the 20-byte
  // command read alone, which is right for that entry point but would leave the
  // host path's ~45 MB copy uncounted in ExtractTimings::total_ms.
  PhaseClock download_clock(timings != nullptr);
  Result<Mesh> mesh = download(device_mesh);
  if (timings != nullptr) timings->readback_ms += download_clock.lap();
  // This overload's whole product is the host copy, so the slot extract_device
  // claimed and stamped is finished with as soon as download() has run -- and
  // given back whether it succeeded or not, since a failure that stranded the
  // slot would starve the ring just as surely. A host-only caller never sees a
  // generation (the return type carries none), so it cannot honour the release
  // contract itself; this is what keeps it off that contract entirely.
  //
  // free_slot_of, not release_through: this slot is the only one to give back.
  // The high-water mark is the consumer's statement about what *it* has
  // finished reading, so using it here would also retire every older slot --
  // including one holding a DeviceMesh an extract_device caller on this same
  // extractor is still drawing out of, whose arena the next grow would then
  // vmaDestroyBuffer under a live draw.
  free_slot_of(device_mesh.generation);
  return mesh;
}

Result<Mesh> MarchingCubes::download(const DeviceMesh& device_mesh) const {
  // Moved-from, like both extract entry points -- and this one needs it most.
  // The defaulted moves reset every *owned* member (Buffer and the pipeline
  // wrappers each self-empty), but generation_ and slot_ are plain scalars a
  // defaulted move copies rather than zeroes, and a DeviceMesh holds raw
  // VkBuffer values copied out at extract time, so valid() is still true on it.
  // The currency check below would therefore pass on a moved-from extractor and
  // the memcpy would run on a null Buffer::mapped(). Guarding here rather than
  // hand-writing the moves keeps the rule-of-zero note above intact -- the
  // scalars are unobservable once every entry point gates on valid().
  if (!valid()) {
    return Status::invalid_argument("MarchingCubes::download: moved-from");
  }
  // An empty mesh copies to an empty Mesh without touching the buffers, which
  // a grid with no active blocks never even allocated.
  if (device_mesh.empty()) {
    return Mesh{};
  }
  // Only this extractor's newest extract may be downloaded, and the check is by
  // generation, NOT by buffer handle. With one slot the arena is grow-only and
  // reused in place, so a superseded view names the very same VkBuffer as the
  // live one and a handle comparison would accept it, handing back the newer
  // extract's geometry under this view's stale counts. With a ring it is the
  // other way round -- a superseded view names a *different* buffer -- and the
  // generation check is what makes the unqualified arena() below correct: an
  // extract advances slot_ and generation_ in the same breath and nothing moves
  // slot_ again until the next claim, so "this mesh is the current generation"
  // and "this mesh lives in the current slot" are the same statement. That is
  // why those two lines are adjacent: anything fallible between them opens a
  // window where they disagree and this memcpy reads the wrong slot -- one that
  // may never have been sized, so mapped() is null. A DeviceMesh does not carry
  // its slot, so that invariant is the only thing tying the copy below to the
  // right buffer. Widening this to accept an older generation therefore means
  // indexing slots_ by it, not just relaxing the comparison.
  if (device_mesh.generation != generation_ || !device_mesh.valid()) {
    return Status::invalid_argument(
        "MarchingCubes::download: the DeviceMesh is not this extractor's "
        "current extract (superseded by a later one, or from another "
        "extractor)");
  }
  Mesh mesh;
  const auto vertex_count = static_cast<std::size_t>(device_mesh.vertex_count);
  mesh.vertices.resize(vertex_count);
  mesh.indices.resize(vertex_count);
  if (vertex_count > 0) {
    std::memcpy(mesh.vertices.data(), arena().mapped(),
                vertex_count * sizeof(Vertex));
    // Regenerated, not read back: the run is the identity 0,1,2,... and
    // index_run() is write-combined (SequentialWrite), where host reads are
    // pathologically slow. Generating it costs nothing and touches no device
    // memory.
    std::iota(mesh.indices.begin(), mesh.indices.end(), std::uint32_t{0});
  }
  return mesh;
}

Result<DeviceMesh> MarchingCubes::extract_device(volume::VoxelBlockGrid& grid,
                                                 float iso,
                                                 ExtractTimings* timings) {
  // Fully overwrite the caller's struct up front, so the accumulating spans
  // below start from zero and one instance can be reused across frames. A
  // failed call then reports zeros rather than a previous call's numbers.
  if (timings != nullptr) *timings = ExtractTimings{};
  if (!valid()) {
    return Status::invalid_argument("MarchingCubes::extract: moved-from");
  }
  if (!grid.valid()) {
    return Status::invalid_argument(
        "MarchingCubes::extract: grid is moved-from");
  }
  // The grid must carry the float tsdf + weight the sparse kernel samples; the
  // uint32 color attribute is optional (its absence -> opaque-white vertices).
  VR_ASSIGN(volume::AttributeView tsdf_view, grid.attribute("tsdf"));
  VR_ASSIGN(volume::AttributeView weight_view, grid.attribute("weight"));
  if (tsdf_view.element_size != sizeof(float) ||
      weight_view.element_size != sizeof(float)) {
    return Status::invalid_argument(
        "MarchingCubes::extract: tsdf/weight must be float attributes");
  }
  const bool has_color = grid.has_attribute("color");
  volume::AttributeView color_view{};
  if (has_color) {
    VR_ASSIGN(color_view, grid.attribute("color"));
    if (color_view.element_size != sizeof(std::uint32_t)) {
      return Status::invalid_argument(
          "MarchingCubes::extract: color must be a uint32 attribute");
    }
  }

  // Claim the slot and bump the generation before this call does anything else
  // -- which now means before the active-set compact below, not after it. Both
  // placements are argued at claim_output_slot: a refusal must cost the caller
  // nothing, and the bump must be the very next statement so no fallible work
  // sits between slot_ moving and generation_ moving.
  //
  // "Costs nothing" is meant literally, and the compact is why it has to be
  // here: it is a dispatch, a blocking fence wait and a full active-set
  // readback -- hundreds of KB at room0 scale -- and a live consumer that is
  // one frame behind refuses on *every* frame. Claiming above it makes the
  // refusal a comparison of slot generations and nothing else, and skips the
  // neighbour LUT and the two input uploads below for free.
  //
  // The bump is what invalidates every outstanding DeviceMesh, and it happens
  // here rather than on success because this call is about to overwrite -- and,
  // on a grow, reallocate -- the claimed slot's arena whether or not it
  // succeeds. Moving it above the compact widens that to a compact failure,
  // which is the conservative direction: it retires meshes a fraction earlier,
  // never later.
  VR_TRY(claim_output_slot());
  ++generation_;

  // The active set drives the dispatch (one thread per voxel of each block) and
  // supplies the neighbour lookup. An empty map means nothing to mesh.
  PhaseClock phase_clock(timings != nullptr);
  VR_ASSIGN(std::vector<volume::BlockIndex> active,
            grid.map().compact_active_blocks());
  if (timings != nullptr) timings->compact_ms = phase_clock.lap();
  if (active.empty()) {
    // Nothing to mesh -- but this path stamps the slot it claimed above exactly
    // like a real extract, so "every generation handed out lives in exactly one
    // slot" is total.
    //
    // It used to advance generation_ without claiming, on the reasoning that an
    // empty mesh owns no bytes and so needs no slot to protect. That is true of
    // the empty mesh and false of the *ring*: the consumer's contract is to
    // release_through(g) as generation g retires, an empty mesh retires the
    // instant it is handed over, and released_through_ is a high-water mark. So
    // releasing the empty generation would mark every older slot released too
    // -- including the one holding the mesh the consumer is still drawing,
    // because an empty extract is precisely when it keeps showing the previous
    // one. The next grow would then vmaDestroyBuffer an arena under a live
    // draw.
    //
    // The command must be reset even though no dispatch will touch it: a
    // consumer drawing indirectly reads it and never consults triangle_count --
    // that is the entire point of publishing one -- so inheriting the previous
    // extract's live indexCount would silently redraw the previous mesh out of
    // whichever arena this slot happens to hold. Zeroed, it draws nothing,
    // which is what an empty mesh means.
    VR_TRY(ensure_indirect_command());
    // Stamped here and not a line earlier: this is the last fallible statement,
    // so from here the DeviceMesh below is certain to be handed out. A stamp
    // above a return that never publishes is a slot nothing can release.
    slots_[slot_].generation = generation_;
    // The arena and index run are named as they are found: this slot may never
    // have been sized (nothing to size it for), in which case they are null
    // handles and valid() is false beside empty() being true. A consumer gates
    // on empty() and draws nothing either way.
    DeviceMesh device_mesh;
    device_mesh.vertices = arena().handle();
    device_mesh.indices = index_run().handle();
    device_mesh.indirect = indirect().handle();
    device_mesh.vertex_usage = arena().usage();
    device_mesh.index_usage = index_run().usage();
    device_mesh.indirect_usage = indirect().usage();
    device_mesh.sharing_mode = indirect().sharing_mode();
    device_mesh.generation = generation_;
    device_mesh.live_generation = &generation_;
    if (timings != nullptr) {
      // The arenas are retained across calls, so an extract that meshes
      // nothing still costs whatever the ring is holding. Reporting 0 here read
      // as "the extractor released its memory", which is the opposite of true
      // -- and this is the instrument the ring's runaway growth was diagnosed
      // with, so it is exactly the frame where a wrong figure misleads. The
      // per-call counters below stay 0, which is honest: this call planned no
      // capacity and emitted nothing.
      timings->arena_bytes = resident_arena_bytes();
    }
    return device_mesh;
  }

  const volume::VoxelGridParams& gp = grid.grid();
  const std::int32_t bs = gp.block_size;
  const auto vpb = static_cast<std::uint32_t>(gp.voxels_per_block);
  const auto num_active = static_cast<std::uint32_t>(active.size());

  // One invocation per voxel of each active block; worst-case 5 triangles each.
  // Both the thread index and the triangle capacity flow through 32-bit shader
  // values, so keep the thread count inside uint32.
  const std::uint64_t threads =
      static_cast<std::uint64_t>(num_active) * static_cast<std::uint64_t>(vpb);
  const std::uint64_t worst_case = threads * kMaxTrisPerCell;
  // Both the thread index and the triangle counter are 32-bit shader values.
  // The counter bound matters even though the arena is no longer sized for the
  // worst case: the kernel bumps `index_count` for every triangle the field
  // produces, dropped ones included, so a field whose worst case exceeds uint32
  // could wrap it -- and the host, which now trusts that count, would publish a
  // handful of triangles as the whole surface. Rejected here, before the
  // neighbour table, the uploads and a dispatch.
  //
  // The bound is in INDICES, not triangles. The atomic counts
  // kIndicesPerTriangle at a time (it is the draw command's indexCount), so
  // bounding the triangle total instead leaves the real counter free to reach
  // three times the limit -- exactly the wrap this exists to prevent. Worse
  // than a plain overflow, too: 2^32 % 3 == 1, so a wrapped counter also
  // desynchronises the `/ 3` that turns it into a slot index, and the dispatch
  // would overwrite triangles it had already emitted.
  if (threads > 0xFFFFFFFFull ||
      worst_case > 0xFFFFFFFFull / kIndicesPerTriangle) {
    return Status::invalid_argument(
        "MarchingCubes::extract: active set too large for this slice");
  }
  // The arena is sized to what the surface actually emits, not to the
  // 5-triangles-per-cell worst case. Real fields are nowhere near that bound --
  // a room scan fills ~2% of it -- and since the arena is now *retained*, the
  // worst case was resident memory rather than a transient over-allocation
  // (~1.8 GB against ~38 MB of triangles on Replica room0).
  //
  // Correctness does not depend on the guess: the kernel bumps `index_count`
  // for every triangle and drops those past `capacity`, so an undersized arena
  // is *detected*, never silently truncated. The count is a property of the
  // field, not of the atomic ordering, so refitting to it and re-running is
  // guaranteed to fit. That makes this a one-dispatch steady state that pays a
  // second dispatch only when the plan undershoots the surface, rather than
  // the unconditional two-dispatch count-then-fill this replaces.
  //
  // The plan reads no slot -- only this call's active set and the density the
  // last one measured -- so it is free to sit anywhere and cannot compound
  // across the ring. That is deliberate; see plan_capacity.
  const std::uint32_t capacity = plan_capacity(num_active, worst_case);

  // The neighbourhood is resolved in the kernel now, one workgroup per block,
  // so there is no host pass here at all -- see marching_cubes_sparse.comp.
  // This phase used to build an unordered_map of every active coord and do 8
  // lookups per block, which measured 102 ms of a 133 ms extract at 107k
  // blocks; the dispatch it fed was 26 ms. Kept as a zeroed timing rather than
  // removed from ExtractTimings so a caller's read-out keeps its shape across
  // this change and the phase's disappearance is visible as a 0 rather than a
  // missing field.
  phase_clock.restart();
  if (timings != nullptr) timings->neighbour_lut_ms = phase_clock.lap();

  // Per-extract inputs: the active blocks (write-once), and the vertex arena +
  // atomic counter out. The hash entries and attribute buffers bind straight
  // from the grid (no copy).
  VR_ASSIGN(Buffer active_buf,
            storage_buffer(*allocator_,
                           static_cast<VkDeviceSize>(num_active) *
                               sizeof(volume::BlockIndex),
                           HostAccess::SequentialWrite));
  std::memcpy(
      active_buf.mapped(), active.data(),
      static_cast<std::size_t>(num_active) * sizeof(volume::BlockIndex));

  if (timings != nullptr) timings->input_upload_ms = phase_clock.lap();
  VR_TRY(ensure_output_buffers(capacity));
  if (timings != nullptr) timings->arena_alloc_ms = phase_clock.lap();

  kernel_sparse_.set.write_storage_buffer(1, active_buf.handle(), 0,
                                          VK_WHOLE_SIZE);
  kernel_sparse_.set.write_storage_buffer(2, grid.map().entries_buffer(), 0,
                                          VK_WHOLE_SIZE);
  kernel_sparse_.set.write_storage_buffer(3, tsdf_view.buffer->handle(), 0,
                                          VK_WHOLE_SIZE);
  kernel_sparse_.set.write_storage_buffer(4, weight_view.buffer->handle(), 0,
                                          VK_WHOLE_SIZE);
  kernel_sparse_.set.write_storage_buffer(
      5, has_color ? color_view.buffer->handle() : color_dummy_.handle(), 0,
      VK_WHOLE_SIZE);

  // Both output bindings are written once per extract, which is what a ring
  // requires: each names the *claimed slot's* buffer, so both move when slot_
  // does. Within the call only the arena can change again -- a refit that
  // reallocates it rebinds it there -- while the command buffer is created once
  // per slot and reused.
  kernel_sparse_.set.write_storage_buffer(6, arena().handle(), 0,
                                          VK_WHOLE_SIZE);
  kernel_sparse_.set.write_storage_buffer(7, indirect().handle(), 0,
                                          VK_WHOLE_SIZE);
  if (timings != nullptr) timings->descriptor_ms = phase_clock.lap();

  // Run the surface, read the count, and re-run once if the arena was too
  // small. `index_count` counts every triangle the field produces -- the kernel
  // drops those past `capacity` but still bumps -- so an undersized arena
  // reports the exact size it needed, and the count is a property of the field
  // rather than of the atomic ordering, so the refitted retry cannot overflow
  // again. Bounded at two iterations for that reason.
  //
  // The dispatch is told the arena's *full* capacity rather than the planned
  // number, so it never drops a triangle the arena had room for -- and that
  // keeps `requested <= arena_capacity()` true by construction, which is what
  // bounds the vertex count published below.
  std::uint32_t requested = arena_capacity();
  std::uint32_t produced = 0;
  for (int attempt = 0; attempt < 2; ++attempt) {
    const SparsePushConstants push{bs,
                                   static_cast<std::int32_t>(vpb),
                                   gp.voxel_size,
                                   iso,
                                   num_active,
                                   requested,
                                   kWeightThreshold,
                                   has_color ? 1u : 0u,
                                   gp.num_buckets,
                                   gp.bucket_size,
                                   gp.max_chain};
    // One workgroup per block, not one thread per voxel: the kernel resolves
    // the block's 2x2x2 neighbourhood into shared memory, which only works when
    // every thread in the group belongs to the same block. Each group then
    // strides over the block's voxels, so this is independent of block_size.
    VR_TRY(dispatch(*device_, kernel_sparse_, &push, sizeof(push), num_active,
                    max_workgroup_count_x_));
    if (timings != nullptr) {
      timings->dispatch_ms += phase_clock.lap();
      ++timings->dispatches;
    }

    // Only the 20-byte command comes back; the geometry stays where the kernel
    // wrote it.
    VkDrawIndexedIndirectCommand produced_command{};
    std::memcpy(&produced_command, indirect().mapped(),
                sizeof(produced_command));
    produced = produced_command.indexCount / kIndicesPerTriangle;
    if (timings != nullptr) timings->readback_ms += phase_clock.lap();
    if (produced <= requested) {
      break;  // everything the field emitted is in the arena
    }
    // From here the command names more indices than the arena holds -- the
    // over-count is how the refit below learns its size -- so every exit until
    // the loop breaks has to bound it before returning. At slot_count == 1 an
    // outstanding DeviceMesh names this very buffer, so a failure that left the
    // over-count in place would hand a live consumer a draw that reads past the
    // end of both the arena and the index run.
    if (attempt == 1) {
      // Cannot happen -- the same field emits the same count, so the refitted
      // arena fits it -- but report rather than hand back a truncated mesh if
      // that assumption is ever broken.
      clamp_indirect_to_arena();
      return Status::out_of_memory(
          "MarchingCubes::extract: the vertex arena still overflowed after "
          "refitting it to the measured triangle count");
    }
    // Refit to the measured count (ensure_output_buffers adds the growth
    // headroom, and re-zeroes the command the retry is about to bump), then
    // rebind the arena in case it was reallocated.
    //
    // A failure here is the other path that returns mid-over-count: it can
    // reject the refit against maxStorageBufferRange, or fail the allocation
    // outright after having already freed the old arena -- in which case
    // arena_capacity() is 0 and the clamp writes exactly that.
    if (Status refit = ensure_output_buffers(produced); !refit.ok()) {
      clamp_indirect_to_arena();
      return refit;
    }
    kernel_sparse_.set.write_storage_buffer(6, arena().handle(), 0,
                                            VK_WHOLE_SIZE);
    requested = arena_capacity();
    if (timings != nullptr) timings->arena_alloc_ms += phase_clock.lap();
  }
  // Clamped against the arena itself, not against `requested`: this count is
  // what download()'s memcpy and the texturer's `num_vertices` bound run on, so
  // bound it by the buffer that has to hold it rather than by a variable that
  // tracks that buffer.
  const std::uint32_t emitted = std::min(produced, arena_capacity());

  // Record the density this surface actually had, so the next call's plan
  // scales it by that call's active set instead of discovering the size by
  // overflowing. Rounded up, so any non-empty surface records at least one
  // triangle per block; a surface that emitted nothing records 0, and the next
  // plan falls back to the seed.
  tris_per_block_ = static_cast<std::uint32_t>(
      (static_cast<std::uint64_t>(emitted) + num_active - 1) / num_active);

  // Nothing to clamp here, and that is a property worth stating rather than a
  // line worth adding: the loop breaks only on `produced <= requested`, and
  // `requested` is arena_capacity(), so `emitted == produced` and the command
  // already reads exactly emitted * kIndicesPerTriangle. A memcpy at this point
  // would rewrite the bytes that are already there and, by looking like the
  // guarantee, hide the fact that the paths which actually need one are the two
  // failure returns above -- which is where clamp_indirect_to_arena() is
  // called.

  // Everything fallible is behind us, so the mesh below is certain to be handed
  // out -- which is exactly when the slot may be marked outstanding. Stamping
  // any earlier (it used to happen inside ensure_output_buffers) leaves a slot
  // carrying a generation no DeviceMesh ever named whenever a call fails after
  // it, and nothing can release a generation the caller was never given.
  slots_[slot_].generation = generation_;

  DeviceMesh device_mesh;
  device_mesh.vertices = arena().handle();
  device_mesh.indices = index_run().handle();
  device_mesh.indirect = indirect().handle();
  device_mesh.vertex_usage = arena().usage();
  device_mesh.index_usage = index_run().usage();
  device_mesh.indirect_usage = indirect().usage();
  // One config creates all three, so any of them answers for the set.
  device_mesh.sharing_mode = arena().sharing_mode();
  device_mesh.triangle_count = emitted;
  device_mesh.vertex_count = emitted * kIndicesPerTriangle;
  device_mesh.generation = generation_;
  device_mesh.live_generation = &generation_;
  if (timings != nullptr) {
    timings->active_blocks = num_active;
    timings->triangle_capacity = requested;
    timings->emitted_triangles = emitted;
    // What the extractor is holding, not what this call asked for: the arenas
    // are retained and grown, so a steady-state call allocates nothing and
    // still reports them.
    //
    // Summed over the whole ring, not just the slot this call wrote. Every slot
    // holds its own arena, grown geometrically and never shrunk, so reporting
    // one of N would under-report resident memory N-fold -- and this field is
    // the instrument the ring's own runaway growth was diagnosed with.
    timings->arena_bytes = resident_arena_bytes();
  }
  return device_mesh;
}

}  // namespace volumetric_kit::recon::mesh
