// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/mesh/marching_cubes.hpp"

#include <algorithm>
#include <chrono>
#include <cstddef>
#include <cstring>
#include <numeric>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

#include "volumetric_kit/recon/core/allocator.hpp"
#include "volumetric_kit/recon/core/compute_kernel.hpp"
#include "volumetric_kit/recon/core/compute_util.hpp"
#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"
#include "volumetric_kit/recon/mesh/marching_cubes_tables.hpp"
#include "volumetric_kit/recon/volume/hash.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "marching_cubes_comp.spv.hpp"
#include "marching_cubes_sparse_comp.spv.hpp"

namespace volumetric_kit::recon::mesh {
namespace {

// Local group size, matching `layout(local_size_x = 256)` in the kernel.
constexpr std::uint32_t kLocalSize = 256;

// Worst-case triangles a single marching-cubes cell can emit (5 per the table).
constexpr std::uint64_t kMaxTrisPerCell = 5;

// Triangles per active block the first extract plans for, before any
// measurement is available. A real scan measures 54-68 (Replica room0) against
// the 5*block_size^3 worst case -- 2560 for the default 8-voxel block, ~40x
// higher -- and the estimate self-corrects from the first completed extract, so
// this only has to be the right order of magnitude. Guessing low costs one
// extra dispatch on the first call; guessing high costs resident memory for the
// extractor's whole lifetime, since the arena never shrinks.
constexpr std::uint64_t kSeedTrisPerBlock = 64;

// A corner with weight at or below this is treated as unintegrated, and any
// cell touching it is skipped. Small and positive so a never-integrated voxel
// (weight 0) is excluded while any genuine integration counts. The `tsdf` tier
// will surface this as a tunable knob; the dense analytic path fills every
// weight.
constexpr float kWeightThreshold = 1e-6f;

// The lookup tables, flattened for upload -- byte-identical to the GLSL
// `Tables` block (scalar layout, all-int so std430 and scalar agree). One
// definition of the tables (the constexpr arrays in the header) feeds both
// sides.
struct McTables {
  std::int32_t tri_table[256 * 16];
  std::int32_t corner_offset[8 * 3];
  std::int32_t edge_to_vert[12 * 2];
};
static_assert(sizeof(McTables) ==
                  (256 * 16 + 8 * 3 + 12 * 2) * sizeof(std::int32_t),
              "McTables must be tightly packed for the shader ABI");

// The push-constant block the kernel reads (mirrors `PushConstants` in
// marching_cubes.comp under scalar layout).
struct PushConstants {
  Vec3i dims;
  float voxel_size;
  Vec3f origin;
  float iso;
  std::uint32_t capacity;
  float weight_threshold;
  std::uint32_t has_color;  // 0 = no color input; vertices get opaque white
};
static_assert(sizeof(PushConstants) == 44, "PushConstants must be 44 bytes");
static_assert(offsetof(PushConstants, dims) == 0, "PushConstants layout drift");
static_assert(offsetof(PushConstants, voxel_size) == 12, "PushConstants drift");
static_assert(offsetof(PushConstants, origin) == 16, "PushConstants drift");
static_assert(offsetof(PushConstants, iso) == 28, "PushConstants drift");
static_assert(offsetof(PushConstants, capacity) == 32, "PushConstants drift");
static_assert(offsetof(PushConstants, weight_threshold) == 36,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, has_color) == 40,
              "PushConstants layout drift");

// The push-constant block the sparse kernel reads (mirrors `PushConstants` in
// marching_cubes_sparse.comp under scalar layout). The grid geometry rides here
// (block_size / voxel_size); the block coordinates and per-voxel data come
// through the bound buffers.
struct SparsePushConstants {
  std::int32_t block_size;
  std::int32_t voxels_per_block;
  float voxel_size;
  float iso;
  std::uint32_t num_active_blocks;
  std::uint32_t capacity;
  float weight_threshold;
  std::uint32_t has_color;  // 0 = no color attribute; vertices get opaque white
};
// Pin every field offset (all 4-byte scalars): a same-size reorder would keep
// sizeof == 32 but silently drift the host<->GLSL push-constant ABI, so guard
// each one, matching the dense PushConstants above.
static_assert(sizeof(SparsePushConstants) == 32,
              "SparsePushConstants must be 32 bytes");
static_assert(offsetof(SparsePushConstants, block_size) == 0,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, voxels_per_block) == 4,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, voxel_size) == 8,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, iso) == 12,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, num_active_blocks) == 16,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, capacity) == 20,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, weight_threshold) == 24,
              "SparsePushConstants layout drift");
static_assert(offsetof(SparsePushConstants, has_color) == 28,
              "SparsePushConstants layout drift");

// Hash a block coordinate for the host neighbour-lookup map. Reuses the volume
// tier's spatial-hash prime constants (volume/hash.hpp) so the mixing matches
// the device hash exactly; the map is a plain host container, not the device
// table.
struct CoordHash {
  std::size_t operator()(const Vec3i& c) const noexcept {
    return (static_cast<std::uint32_t>(c.x) * volume::kHashPrimeX) ^
           (static_cast<std::uint32_t>(c.y) * volume::kHashPrimeY) ^
           (static_cast<std::uint32_t>(c.z) * volume::kHashPrimeZ);
  }
};

// Bytes a vertex arena needs to hold @p capacity triangles (3 vertices each).
std::uint64_t arena_bytes_for(std::uint32_t capacity) {
  return static_cast<std::uint64_t>(capacity) * 3 * sizeof(Vertex);
}

// Read the atomic triangle count back and copy the emitted vertices into a
// Mesh with the trivial 0,1,2,... index run (independent triangles; a later
// shared-vertex dedup can shrink `vertices` without changing the Mesh
// contract). The dense extract's readback; the sparse path leaves its result on
// the device and downloads it separately.
Mesh collect_mesh(const Buffer& vertices, const Buffer& counter,
                  std::uint32_t capacity,
                  std::uint32_t* emitted_out = nullptr) {
  std::uint32_t emitted = 0;
  std::memcpy(&emitted, counter.mapped(), sizeof(std::uint32_t));
  // The dense path is worst-case sized, so the kernel never drops -- but the
  // count is a device write, and this clamp is what keeps the copy below inside
  // the arena regardless.
  emitted = std::min(emitted, capacity);
  if (emitted_out != nullptr) *emitted_out = emitted;

  const auto vertex_count = static_cast<std::size_t>(emitted) * 3;
  Mesh mesh;
  // TODO(mesh): resize() zero-initializes the vector and the memcpy below
  // immediately overwrites it -- two passes over the whole readback. There is
  // no resize-without-init on std::vector; revisit if the download shows up in
  // an ExtractTimings profile.
  mesh.vertices.resize(vertex_count);
  if (vertex_count > 0) {
    std::memcpy(mesh.vertices.data(), vertices.mapped(),
                vertex_count * sizeof(Vertex));
  }
  mesh.indices.resize(vertex_count);
  std::iota(mesh.indices.begin(), mesh.indices.end(), std::uint32_t{0});
  return mesh;
}

// Stopwatch for the opt-in ExtractTimings. Reading the clock is cheap, but it
// is skipped entirely when the caller wants no measurement, so the untimed path
// costs one branch per phase.
class PhaseClock {
 public:
  explicit PhaseClock(bool enabled) : enabled_(enabled) { restart(); }

  void restart() {
    if (enabled_) start_ = std::chrono::steady_clock::now();
  }

  // Milliseconds since the last restart, then restart for the next phase.
  double lap() {
    if (!enabled_) return 0.0;
    const auto now = std::chrono::steady_clock::now();
    const double ms =
        std::chrono::duration<double, std::milli>(now - start_).count();
    start_ = now;
    return ms;
  }

 private:
  bool enabled_;
  std::chrono::steady_clock::time_point start_{};
};

}  // namespace

std::uint32_t MarchingCubes::plan_capacity(std::uint32_t num_active,
                                           std::uint64_t worst_case) const {
  // Predict from density rather than react to an overflow: the last extract
  // measured how many triangles an active block carries, and scaling that by
  // THIS call's active set moves the plan ahead of a growing surface. A purely
  // reactive plan (whatever the arena happens to hold) discovers every size
  // increase by overflowing, which throws a whole dispatch away each time.
  const std::uint64_t per_block =
      tris_per_block_ != 0 ? tris_per_block_ : kSeedTrisPerBlock;
  const std::uint64_t estimate =
      static_cast<std::uint64_t>(num_active) * per_block;
  // Never below what the arena already holds: the dispatch is told this
  // number, so planning under the arena would drop triangles there was room
  // for and force a pointless refit. Never above the worst case -- more than
  // that cannot be emitted, so asking for it would waste memory outright.
  const std::uint64_t held = arena_capacity();
  return static_cast<std::uint32_t>(
      std::min(std::max(estimate, held), worst_case));
}

Status MarchingCubes::ensure_output_buffers(std::uint32_t capacity) {
  // Guard the REQUESTED capacity against the device's binding limit before any
  // growth headroom is added, so a surface that legitimately fits is never
  // rejected because the growth policy overshot.
  if (arena_bytes_for(capacity) > max_storage_buffer_range_) {
    return Status::invalid_argument(
        "MarchingCubes::extract: a vertex arena for " +
        std::to_string(capacity) +
        " triangles exceeds the device maxStorageBufferRange");
  }
  if (!counter_.valid()) {
    VR_ASSIGN(counter_, storage_buffer(*allocator_, sizeof(std::uint32_t)));
  }
  // The counter is the only per-call reset: 4 bytes, against an arena whose
  // stale tail is never read (the counter bounds the readback). It happens
  // ABOVE the reuse early-return below, and must stay there: a refit that
  // reallocated nothing still has to hand the retry a zeroed counter, or the
  // second dispatch accumulates onto the first's count.
  std::memset(counter_.mapped(), 0, sizeof(std::uint32_t));

  if (vertex_arena_.valid() && capacity <= arena_capacity()) {
    return {};  // the steady state -- no allocation at all
  }
  // Grow geometrically rather than to the exact request: the active set climbs
  // steadily through a scan, so exact sizing would reallocate (and re-fault)
  // this large buffer on most frames. The headroom multiplies the LARGER of
  // the request and what is held, so a refit to a measured count gets headroom
  // too (it is the request that a growing scan will outgrow next). Fall back to
  // the exact request whenever the headroom would not fit -- the request itself
  // already passed the guard above, so a surface that legitimately fits is
  // never rejected by an overshoot. Both tests run in 64-bit *before*
  // narrowing: 1.5x a near-uint32 capacity does not fit a uint32, and
  // truncating first could turn an over-large request into a small one that
  // passes the byte check.
  const std::uint64_t grown =
      std::max<std::uint64_t>(capacity, arena_capacity()) * 3 / 2;
  const bool headroom_fits =
      grown <= 0xFFFFFFFFull &&
      arena_bytes_for(static_cast<std::uint32_t>(grown)) <=
          max_storage_buffer_range_;
  const std::uint32_t grown_capacity =
      headroom_fits ? static_cast<std::uint32_t>(grown) : capacity;

  // Drop the old arena BEFORE allocating the new one, so the grow asks the
  // driver for one arena rather than two. VMA pools an emptied block instead of
  // returning it (see tests/core_memory_stats_test.cpp), so this holds against
  // the *driver* for an arena large enough to get a dedicated allocation; a
  // small one lives in a pooled block that VMA keeps, and process RSS can still
  // show both across the grow. Failing here leaves the extractor with no arena
  // rather than a capacity claiming a buffer that was never allocated.
  //
  // This assignment calls vmaDestroyBuffer *immediately* -- there is no fence
  // wait and no deferred retire. Safe for this tier's own work, which is
  // fence-blocked inside submit_single_time, but NOT for an external consumer
  // holding a DeviceMesh: see the seam-B TODO on MarchingCubesConfig, which is
  // why a bindable arena is not yet a drawable one.
  vertex_arena_ = Buffer{};
  // Released together: arena_capacity() is derived from the arena's size, so
  // dropping the arena is what marks the pair unsized, and the index run must
  // not outlive the arena it indexes.
  index_run_ = Buffer{};

  // Build both into locals and commit them together, so a failure on the second
  // allocation cannot leave a sized arena beside a null index run -- which
  // arena_capacity() would then report as ready and the next extract would hand
  // out as a DeviceMesh naming no index buffer.
  // config_ is applied on every grow, not just the first, so the consumer's
  // usage survives a reallocation (see MarchingCubesConfig).
  VR_ASSIGN(
      Buffer arena,
      storage_buffer(*allocator_,
                     static_cast<VkDeviceSize>(arena_bytes_for(grown_capacity)),
                     HostAccess::Random, config_.extra_vertex_usage));

  // The index run covers the whole arena and never changes shape, so it is
  // written once here rather than rebuilt per extract. iota straight into the
  // mapped buffer: no staging copy, and only on a grow. SequentialWrite because
  // this fill is the only host access it ever gets -- download() regenerates
  // the run on the host rather than reading back from write-combined memory.
  const std::size_t index_count = static_cast<std::size_t>(grown_capacity) * 3;
  VR_ASSIGN(Buffer indices_buf,
            storage_buffer(
                *allocator_,
                static_cast<VkDeviceSize>(index_count * sizeof(std::uint32_t)),
                HostAccess::SequentialWrite, config_.extra_index_usage));
  auto* indices = static_cast<std::uint32_t*>(indices_buf.mapped());
  std::iota(indices, indices + index_count, std::uint32_t{0});

  vertex_arena_ = std::move(arena);
  index_run_ = std::move(indices_buf);
  return {};
}

Result<MarchingCubes> MarchingCubes::create(Device& device,
                                            Allocator& allocator,
                                            const MarchingCubesConfig& config) {
  // Reject the one usage bit this repo's Device provably cannot honour, here
  // where the caller supplied it rather than inside the first extract's arena
  // grow (CLAUDE.md's "validate before creating"). Device::create never enables
  // bufferDeviceAddress, and the allocator is built without
  // VMA_ALLOCATOR_CREATE_BUFFER_DEVICE_ADDRESS_BIT, so this bit trips a VMA
  // assert in a debug build and drops VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT in
  // NDEBUG. Other bits are gated by features/extensions an adopted device may
  // legitimately have enabled, so they are the embedder's call, not ours.
  const VkBufferUsageFlags unsupported =
      VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT;
  if (((config.extra_vertex_usage | config.extra_index_usage) & unsupported) !=
      0) {
    return Status::invalid_argument(
        "MarchingCubes::create: VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT is "
        "not supported -- Device::create does not enable bufferDeviceAddress");
  }

  const VkDevice dev = device.handle();

  MarchingCubes mc;
  mc.device_ = &device;
  mc.allocator_ = &allocator;

  // Cache the 1-D dispatch's groupCountX ceiling so extract() can reject an
  // over-large grid cleanly (see dispatch()), plus the storage-buffer binding
  // limit so extract() can reject a worst-case vertex arena that would exceed
  // it before the allocation fails opaquely.
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  mc.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];
  mc.max_storage_buffer_range_ = props.limits.maxStorageBufferRange;
  mc.config_ = config;

  // Two kernels share one pool. The dense kernel binds five storage buffers:
  // tables (persistent) + the per-extract samples / colors / vertices /
  // counter. The sparse kernel binds eight: tables (persistent) + the
  // per-extract active blocks / neighbour LUT / tsdf / weight / color /
  // vertices / counter. KernelSetBuilder (core/compute_kernel.hpp) builds each
  // layout + pipeline and allocates its set from a shared pool sized to the
  // exact descriptor total.
  VkPushConstantRange push{};
  push.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push.offset = 0;
  push.size = sizeof(PushConstants);
  VkPushConstantRange push_sparse = push;
  push_sparse.size = sizeof(SparsePushConstants);
  KernelSetBuilder kb(dev);
  VR_TRY(kb.add(mc.kernel_, vr_marching_cubes_comp_spv,
                vr_marching_cubes_comp_spv_size, 5, &push));
  VR_TRY(kb.add(mc.kernel_sparse_, vr_marching_cubes_sparse_comp_spv,
                vr_marching_cubes_sparse_comp_spv_size, 8, &push_sparse));
  VR_ASSIGN(mc.pool_, kb.build());

  // Upload the lookup tables once and bind them at set binding 0 of both
  // kernels for good. The constexpr header arrays are the single source;
  // flatten them into the shader block layout.
  VR_ASSIGN(mc.tables_, storage_buffer(allocator, sizeof(McTables),
                                       HostAccess::SequentialWrite));
  McTables host_tables;
  std::memcpy(host_tables.tri_table, kTriTable, sizeof(kTriTable));
  std::memcpy(host_tables.corner_offset, kCornerOffset, sizeof(kCornerOffset));
  std::memcpy(host_tables.edge_to_vert, kEdgeToVert, sizeof(kEdgeToVert));
  std::memcpy(mc.tables_.mapped(), &host_tables, sizeof(McTables));
  mc.kernel_.set.write_storage_buffer(0, mc.tables_.handle(), 0, VK_WHOLE_SIZE);
  mc.kernel_sparse_.set.write_storage_buffer(0, mc.tables_.handle(), 0,
                                             VK_WHOLE_SIZE);

  // A 1-element dummy for the sparse kernel's color slot when a grid carries no
  // color attribute; bound now so binding 5 is always valid, overwritten with a
  // real color buffer per extract when one exists.
  VR_ASSIGN(mc.color_dummy_, storage_buffer(allocator, sizeof(std::uint32_t),
                                            HostAccess::SequentialWrite));
  std::memset(mc.color_dummy_.mapped(), 0, sizeof(std::uint32_t));
  mc.kernel_sparse_.set.write_storage_buffer(5, mc.color_dummy_.handle(), 0,
                                             VK_WHOLE_SIZE);

  return mc;
}

Result<Mesh> MarchingCubes::extract(const volume::Voxel* samples,
                                    std::size_t count, const DenseGrid& grid,
                                    float iso, const Vec3u8* colors) {
  if (!valid()) {
    return Status::invalid_argument("MarchingCubes::extract: moved-from");
  }
  if (samples == nullptr) {
    return Status::invalid_argument("MarchingCubes::extract: samples is null");
  }
  if (grid.dims.x < 2 || grid.dims.y < 2 || grid.dims.z < 2) {
    return Status::invalid_argument(
        "MarchingCubes::extract: grid must be at least 2x2x2 samples");
  }
  // `!(x > 0)` rather than `x <= 0` so a NaN voxel_size is rejected too (every
  // comparison with NaN is false, so `<= 0` would let it through).
  if (!(grid.voxel_size > 0.0f)) {
    return Status::invalid_argument(
        "MarchingCubes::extract: voxel_size must be > 0");
  }
  const auto sample_count = static_cast<std::uint64_t>(grid.dims.x) *
                            static_cast<std::uint64_t>(grid.dims.y) *
                            static_cast<std::uint64_t>(grid.dims.z);
  if (static_cast<std::uint64_t>(count) != sample_count) {
    return Status::invalid_argument(
        "MarchingCubes::extract: count must equal dims.x*dims.y*dims.z");
  }

  // Worst-case triangle capacity: one cell per (dims-1) step, 5 triangles each.
  const std::uint64_t cells = static_cast<std::uint64_t>(grid.dims.x - 1) *
                              static_cast<std::uint64_t>(grid.dims.y - 1) *
                              static_cast<std::uint64_t>(grid.dims.z - 1);
  const std::uint64_t capacity64 = cells * kMaxTrisPerCell;
  // capacity + the per-cell dispatch index both flow through 32-bit shader
  // values, so keep the worst case inside uint32.
  // The dense path keeps the worst-case sizing: it takes a caller-supplied
  // sample grid (the analytic/test entry point), so its cell count is small and
  // bounded by the caller, and one dispatch with no measurement step is the
  // simpler thing to keep correct.
  // TODO(mesh): fit this path to the surface too, as the sparse extract does.
  // The two share one retained arena, so a large dense call grows it to the
  // dense worst case and every later sparse extract plans from there -- which
  // forfeits the fitted arena for a process that uses both entry points.
  if (capacity64 > 0xFFFFFFFFull || cells > 0xFFFFFFFFull) {
    return Status::invalid_argument(
        "MarchingCubes::extract: grid too large for this slice");
  }
  const auto capacity = static_cast<std::uint32_t>(capacity64);

  // Per-extract buffers (sized to this grid): the samples in, the vertex arena
  // out (3 vertices per triangle at worst-case capacity), and the atomic
  // triangle counter.
  VR_ASSIGN(
      Buffer samples_buf,
      storage_buffer(*allocator_,
                     static_cast<VkDeviceSize>(count) * sizeof(volume::Voxel),
                     HostAccess::SequentialWrite));
  std::memcpy(samples_buf.mapped(), samples, count * sizeof(volume::Voxel));

  // Colors (optional, parallel to samples): each sample's RGB packed into the
  // low three bytes of a uint (the kernel reads it back with unpackUnorm4x8 and
  // takes .rgb, so the high byte is unused and left zero). Always bound so the
  // descriptor is valid; the has_color push flag tells the kernel whether to
  // read it. Absent -> a 1-element dummy buffer + opaque-white vertices.
  const std::uint32_t has_color = colors != nullptr ? 1u : 0u;
  Buffer colors_buf;
  if (colors != nullptr) {
    VR_ASSIGN(colors_buf, storage_buffer(*allocator_,
                                         static_cast<VkDeviceSize>(count) *
                                             sizeof(std::uint32_t),
                                         HostAccess::SequentialWrite));
    // Pack straight into the mapped buffer -- SequentialWrite is exactly this
    // forward, write-once pattern, so no staging vector or second copy.
    auto* packed = static_cast<std::uint32_t*>(colors_buf.mapped());
    for (std::size_t i = 0; i < count; ++i) {
      packed[i] = static_cast<std::uint32_t>(colors[i].x) |
                  (static_cast<std::uint32_t>(colors[i].y) << 8) |
                  (static_cast<std::uint32_t>(colors[i].z) << 16);
    }
  } else {
    VR_ASSIGN(colors_buf, storage_buffer(*allocator_, sizeof(std::uint32_t),
                                         HostAccess::SequentialWrite));
    std::memset(colors_buf.mapped(), 0, sizeof(std::uint32_t));
  }

  // This call is about to overwrite -- and, on a grow, reallocate -- the shared
  // arena, so every outstanding DeviceMesh is stale from here on, whether or
  // not the call succeeds. Bump before the first thing that touches it.
  ++generation_;
  VR_TRY(ensure_output_buffers(capacity));

  kernel_.set.write_storage_buffer(1, samples_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(2, colors_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(3, vertex_arena_.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(4, counter_.handle(), 0, VK_WHOLE_SIZE);

  const PushConstants push{grid.dims, grid.voxel_size,  grid.origin, iso,
                           capacity,  kWeightThreshold, has_color};
  VR_TRY(dispatch(*device_, kernel_, &push, sizeof(push),
                  group_count(static_cast<std::uint32_t>(cells), kLocalSize),
                  max_workgroup_count_x_));

  return collect_mesh(vertex_arena_, counter_, capacity);
}

Result<Mesh> MarchingCubes::extract(volume::VoxelBlockGrid& grid, float iso,
                                    ExtractTimings* timings) {
  VR_ASSIGN(const DeviceMesh device_mesh, extract_device(grid, iso, timings));
  // The host copy is part of this call's readback, so it belongs in the phase
  // that names it -- extract_device stamped readback_ms with the 4-byte counter
  // read alone, which is right for that entry point but would leave the host
  // path's ~45 MB copy uncounted in ExtractTimings::total_ms.
  PhaseClock download_clock(timings != nullptr);
  VR_ASSIGN(Mesh mesh, download(device_mesh));
  if (timings != nullptr) timings->readback_ms += download_clock.lap();
  return mesh;
}

Result<Mesh> MarchingCubes::download(const DeviceMesh& device_mesh) const {
  // An empty mesh copies to an empty Mesh without touching the buffers, which
  // a grid with no active blocks never even allocated.
  if (device_mesh.empty()) {
    return Mesh{};
  }
  // Only this extractor's newest extract may be downloaded. Checked by
  // generation, NOT by buffer handle: the arena is grow-only and reused in
  // place, so a superseded view names the very same VkBuffer as the live one
  // and a handle comparison would accept it and hand back the newer extract's
  // geometry under this view's stale counts.
  if (device_mesh.generation != generation_ || !device_mesh.valid()) {
    return Status::invalid_argument(
        "MarchingCubes::download: the DeviceMesh is not this extractor's "
        "current extract (superseded by a later one, or from another "
        "extractor)");
  }
  Mesh mesh;
  const auto vertex_count = static_cast<std::size_t>(device_mesh.vertex_count);
  mesh.vertices.resize(vertex_count);
  mesh.indices.resize(vertex_count);
  if (vertex_count > 0) {
    std::memcpy(mesh.vertices.data(), vertex_arena_.mapped(),
                vertex_count * sizeof(Vertex));
    // Regenerated, not read back: the run is the identity 0,1,2,... and
    // index_run_ is write-combined (SequentialWrite), where host reads are
    // pathologically slow. Generating it costs nothing and touches no device
    // memory.
    std::iota(mesh.indices.begin(), mesh.indices.end(), std::uint32_t{0});
  }
  return mesh;
}

Result<DeviceMesh> MarchingCubes::extract_device(volume::VoxelBlockGrid& grid,
                                                 float iso,
                                                 ExtractTimings* timings) {
  // Fully overwrite the caller's struct up front, so the accumulating spans
  // below start from zero and one instance can be reused across frames. A
  // failed call then reports zeros rather than a previous call's numbers.
  if (timings != nullptr) *timings = ExtractTimings{};
  if (!valid()) {
    return Status::invalid_argument("MarchingCubes::extract: moved-from");
  }
  if (!grid.valid()) {
    return Status::invalid_argument(
        "MarchingCubes::extract: grid is moved-from");
  }
  // The grid must carry the float tsdf + weight the sparse kernel samples; the
  // uint32 color attribute is optional (its absence -> opaque-white vertices).
  VR_ASSIGN(volume::AttributeView tsdf_view, grid.attribute("tsdf"));
  VR_ASSIGN(volume::AttributeView weight_view, grid.attribute("weight"));
  if (tsdf_view.element_size != sizeof(float) ||
      weight_view.element_size != sizeof(float)) {
    return Status::invalid_argument(
        "MarchingCubes::extract: tsdf/weight must be float attributes");
  }
  const bool has_color = grid.has_attribute("color");
  volume::AttributeView color_view{};
  if (has_color) {
    VR_ASSIGN(color_view, grid.attribute("color"));
    if (color_view.element_size != sizeof(std::uint32_t)) {
      return Status::invalid_argument(
          "MarchingCubes::extract: color must be a uint32 attribute");
    }
  }

  // The active set drives the dispatch (one thread per voxel of each block) and
  // supplies the neighbour lookup. An empty map means nothing to mesh.
  PhaseClock phase_clock(timings != nullptr);
  VR_ASSIGN(std::vector<volume::BlockIndex> active,
            grid.map().compact_active_blocks());
  if (timings != nullptr) timings->compact_ms = phase_clock.lap();
  if (active.empty()) {
    // Nothing to mesh. Still name the (possibly unsized) buffers so a caller
    // can treat the result uniformly; the zero counts make it empty().
    DeviceMesh device_mesh;
    device_mesh.vertices = vertex_arena_.handle();
    device_mesh.indices = index_run_.handle();
    device_mesh.vertex_usage = vertex_arena_.usage();
    device_mesh.index_usage = index_run_.usage();
    device_mesh.generation = ++generation_;
    return device_mesh;
  }

  const volume::VoxelGridParams& gp = grid.grid();
  const std::int32_t bs = gp.block_size;
  const auto vpb = static_cast<std::uint32_t>(gp.voxels_per_block);
  const auto num_active = static_cast<std::uint32_t>(active.size());

  // One invocation per voxel of each active block; worst-case 5 triangles each.
  // Both the thread index and the triangle capacity flow through 32-bit shader
  // values, so keep the thread count inside uint32.
  const std::uint64_t threads =
      static_cast<std::uint64_t>(num_active) * static_cast<std::uint64_t>(vpb);
  const std::uint64_t worst_case = threads * kMaxTrisPerCell;
  // Both the thread index and the triangle counter are 32-bit shader values.
  // The counter bound matters even though the arena is no longer sized for the
  // worst case: the kernel bumps `tri_count` for every triangle the field
  // produces, dropped ones included, so a field whose worst case exceeds uint32
  // could wrap it -- and the host, which now trusts that count, would publish a
  // handful of triangles as the whole surface. Rejected here, before the
  // neighbour table, the uploads and a dispatch.
  if (threads > 0xFFFFFFFFull || worst_case > 0xFFFFFFFFull) {
    return Status::invalid_argument(
        "MarchingCubes::extract: active set too large for this slice");
  }
  // The arena is sized to what the surface actually emits, not to the
  // 5-triangles-per-cell worst case. Real fields are nowhere near that bound --
  // a room scan fills ~2% of it -- and since the arena is now *retained*, the
  // worst case was resident memory rather than a transient over-allocation
  // (~1.8 GB against ~38 MB of triangles on Replica room0).
  //
  // Correctness does not depend on the guess: the kernel bumps `tri_count`
  // for every triangle and drops those past `capacity`, so an undersized arena
  // is *detected*, never silently truncated. The count is a property of the
  // field, not of the atomic ordering, so refitting to it and re-running is
  // guaranteed to fit. That makes this a one-dispatch steady state that pays a
  // second dispatch only when the plan undershoots the surface, rather than
  // the unconditional two-dispatch count-then-fill this replaces.
  const std::uint32_t capacity = plan_capacity(num_active, worst_case);

  // Neighbour lookup: map each active block coordinate to its voxel-array base,
  // then, per block, gather the eight pointers of its 2x2x2 +neighbourhood
  // (octant = ox + 2*oy + 4*oz). -1 marks an unallocated neighbour, which the
  // kernel treats as no-surface. Built host-side from the compacted set, so the
  // kernel does no device-side hash probe.
  phase_clock.restart();
  std::unordered_map<Vec3i, std::int32_t, CoordHash> ptr_by_coord;
  ptr_by_coord.reserve(active.size() * 2);
  for (const volume::BlockIndex& b : active) {
    ptr_by_coord.emplace(b.coord, b.ptr);
  }
  std::vector<std::int32_t> neighbour_lut(static_cast<std::size_t>(num_active) *
                                          8);
  for (std::uint32_t i = 0; i < num_active; ++i) {
    const Vec3i c = active[i].coord;
    for (int oct = 0; oct < 8; ++oct) {
      const Vec3i n = c + Vec3i(oct & 1, (oct >> 1) & 1, (oct >> 2) & 1);
      const auto it = ptr_by_coord.find(n);
      neighbour_lut[static_cast<std::size_t>(i) * 8 +
                    static_cast<std::size_t>(oct)] =
          it != ptr_by_coord.end() ? it->second : -1;
    }
  }

  // Per-extract inputs: the active blocks + neighbour LUT (write-once), and the
  // vertex arena + atomic counter out. Attribute buffers bind straight from the
  // grid (no copy).
  if (timings != nullptr) timings->neighbour_lut_ms = phase_clock.lap();
  VR_ASSIGN(Buffer active_buf,
            storage_buffer(*allocator_,
                           static_cast<VkDeviceSize>(num_active) *
                               sizeof(volume::BlockIndex),
                           HostAccess::SequentialWrite));
  std::memcpy(
      active_buf.mapped(), active.data(),
      static_cast<std::size_t>(num_active) * sizeof(volume::BlockIndex));
  VR_ASSIGN(
      Buffer neighbour_buf,
      storage_buffer(*allocator_, neighbour_lut.size() * sizeof(std::int32_t),
                     HostAccess::SequentialWrite));
  std::memcpy(neighbour_buf.mapped(), neighbour_lut.data(),
              neighbour_lut.size() * sizeof(std::int32_t));

  if (timings != nullptr) timings->input_upload_ms = phase_clock.lap();
  // This call is about to overwrite -- and, on a grow, reallocate -- the arena,
  // so every outstanding DeviceMesh is stale from here on, whether or not the
  // call succeeds. Bump before the first thing that touches it, not on the
  // success path: a failure between here and the return would otherwise leave
  // a superseded DeviceMesh passing download()'s currency check and reading
  // this call's geometry under its own stale counts.
  ++generation_;
  VR_TRY(ensure_output_buffers(capacity));
  if (timings != nullptr) timings->arena_alloc_ms = phase_clock.lap();

  kernel_sparse_.set.write_storage_buffer(1, active_buf.handle(), 0,
                                          VK_WHOLE_SIZE);
  kernel_sparse_.set.write_storage_buffer(2, neighbour_buf.handle(), 0,
                                          VK_WHOLE_SIZE);
  kernel_sparse_.set.write_storage_buffer(3, tsdf_view.buffer->handle(), 0,
                                          VK_WHOLE_SIZE);
  kernel_sparse_.set.write_storage_buffer(4, weight_view.buffer->handle(), 0,
                                          VK_WHOLE_SIZE);
  kernel_sparse_.set.write_storage_buffer(
      5, has_color ? color_view.buffer->handle() : color_dummy_.handle(), 0,
      VK_WHOLE_SIZE);

  // Both output bindings are written once: the counter's handle never changes
  // (ensure_output_buffers creates it only when it holds none), and the arena's
  // changes only when a refit reallocates it -- which rebinds it there.
  kernel_sparse_.set.write_storage_buffer(6, vertex_arena_.handle(), 0,
                                          VK_WHOLE_SIZE);
  kernel_sparse_.set.write_storage_buffer(7, counter_.handle(), 0,
                                          VK_WHOLE_SIZE);
  if (timings != nullptr) timings->descriptor_ms = phase_clock.lap();

  // Run the surface, read the count, and re-run once if the arena was too
  // small. `tri_count` counts every triangle the field produces -- the kernel
  // drops those past `capacity` but still bumps -- so an undersized arena
  // reports the exact size it needed, and the count is a property of the field
  // rather than of the atomic ordering, so the refitted retry cannot overflow
  // again. Bounded at two iterations for that reason.
  //
  // The dispatch is told the arena's *full* capacity rather than the planned
  // number, so it never drops a triangle the arena had room for -- and that
  // keeps `requested <= arena_capacity()` true by construction, which is what
  // bounds the vertex count published below.
  std::uint32_t requested = arena_capacity();
  std::uint32_t produced = 0;
  for (int attempt = 0; attempt < 2; ++attempt) {
    const SparsePushConstants push{bs,
                                   static_cast<std::int32_t>(vpb),
                                   gp.voxel_size,
                                   iso,
                                   num_active,
                                   requested,
                                   kWeightThreshold,
                                   has_color ? 1u : 0u};
    VR_TRY(
        dispatch(*device_, kernel_sparse_, &push, sizeof(push),
                 group_count(static_cast<std::uint32_t>(threads), kLocalSize),
                 max_workgroup_count_x_));
    if (timings != nullptr) {
      timings->dispatch_ms += phase_clock.lap();
      ++timings->dispatches;
    }

    // Only the 4-byte counter comes back; the geometry stays where the kernel
    // wrote it.
    std::memcpy(&produced, counter_.mapped(), sizeof(std::uint32_t));
    if (timings != nullptr) timings->readback_ms += phase_clock.lap();
    if (produced <= requested) {
      break;  // everything the field emitted is in the arena
    }
    if (attempt == 1) {
      // Cannot happen -- the same field emits the same count, so the refitted
      // arena fits it -- but report rather than hand back a truncated mesh if
      // that assumption is ever broken.
      return Status::out_of_memory(
          "MarchingCubes::extract: the vertex arena still overflowed after "
          "refitting it to the measured triangle count");
    }
    // Refit to the measured count (ensure_output_buffers adds the growth
    // headroom, and re-zeroes the counter the retry is about to bump), then
    // rebind the arena in case it was reallocated.
    VR_TRY(ensure_output_buffers(produced));
    kernel_sparse_.set.write_storage_buffer(6, vertex_arena_.handle(), 0,
                                            VK_WHOLE_SIZE);
    requested = arena_capacity();
    if (timings != nullptr) timings->arena_alloc_ms += phase_clock.lap();
  }
  // Clamped against the arena itself, not against `requested`: this count is
  // what download()'s memcpy and the texturer's `num_vertices` bound run on, so
  // bound it by the buffer that has to hold it rather than by a variable that
  // tracks that buffer.
  const std::uint32_t emitted = std::min(produced, arena_capacity());

  // Record the density this surface actually had, so the next call's plan
  // scales it by that call's active set instead of discovering the size by
  // overflowing. Rounded up, so any non-empty surface records at least one
  // triangle per block; a surface that emitted nothing records 0, and the next
  // plan falls back to the seed.
  tris_per_block_ = static_cast<std::uint32_t>(
      (static_cast<std::uint64_t>(emitted) + num_active - 1) / num_active);

  DeviceMesh device_mesh;
  device_mesh.vertices = vertex_arena_.handle();
  device_mesh.indices = index_run_.handle();
  device_mesh.vertex_usage = vertex_arena_.usage();
  device_mesh.index_usage = index_run_.usage();
  device_mesh.triangle_count = emitted;
  device_mesh.vertex_count = emitted * 3;
  device_mesh.generation = generation_;
  if (timings != nullptr) {
    timings->active_blocks = num_active;
    timings->triangle_capacity = requested;
    timings->emitted_triangles = emitted;
    // What the extractor is holding, not what this call asked for: the arena is
    // retained and grown, so a steady-state call allocates nothing and still
    // reports it.
    timings->arena_bytes = vertex_arena_.size();
  }
  return device_mesh;
}

}  // namespace volumetric_kit::recon::mesh
