// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tao Jin

#include "volumetric_kit/recon/mesh/marching_cubes.hpp"

#include <algorithm>
#include <cstddef>
#include <cstring>
#include <numeric>
#include <string>
#include <utility>
#include <vector>

#include "volumetric_kit/recon/core/allocator.hpp"
#include "volumetric_kit/recon/core/compute_kernel.hpp"
#include "volumetric_kit/recon/core/device.hpp"
#include "volumetric_kit/recon/core/vulkan.hpp"
#include "volumetric_kit/recon/mesh/marching_cubes_tables.hpp"

// Embedded SPIR-V (generated by vr_embed_shaders onto a PRIVATE include path).
#include "marching_cubes_comp.spv.hpp"

namespace volumetric_kit::recon::mesh {
namespace {

// Local group size, matching `layout(local_size_x = 256)` in the kernel.
constexpr std::uint32_t kLocalSize = 256;

// Worst-case triangles a single marching-cubes cell can emit (5 per the table).
constexpr std::uint64_t kMaxTrisPerCell = 5;

// A corner with weight at or below this is treated as unintegrated, and any
// cell touching it is skipped. Small and positive so a never-integrated voxel
// (weight 0) is excluded while any genuine integration counts. The `tsdf` tier
// will surface this as a tunable knob; the dense analytic path fills every
// weight.
constexpr float kWeightThreshold = 1e-6f;

// The lookup tables, flattened for upload -- byte-identical to the GLSL
// `Tables` block (scalar layout, all-int so std430 and scalar agree). One
// definition of the tables (the constexpr arrays in the header) feeds both
// sides.
struct McTables {
  std::int32_t tri_table[256 * 16];
  std::int32_t corner_offset[8 * 3];
  std::int32_t edge_to_vert[12 * 2];
};
static_assert(sizeof(McTables) ==
                  (256 * 16 + 8 * 3 + 12 * 2) * sizeof(std::int32_t),
              "McTables must be tightly packed for the shader ABI");

// The push-constant block the kernel reads (mirrors `PushConstants` in
// marching_cubes.comp under scalar layout).
struct PushConstants {
  Vec3i dims;
  float voxel_size;
  Vec3f origin;
  float iso;
  std::uint32_t capacity;
  float weight_threshold;
  std::uint32_t has_color;  // 0 = no color input; vertices get opaque white
};
static_assert(sizeof(PushConstants) == 44, "PushConstants must be 44 bytes");
static_assert(offsetof(PushConstants, dims) == 0, "PushConstants layout drift");
static_assert(offsetof(PushConstants, voxel_size) == 12, "PushConstants drift");
static_assert(offsetof(PushConstants, origin) == 16, "PushConstants drift");
static_assert(offsetof(PushConstants, iso) == 28, "PushConstants drift");
static_assert(offsetof(PushConstants, capacity) == 32, "PushConstants drift");
static_assert(offsetof(PushConstants, weight_threshold) == 36,
              "PushConstants layout drift");
static_assert(offsetof(PushConstants, has_color) == 40,
              "PushConstants layout drift");

std::uint32_t group_count(std::uint32_t items) {
  // Ceil-divide without the `items + kLocalSize - 1` term, which overflows
  // uint32 near the top of the range and wraps to ~0 groups (a silent no-op
  // dispatch); mirrors the volume tier's group_count.
  return items / kLocalSize + (items % kLocalSize != 0u ? 1u : 0u);
}

// A host-visible, host-mapped storage buffer of the given byte size.
Result<Buffer> storage_buffer(Allocator& allocator, VkDeviceSize bytes,
                              HostAccess access = HostAccess::Random) {
  BufferDesc desc;
  desc.size = bytes;
  desc.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
  desc.memory = MemoryUsage::HostVisible;
  desc.mapped = true;
  desc.host_access = access;
  return allocator.create_buffer(desc);
}

}  // namespace

Result<MarchingCubes> MarchingCubes::create(Device& device,
                                            Allocator& allocator) {
  const VkDevice dev = device.handle();

  MarchingCubes mc;
  mc.device_ = &device;
  mc.allocator_ = &allocator;

  // Cache the 1-D dispatch's groupCountX ceiling so extract() can reject an
  // over-large grid cleanly (see dispatch()).
  VkPhysicalDeviceProperties props{};
  vkGetPhysicalDeviceProperties(device.physical_device(), &props);
  mc.max_workgroup_count_x_ = props.limits.maxComputeWorkGroupCount[0];

  // The kernel binds five storage buffers: tables (persistent) + the
  // per-extract samples / colors / vertices / counter. KernelSetBuilder
  // (core/compute_kernel.hpp) builds its layout + pipeline and allocates its
  // set from a shared pool sized to the exact descriptor total.
  VkPushConstantRange push{};
  push.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
  push.offset = 0;
  push.size = sizeof(PushConstants);
  KernelSetBuilder kb(dev);
  VR_TRY(kb.add(mc.kernel_, vr_marching_cubes_comp_spv,
                vr_marching_cubes_comp_spv_size, 5, &push));
  VR_ASSIGN(mc.pool_, kb.build());

  // Upload the lookup tables once and bind them at set binding 0 for good. The
  // constexpr header arrays are the single source; flatten them into the shader
  // block layout.
  VR_ASSIGN(mc.tables_, storage_buffer(allocator, sizeof(McTables),
                                       HostAccess::SequentialWrite));
  McTables host_tables;
  std::memcpy(host_tables.tri_table, kTriTable, sizeof(kTriTable));
  std::memcpy(host_tables.corner_offset, kCornerOffset, sizeof(kCornerOffset));
  std::memcpy(host_tables.edge_to_vert, kEdgeToVert, sizeof(kEdgeToVert));
  std::memcpy(mc.tables_.mapped(), &host_tables, sizeof(McTables));
  mc.kernel_.set.write_storage_buffer(0, mc.tables_.handle(), 0, VK_WHOLE_SIZE);

  return mc;
}

Result<Mesh> MarchingCubes::extract(const volume::Voxel* samples,
                                    std::size_t count, const DenseGrid& grid,
                                    float iso, const Vec3u8* colors) {
  if (!valid()) {
    return Status::invalid_argument("MarchingCubes::extract: moved-from");
  }
  if (samples == nullptr) {
    return Status::invalid_argument("MarchingCubes::extract: samples is null");
  }
  if (grid.dims.x < 2 || grid.dims.y < 2 || grid.dims.z < 2) {
    return Status::invalid_argument(
        "MarchingCubes::extract: grid must be at least 2x2x2 samples");
  }
  // `!(x > 0)` rather than `x <= 0` so a NaN voxel_size is rejected too (every
  // comparison with NaN is false, so `<= 0` would let it through).
  if (!(grid.voxel_size > 0.0f)) {
    return Status::invalid_argument(
        "MarchingCubes::extract: voxel_size must be > 0");
  }
  const auto sample_count = static_cast<std::uint64_t>(grid.dims.x) *
                            static_cast<std::uint64_t>(grid.dims.y) *
                            static_cast<std::uint64_t>(grid.dims.z);
  if (static_cast<std::uint64_t>(count) != sample_count) {
    return Status::invalid_argument(
        "MarchingCubes::extract: count must equal dims.x*dims.y*dims.z");
  }

  // Worst-case triangle capacity: one cell per (dims-1) step, 5 triangles each.
  const std::uint64_t cells = static_cast<std::uint64_t>(grid.dims.x - 1) *
                              static_cast<std::uint64_t>(grid.dims.y - 1) *
                              static_cast<std::uint64_t>(grid.dims.z - 1);
  const std::uint64_t capacity64 = cells * kMaxTrisPerCell;
  // capacity + the per-cell dispatch index both flow through 32-bit shader
  // values, so keep the worst case inside uint32.
  // TODO(mesh): a two-pass count->fill would size the vertex buffer exactly
  // instead of at the 5-per-cell worst case; the incremental block-mesh pool
  // slice supersedes both.
  if (capacity64 > 0xFFFFFFFFull || cells > 0xFFFFFFFFull) {
    return Status::invalid_argument(
        "MarchingCubes::extract: grid too large for this slice");
  }
  const auto capacity = static_cast<std::uint32_t>(capacity64);

  // Per-extract buffers (sized to this grid): the samples in, the vertex arena
  // out (3 vertices per triangle at worst-case capacity), and the atomic
  // triangle counter.
  VR_ASSIGN(
      Buffer samples_buf,
      storage_buffer(*allocator_,
                     static_cast<VkDeviceSize>(count) * sizeof(volume::Voxel),
                     HostAccess::SequentialWrite));
  std::memcpy(samples_buf.mapped(), samples, count * sizeof(volume::Voxel));

  // Colors (optional, parallel to samples): each RGB packed into a uint
  // (unpackUnorm4x8 in the kernel). Always bound so the descriptor is valid;
  // the has_color push flag tells the kernel whether to read it. Absent -> a
  // 1-element dummy buffer + opaque-white vertices.
  const std::uint32_t has_color = colors != nullptr ? 1u : 0u;
  Buffer colors_buf;
  if (colors != nullptr) {
    std::vector<std::uint32_t> packed(count);
    for (std::size_t i = 0; i < count; ++i) {
      packed[i] = static_cast<std::uint32_t>(colors[i].x) |
                  (static_cast<std::uint32_t>(colors[i].y) << 8) |
                  (static_cast<std::uint32_t>(colors[i].z) << 16) |
                  (std::uint32_t{0xFF} << 24);
    }
    VR_ASSIGN(colors_buf, storage_buffer(*allocator_,
                                         static_cast<VkDeviceSize>(count) *
                                             sizeof(std::uint32_t),
                                         HostAccess::SequentialWrite));
    std::memcpy(colors_buf.mapped(), packed.data(),
                count * sizeof(std::uint32_t));
  } else {
    VR_ASSIGN(colors_buf, storage_buffer(*allocator_, sizeof(std::uint32_t),
                                         HostAccess::SequentialWrite));
    std::memset(colors_buf.mapped(), 0, sizeof(std::uint32_t));
  }

  VR_ASSIGN(Buffer vertices_buf,
            storage_buffer(*allocator_, static_cast<VkDeviceSize>(capacity) *
                                            3 * sizeof(Vertex)));
  VR_ASSIGN(Buffer counter_buf,
            storage_buffer(*allocator_, sizeof(std::uint32_t)));
  std::memset(counter_buf.mapped(), 0, sizeof(std::uint32_t));

  kernel_.set.write_storage_buffer(1, samples_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(2, colors_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(3, vertices_buf.handle(), 0, VK_WHOLE_SIZE);
  kernel_.set.write_storage_buffer(4, counter_buf.handle(), 0, VK_WHOLE_SIZE);

  const PushConstants push{grid.dims, grid.voxel_size,  grid.origin, iso,
                           capacity,  kWeightThreshold, has_color};
  VR_TRY(dispatch(*device_, kernel_, &push, sizeof(push),
                  group_count(static_cast<std::uint32_t>(cells)),
                  max_workgroup_count_x_));

  std::uint32_t emitted = 0;
  std::memcpy(&emitted, counter_buf.mapped(), sizeof(std::uint32_t));
  // Worst-case capacity means the kernel never drops, but clamp defensively so
  // a future smaller-capacity mode cannot over-read the vertex arena.
  emitted = std::min(emitted, capacity);

  const auto vertex_count = static_cast<std::size_t>(emitted) * 3;
  Mesh mesh;
  mesh.vertices.resize(vertex_count);
  if (vertex_count > 0) {
    std::memcpy(mesh.vertices.data(), vertices_buf.mapped(),
                vertex_count * sizeof(Vertex));
  }
  // Independent triangles: indices are the trivial 0,1,2,... run. Carried so a
  // later shared-vertex dedup slice can shrink `vertices` without changing the
  // Mesh contract.
  mesh.indices.resize(vertex_count);
  std::iota(mesh.indices.begin(), mesh.indices.end(), std::uint32_t{0});
  return mesh;
}

}  // namespace volumetric_kit::recon::mesh
